/* Capítulos 8 a 11 y anexos. */
const U = require('./doc_parte1.js');
const {
  Paragraph, TextRun, AlignmentType, BorderStyle,
  AZUL, AMBAR, GRIS, FONDO, ANCHO_TABLA,
  p, neg, txt, cur, mono, h1, h2, h3, formula, nota, vinetas, numerada,
  tabla, figura, pieTabla, salto,
} = U;

function validacion() {
  return [
    h1('8. Validación estadística'),
    h2('8.1 El procedimiento'),
    p('La validación se hizo por backtesting de origen móvil, que es el procedimiento estándar para modelos de proyección temporal y el único que evita contaminar la evaluación con información del futuro.'),
    ...numerada([
      'Se fija un semestre de corte y se descarta todo lo posterior.',
      'Se reestima el modelo completo —tablas de transición, constantes de contracción y ponderación de recencia— usando exclusivamente los datos hasta ese corte.',
      'Se proyectan los semestres siguientes, alimentando el modelo con los ingresantes realmente observados —con su modalidad real— para aislar el error del modelo del error del supuesto de admisión.',
      'La condición de llegada y el reparto r se recalculan dentro de la ventana truncada, también en el panel de la base central: en cada corte el modelo sólo puede saber lo que se observa hasta ese semestre, de modo que un estudiante cuya interrupción ocurriera después del corte no cuenta como reinicio, y una matrícula posterior al corte no cuenta como continuación.',
      'Se compara con la matrícula efectivamente registrada, en los diez niveles de agregación.',
      'Se repite desplazando el corte.',
    ]),
    p([txt('Es esencial que la reestimación sea completa en cada corte. Si las constantes de contracción o λ se hubieran fijado con toda la muestra y sólo se reproyectara, el ejercicio filtraría información del futuro y los errores saldrían artificialmente bajos. Aquí se recalcula todo, incluida la selección de λ del apartado 6.7, que se ejecutó '), cur('dentro'), txt(' del bucle de validación, y lo mismo vale para los contrastes de especificación de los apartados 6.5 y 6.6.')]),
    p('Con ocho semestres de historia y la exigencia de al menos cinco para estimar, resultan tres orígenes de reestimación (hasta 2025-I, 2025-II y 2026-I) y seis comparaciones origen-horizonte.'),

    h2('8.2 La métrica'),
    p('Se emplea el error porcentual absoluto ponderado (EPAP, o WAPE en la literatura anglosajona):'),
    ...formula([
      '          Σ | proyectado_i − observado_i |',
      'EPAP =   ─────────────────────────────────',
      '                Σ  observado_i',
    ]),
    p('Se prefiere al error porcentual absoluto medio (EPAM) porque este último otorga el mismo peso a una celda de 800 estudiantes que a una de 3, y basta con unas pocas celdas diminutas para que el promedio pierda todo significado. El EPAP pondera cada celda por su matrícula, que es lo que importa cuando el resultado se usa para dimensionar recursos.'),
    nota('Sobre la comparación entre revisiones.', 'El EPAP depende del nivel de agregación en que se mide, y cada dimensión añadida parte las celdas: la modalidad en hasta tres y la continuidad en hasta cinco más. Comparar el cruce más fino de esta revisión con el de la anterior no diría nada, porque no son la misma partición. Las comparaciones entre especificaciones de este documento —apartados 1.2, 1.3, 6.5 y 6.6— se hacen todas sobre niveles que existen en ambas.'),

    h2('8.3 Resultados'),
    ...figura('15_validacion.png', 'Tablas de validación dentro del propio modelo: error por nivel de agregación y cobertura empírica del intervalo.', { maxAlto: 470 }),
    tabla([1600, 1650, 1250, 1300, 1500, 1726],
      ['Ajustado hasta', 'Proyectado', 'Horizonte', 'Observado', 'Proyectado', 'Error'],
      [
        ['2025-I', '2025-II', '1', '16 353', '16 628', '+1,68 %'],
        ['2025-I', '2026-I', '2', '21 420', '21 334', '−0,40 %'],
        ['2025-I', '2026-II', '3', '20 526', '21 161', '+3,09 %'],
        ['2025-II', '2026-I', '1', '21 420', '21 201', '−1,02 %'],
        ['2025-II', '2026-II', '2', '20 526', '20 773', '+1,20 %'],
        ['2026-I', '2026-II', '1', '20 526', '20 865', '+1,65 %'],
      ]),
    pieTabla('Detalle del backtesting sobre el total institucional. Las tres comparaciones que apuntan a 2026-II se leen aparte: ese semestre seguía admitiendo altas en la fecha de extracción (apartado 3.4.2), de modo que el observado con el que se comparan está por debajo de su valor final.'),
    p([txt('Sobre los tres objetivos ya cerrados el error va del 0,40 % al 1,68 % y el EPAP medio es del '), neg('1,04 %'), txt('; incluyendo el semestre parcial sube al 1,509 %. Para una institución de veinte mil estudiantes, el primero supone un error medio del orden de doscientos estudiantes sobre el total.')]),
    tabla([3600, 2400, 2226],
      ['Revisión del modelo', 'EPAP medio del total', 'Sesgo medio'],
      [
        ['Ciclo, sede, carrera, turno', '2,06 %', '+293'],
        ['+ modalidad de estudios', '1,45 %', '+148'],
        ['+ continuidad, regla del salto de ciclo', '0,85 %', '−28'],
        ['+ continuidad, clasificación oficial', '1,04 %', '−10'],
      ]),
    pieTabla('Evolución del error del total institucional a lo largo de las revisiones del modelo, con la λ elegida por validación cruzada en cada especificación. Las tres primeras filas se midieron sobre todos los objetivos disponibles en su momento; la última, sobre los objetivos cerrados, que es el criterio que esta revisión adopta. No son por tanto estrictamente comparables entre sí, y la fila que sube respecto de la anterior lo hace en parte por eso y en parte por lo que explica el apartado 6.6: la categoría de recuperados de aquella regla era diez veces mayor y capturaba de paso el efecto de repetir ciclo.'),
    nota('Por qué esta revisión adopta una definición que empeora una cifra de la tabla.', 'Porque la cifra anterior medía otra cosa. El encargo es proyectar la matrícula abierta por la clasificación que la universidad usa en sus informes, y esa clasificación no es la del salto de ciclo: es el campo Condición de su base central. Un modelo que acertara más pero repartiera la matrícula en categorías que la institución no reconoce no serviría para lo que se pide. Dicho eso, la comparación limpia del apartado 6.6 —misma base, mismos objetivos cerrados, con y sin la dimensión— sigue favoreciendo a la especificación completa en los cuatro niveles y, sobre todo, en el sesgo.'),

    h2('8.4 El sesgo y la matrícula abierta de 2026-II: una predicción comprobada'),
    p('El sesgo medio del total sobre los objetivos cerrados es de −10 estudiantes, un −0,05 % de la matrícula: prácticamente nulo. Conviene aun así descomponerlo, porque el sesgo sobre el conjunto de las seis comparaciones es de +199, y la diferencia entre ambas cifras es toda ella el semestre incompleto.'),
    tabla([3400, 2700, 2926],
      ['Conjunto de comparaciones', 'Sesgo medio', 'Sobre la matrícula'],
      [
        ['Las seis comparaciones', '+199 estudiantes', '+1,00 %'],
        ['Sólo las que apuntan a 2026-II', '+407 estudiantes', '+1,98 %'],
        ['Excluyendo 2026-II', '−10 estudiantes', '−0,05 %'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.CENTER] }),
    pieTabla('Descomposición del sesgo del backtesting según el semestre proyectado.'),
    p([txt('Una versión anterior de este documento, escrita sobre una extracción de la misma base cuatro días más temprana, atribuía el sesgo a que la matrícula de 2026-II seguía abierta, y dejaba por escrito cómo comprobarlo: reestimar con un cierre más completo y ver si el sesgo de esas tres comparaciones se reducía. '), neg('La comprobación se hizo y el resultado fue el esperado'), txt(': doscientas altas nuevas —un 1 % de ese semestre— bastaron para reducir a la mitad el sesgo de las comparaciones que lo tienen por objetivo. La conclusión se mantiene con la clasificación oficial, y ahora es aún más nítida, porque el sesgo fuera de ese semestre es de diez estudiantes sobre veinte mil.')]),
    p([txt('El sesgo de +407 que queda en 2026-II es del orden de lo que el apartado 3.4.2 estima que aún falta por registrar. Si esa lectura es correcta, con el cierre definitivo debería acercarse al −10 del resto de la serie. El procedimiento es reproducible: basta borrar '), cur('modelo/hist.pkl'), txt(' y reejecutar la canalización.')]),
    nota('Esto no es un detalle de presentación, es una decisión metodológica.', 'Comparar contra un semestre que aún se está llenando premia sistemáticamente a las especificaciones que proyectan de menos. El efecto es medible: seleccionando λ contra todos los objetivos, la validación cruzada elige λ = 0,90 y el óptimo se desplaza hacia el olvido, porque descontar el pasado baja el nivel proyectado y eso acerca artificialmente la proyección a un observado incompleto. Seleccionando contra los objetivos cerrados elige λ = 1,00, que es el valor de producción. Por eso todas las selecciones y ablaciones de este documento se calculan sobre objetivos cerrados, y la serie completa se informa al lado.'),

    h2('8.5 Qué se puede afirmar y qué no'),
    p('La validación se apoya en tres orígenes y seis comparaciones. Es la información disponible, y conviene ser explícito sobre su alcance.'),
    ...vinetas([
      [neg('Se puede afirmar: '), txt('que el modelo no está sesgado de forma apreciable una vez se descuenta el semestre incompleto —diez estudiantes sobre veinte mil—; que su error a un semestre vista en el total es del orden del 1,5 %; que la aritmética de la incertidumbre está bien planteada, porque el factor de inflación calibrado sigue siendo 1,0; y que las dos dimensiones de composición mejoran la proyección en todos los niveles comparables, cada una por separado.')],
      [neg('No se puede afirmar: '), txt('que el error vaya a mantenerse exactamente en ese nivel, ni que las mejoras de las ablaciones sean exactamente del tamaño medido. Tres comparaciones cerradas no permiten estimar con precisión la distribución del error, y el horizonte 3 sólo existe contra el semestre incompleto. Tampoco puede afirmarse nada sólido sobre el total de recuperados o de reingresos por nueva admisión de un semestre concreto: son las poblaciones más pequeñas del modelo y su intervalo es el único que no alcanza la cobertura nominal.')],
      [neg('Conviene repetir: '), txt('cada semestre nuevo añade un origen de validación. El procedimiento está automatizado y reejecutarlo con datos actualizados no requiere trabajo adicional.')],
    ]),
    salto(),
  ];
}

function manual() {
  return [
    h1('9. Manual de uso'),
    h2('9.1 Puesta en marcha'),
    p([txt('El modelo es un único archivo, '), mono('modelo_proyeccion_matricula.html'), txt('. Se abre con doble clic en cualquier navegador moderno. No necesita instalación, servidor ni conexión a internet: todos los datos y el motor de cálculo viajan dentro del archivo. Puede copiarse, enviarse por correo o guardarse en una carpeta compartida.')]),
    p('Al abrirlo, el modelo ya muestra una proyección calculada con un supuesto de referencia —repetir el último ingreso observado del semestre de la misma paridad, con su composición por modalidad— claramente señalado como marcador de posición. Sirve para explorar la herramienta antes de disponer del archivo de admisión; no es una previsión.'),
    nota('Qué NO hay que declarar.', 'El archivo de entrada contiene únicamente ingresantes de la campaña de admisión. Los continuadores —regulares, recuperados, reinicios— y los ingresantes por nueva admisión los genera el modelo, y su desglose en las tablas sale de la recursión. No hay ningún sitio donde declarar cuántos estudiantes se espera recuperar, y eso es deliberado: el modelo proyecta el comportamiento observado, no los objetivos de una campaña.'),
    ...figura('01_cabecera.png', 'Vista inicial del modelo: cinta de acciones, barra de control y pestaña de resumen.', { maxAlto: 400 }),

    h2('9.2 La plantilla de ingresantes'),
    p([txt('El botón '), neg('«Plantilla»'), txt(' descarga un Excel de tres hojas:')]),
    ...vinetas([
      [neg('Instrucciones. '), txt('Descripción de cada columna, tratamiento de los programas nuevos y nomenclatura de semestres.')],
      [neg('Ingresantes. '), txt('La hoja que hay que editar. Viene precargada con el último ingreso observado de cada paridad, desglosado por modalidad, de modo que se parte de una base realista y sólo hay que ajustar las cifras.')],
      [neg('Catálogos. '), txt('Sedes con sus turnos disponibles, sus modalidades y su ciclo máximo ofertable; y carreras con los ciclos de su plan y las modalidades en que se imparten, para escribir los nombres exactamente como los espera el modelo.')],
    ]),
    tabla([1700, 1200, 6126],
      ['Columna', 'Obligatoria', 'Contenido'],
      [
        ['Periodo', 'Sí', 'Semestre académico: 2027-I, 2027-II. También se admite el formato 202701.'],
        ['Sede', 'Sí', 'Debe coincidir con el catálogo para heredar el patrón de turno de esa sede. Una sede que no figure se entiende que abre en el primer semestre en que aparezca, con despliegue progresivo del plan.'],
        ['Carrera', 'Sí', 'Si no figura en el catálogo, se trata como programa nuevo.'],
        ['Modalidad', 'Recomendada', 'Presencial, Semi Presencial o A distancia. Se reconocen sinónimos habituales (virtual, online, blended, híbrida, semipresencial). Si se deja vacía, el modelo la estima por el apartado 6.9 y lo advierte.'],
        ['Ciclo', 'Recomendada', 'Ciclo al que ingresa: 1 en la admisión ordinaria, mayor que 1 en traslados y convalidaciones. Si se deja vacía, el modelo la estima por el apartado 6.10 y lo advierte.'],
        ['Nuevos', 'Sí', 'Número de ingresantes de esa combinación.'],
        ['CiclosPlan', 'No', 'Ciclos totales del plan. Sólo hace falta para un programa nuevo cuya duración no sea de diez ciclos.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Columnas del archivo de entrada. El lector reconoce además sinónimos habituales de cada encabezado.'),
    nota('El turno no se declara; la modalidad sí conviene declararla.', 'Tal como pide el encargo, el archivo de entrada no lleva columna de turno: el modelo lo estima con el procedimiento del apartado 6.8 y muestra el reparto resultante en la pestaña «Ingresantes», indicando en cada fila el nivel de evidencia empleado. La modalidad es distinta: es un dato que el área de admisión conoce y que el modelo no puede deducir. Si falta, se estima —y el modelo lo advierte fila por fila— pero la proyección pierde precisión.'),
    p([txt('Un archivo preparado con la plantilla anterior, sin columna de modalidad, '), neg('sigue funcionando'), txt(': el modelo lo detecta, avisa de cuántas filas ha tenido que estimar y aplica el reparto del apartado 6.9. No hay que rehacer nada para seguir usándolo.')]),

    h3('9.2.1 Si no se sabe en qué ciclo entrarán'),
    p([txt('La planificación de la admisión suele fijar un objetivo por carrera y modalidad, no por ciclo. Para ese caso la columna '), neg('Ciclo puede omitirse'), txt(': basta declarar el total por semestre, sede, carrera y modalidad, y el modelo lo reparte entre los ciclos donde el histórico registra convalidaciones.')]),
    p([txt('El reparto sale del apartado 6.10 y respeta tres restricciones: el ciclo terminal del plan de la carrera, el tope de maduración de una sede recién abierta y el de un '), neg('programa recién abierto'), txt(', que en su primer semestre sólo imparte el ciclo 1 y despliega uno más en cada semestre siguiente. Usa además el método del resto mayor, de modo que la suma por fila coincide exactamente con el total declarado: no se pierde ni se inventa ningún ingresante.')]),
    nota('Conviene declarar el ciclo cuando se conozca.', 'La estimación describe el comportamiento medio del histórico, no una política de admisión. Si la universidad va a abrir una convocatoria de traslados o a cambiar su política de convalidaciones, esa decisión no está en los datos y el modelo no puede anticiparla: ahí el ciclo hay que declararlo. Lo mismo vale para el sentido contrario, un endurecimiento de los requisitos de convalidación. La estimación es un buen punto de partida, no un sustituto de lo que el área de admisión ya sabe.'),
    p([txt('Quien prefiera trabajar fuera del navegador tiene el mismo reparto como programa aparte: '), cur('modelo/repartir_ingresantes.py'), txt(' toma un Excel sin columna de ciclo y escribe otro con ella, listo para cargar, más una hoja con las tasas aplicadas a cada combinación y el nivel de la cascada del que proceden.')]),

    h2('9.3 Cargar el archivo'),
    p([txt('El botón '), neg('«Cargar ingresantes»'), txt(' abre el selector de archivos y admite .xlsx y .csv. Tras la carga, el modelo:')]),
    ...numerada([
      'Ajusta automáticamente el horizonte al último semestre presente en el archivo.',
      'Identifica las carreras y sedes que no existen en el histórico y las marca como nuevas.',
      'Avisa de cuántas filas declaran modalidad y cuántas ha tenido que estimar.',
      'Avisa si alguna fila declara un ciclo superior al del plan de la carrera o al que la sede puede ofrecer todavía, y lo ajusta al máximo disponible.',
      'Advierte si el archivo contiene semestres anteriores o iguales al último observado, que no se proyectan.',
      'Recalcula y repinta toda la proyección.',
    ]),
    ...figura('09_ingresantes_estado.png', 'Resumen del archivo cargado y avisos de validación, incluida la detección del programa nuevo y el recuento de modalidades declaradas.', { maxAlto: 260 }),

    h2('9.4 Elegir el horizonte'),
    p([txt('El campo '), neg('«Semestres a proyectar»'), txt(' admite de 1 a 24 semestres. Debajo se muestra el intervalo resultante con la nomenclatura de la universidad, de modo que no hay ambigüedad sobre qué se está proyectando: con 6 semestres desde 2026-II, el intervalo es 2027-I → 2029-II.')]),
    p('La nomenclatura sigue el sistema institucional: el año seguido de I para el primer semestre y II para el segundo. El modelo la aplica en pantalla, en la plantilla y en todas las exportaciones.'),
    nota('Sobre horizontes largos.', 'La validación cubre hasta tres semestres. Proyectar doce es técnicamente posible y la recursión sigue siendo válida, pero a partir del cuarto o quinto semestre la práctica totalidad de la matrícula proviene de ingresantes supuestos por el usuario, de modo que el resultado refleja sobre todo ese supuesto —incluida la composición por modalidad que se haya declarado. El intervalo de predicción se ensancha en consecuencia y debe leerse con atención.'),

    h2('9.5 Leer los resultados'),
    h3('9.5.1 Resumen'),
    p('La pestaña de resumen presenta los indicadores principales, la serie histórica empalmada con la proyección y su banda, la composición entre ingresantes y continuadores, el reparto por sede, la composición por modalidad de estudios, la composición por continuidad de la matrícula y la tabla por semestre y escenario.'),
    p([txt('La tabla de resumen es la que responde directamente al encargo: una fila por semestre, con los '), neg('ingresantes'), txt(' y los '), neg('continuadores abiertos en regulares, recuperados, reinicios e ingresantes por nueva admisión'), txt(', seguidos de los tres escenarios y el intervalo de predicción. Las cinco primeras columnas suman siempre el total del escenario moderado, porque la condición es parte del estado y no un reparto posterior.')]),
    ...figura('04c_condicion_serie.png', 'Composición de la matrícula por continuidad, observada y proyectada, en las cinco categorías de la clasificación oficial.', { maxAlto: 300 }),
    ...figura('02_kpis.png', 'Indicadores del resumen. Cada uno lleva su contexto: variación frente al semestre anterior, escenarios alternativos y amplitud del intervalo.', { maxAlto: 260 }),
    ...figura('05_tabla_resumen.png', 'Tabla por semestre y escenario, con la separación entre ingresantes y continuadores y el intervalo de predicción.', { maxAlto: 340 }),

    h3('9.5.2 Detalle'),
    p([txt('La pestaña de detalle permite filtrar por semestre, sede, carrera, modalidad, continuidad y turno, y construir cualquier cruce eligiendo qué dimensión va en filas y cuál en columnas —tanto la modalidad como la continuidad están disponibles en ambos ejes. El selector '), neg('«Escenario en tablas»'), txt(' de la barra superior cambia el escenario mostrado en todas las tablas.')]),
    p('Un cruce útil para la planificación del acompañamiento académico es «Carrera» en filas y «Continuidad» en columnas: muestra dónde se concentran los estudiantes que vuelven de una interrupción, que son los de mayor riesgo de no continuar.'),
    ...figura('07_detalle_cruce.png', 'Cruce de la proyección por carrera y ciclo. Filas y columnas son configurables, y el filtro de modalidad permite aislar cada población.', { maxAlto: 480 }),
    p('Debajo, el detalle por celda lista las combinaciones completas de semestre, sede, carrera, modalidad, continuidad, ciclo y turno, con su margen de precisión. Es la vista que corresponde al nivel más desagregado del encargo.'),
    ...figura('08_detalle_celdas.png', 'Detalle por celda con el margen de precisión de cada una.', { maxAlto: 420 }),

    h3('9.5.3 Modelo y validación'),
    p('La última pestaña no contiene resultados sino el sustento: la ecuación, los parámetros estimados, la caracterización de las tres modalidades y de las cinco condiciones, la maduración de sede, las tasas de continuación, las matrices de avance y turno, la descomposición de varianza y los resultados de validación. Está pensada para que cualquier cifra de las otras pestañas pueda rastrearse hasta su origen.'),

    h2('9.6 Exportar'),
    p([txt('El botón '), neg('«Exportar proyección»'), txt(' genera un Excel de siete hojas:')]),
    tabla([2400, 6626],
      ['Hoja', 'Contenido'],
      [
        ['Resumen', 'Totales por semestre y escenario, con ingresantes, continuadores abiertos en las cuatro condiciones restantes —regular, recuperado, reinicio e ingresante por nueva admisión— y el intervalo de predicción. Incluye la cabecera de supuestos: archivo de entrada, horizonte, confianza y choque aplicado.'],
        ['Proyección detallada', 'Una fila por semestre, sede, carrera, modalidad, continuidad, ciclo y turno, con los tres escenarios, la desviación típica independiente y el intervalo de predicción.'],
        ['Agregados', 'Nueve cuadros listos para usar: por sede, carrera, modalidad, ciclo y turno; por modalidad y ciclo; por continuidad; por continuidad y ciclo; y por sede y continuidad, cada uno con los tres escenarios.'],
        ['Ingresantes', 'Los ingresantes utilizados, su modalidad —declarada o estimada— y su reparto estimado por turno, en cantidad y porcentaje, con el nivel de evidencia empleado en cada fila.'],
        ['Parámetros', 'Tasas de continuación por ciclo y rezago, continuación por modalidad y ciclo, tasas por carrera con su valor crudo y contraído, matriz de avance, matriz de turno, maduración de sede y ciclos de plan por carrera.'],
        ['Validación', 'Descomposición de varianza, backtesting por nivel y horizonte, cobertura empírica, detalle del total institucional y rejilla de selección de λ.'],
        ['Metodología', 'Explicación del modelo en doce apartados, para que el archivo se sostenga por sí solo al circular.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.LEFT] }),
    pieTabla('Contenido del archivo Excel de exportación.'),
    p('La exportación incluye todas las celdas de todos los semestres, no sólo las visibles en pantalla, y los totales de cada escenario coinciden exactamente con la suma de sus celdas. La hoja de proyección detallada supera las diecisiete mil filas con un horizonte de cuatro semestres, de modo que conviene usar los filtros de Excel en lugar de recorrerla a mano; los cuadros ya agregados de la hoja «Agregados» cubren los cortes más habituales.'),

    h2('9.7 Parámetros avanzados'),
    p('El botón «Parámetros avanzados» expone tres controles que normalmente no hace falta tocar, pero que permiten reestimar el modelo dentro del navegador y explorar su sensibilidad:'),
    tabla([2600, 1400, 5026],
      ['Control', 'Valor', 'Efecto'],
      [
        ['λ recencia (continuación)', '1,00', 'Ponderación de los semestres antiguos al estimar la continuación, el avance y el reparto por modalidad. Con 1,00, el valor seleccionado, todo el histórico pesa igual; por debajo de 1 los semestres recientes pesan más.'],
        ['λ recencia (turno)', '0,30', 'Lo mismo para el reparto por turno de los ingresantes.'],
        ['Factor de contracción', '1,00', 'Multiplica las constantes k. Por encima de 1 se contrae más hacia los niveles agregados; por debajo, se cree más a cada celda.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Controles avanzados. Los valores por defecto son los seleccionados por validación cruzada.'),
    p('El modelo no trae los parámetros congelados: al mover cualquiera de estos controles vuelve a agregar los conteos de transición semestre a semestre, recalcula las constantes de contracción por el método de los momentos y reproyecta. Incluso el reparto por modalidad de las filas que no la declaran se recalcula, de modo que nada queda fijado fuera del estimador. Es la misma aritmética de la implementación de referencia en Python, verificada punto por punto.'),
    p([txt('El valor por defecto de cada control lo fija la propia estimación, no el archivo HTML: al regenerar el modelo con una base actualizada, la λ que elija la validación cruzada aparece automáticamente en el control. Conviene revisarla al reestimar, porque su '), cur('posición'), txt(' es informativa: si se desplaza hacia el borde inferior de la rejilla, es señal de que ha aparecido una deriva que el modelo no puede ver (apartado 6.7).')]),
    ...figura('17_oscuro.png', 'El modelo también funciona en modo oscuro, conmutable desde la cinta superior.', { maxAlto: 400 }),
    salto(),
  ];
}

function programasNuevos() {
  return [
    h1('10. Programas y sedes nuevas'),
    h2('10.1 El problema'),
    p('Un programa que se abre no tiene historia: no hay cohortes suyas de las que estimar retención, ritmo de avance ni preferencia de turno. Y sin embargo debe poder proyectarse, porque la apertura de programas es justamente uno de los escenarios de planificación más relevantes.'),
    p('Lo mismo vale para una carrera existente que se abre en una modalidad nueva —un programa presencial que empieza a ofrecerse a distancia—, que es un caso cada vez más frecuente a la vista de la deriva documentada en el apartado 3.2.'),

    h2('10.2 La solución: contracción, no reglas especiales'),
    p('El modelo no incorpora ningún tratamiento excepcional. La escalera de contracción resuelve el caso por construcción: al no encontrar evidencia en los niveles finos, la estimación se detiene en el nivel más específico que sí la tenga.'),
    tabla([2600, 3200, 3226],
      ['Parámetro', 'Nivel que se aplica', 'Fundamento'],
      [
        ['Continuación', 'Continuidad × modalidad × ciclo × paridad', 'La estructura por ciclo, continuidad y modalidad es la que más señal contiene y es común a todas las carreras.'],
        ['Avance de ciclo', 'Continuidad × modalidad × ciclo', 'El patrón de aprobación y repetición depende sobre todo del ciclo, de si se vuelve de una pausa y de la modalidad.'],
        ['Transición de turno', 'Sede × modalidad × continuidad × ciclo', 'Depende del catálogo de turnos de la sede y del régimen de la modalidad, que sí se conocen.'],
        ['Reparto de turno de ingresantes', 'Sede × modalidad (o × paridad)', 'La preferencia de turno responde sobre todo a la modalidad y al perfil del alumnado de la sede.'],
        ['Reparto de modalidad, si no se declara', 'Sede × paridad', 'Composición institucional de la sede, restringida a su oferta.'],
        ['Ciclos del plan', 'Declarado o 10 por defecto', 'El usuario puede fijarlo en la columna CiclosPlan de la plantilla.'],
        ['Ciclo máximo ofertable', 'Tope de maduración de la sede', 'Si la sede también es nueva, el programa sólo crece al ritmo al que crece la sede.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.LEFT, AlignmentType.LEFT] }),
    pieTabla('Niveles de la escalera de contracción que se aplican a un programa sin historia.'),
    p([txt('Obsérvese que un programa nuevo hereda el comportamiento de '), neg('su modalidad y de la condición de cada cohorte'), txt(', no el promedio institucional. Una carrera nueva a distancia arranca con una continuación de primer ciclo del orden del 42 %, no del 60 % que promedian las tres modalidades. Y a partir del tercer semestre, cuando empiece a tener reinicios propios, el modelo les aplicará la tasa de un reinicio sin que haya que configurar nada.')]),
    p('A medida que el programa acumule semestres, sus propias celdas ganarán observaciones y el estimador les dará peso de forma progresiva y automática, sin intervención ni recalibrado.'),

    h2('10.3 Ejemplo verificado'),
    p('Para comprobar el comportamiento se preparó un archivo de entrada con un programa inexistente en el histórico, INTELIGENCIA ARTIFICIAL, con plan declarado de ocho ciclos y ingresantes en las tres modalidades, en Lima Sur y Lima Norte.'),
    ...vinetas([
      'El modelo lo detectó como programa nuevo y lo señaló en la pestaña de ingresantes.',
      'Aplicó el plan de ocho ciclos declarado, limitando correctamente el avance.',
      'Aplicó a cada fila la continuación y el avance de su modalidad declarada, no el promedio institucional.',
      'En su primer semestre todos sus estudiantes son ingresantes; en el segundo aparecen sus primeros regulares y recuperados, y en el tercero sus primeros reinicios, sin ninguna configuración.',
      'Resolvió el reparto de turno en el nivel «sede·modalidad·paridad», informándolo en la columna correspondiente.',
      'Proyectó su matrícula a lo largo del horizonte con la estructura de continuación por ciclo y modalidad.',
    ]),
    p('El resultado del reparto por turno ilustra bien lo que aporta condicionar en la modalidad. Las tres filas del programa comparten sede, carrera, ciclo y semestre; se diferencian sólo en la modalidad, y el modelo les asigna turnos radicalmente distintos:'),
    tabla([2500, 1450, 1450, 1450, 2176],
      ['Modalidad declarada', '→ Mañana', '→ Noche', '→ Tarde', 'Nivel de evidencia'],
      [
        ['Presencial', '76,2 %', '20,8 %', '3,0 %', 'sede·modalidad·paridad'],
        ['Semi Presencial', '0,0 %', '97,8 %', '2,2 %', 'sede·modalidad·paridad'],
        ['A distancia', '0,0 %', '98,8 %', '1,2 %', 'sede·modalidad·paridad'],
      ]),
    pieTabla('Reparto por turno estimado para el programa nuevo en Lima Sur, primer ciclo, semestre impar. Sin la dimensión de modalidad las tres filas habrían recibido el mismo reparto.'),
    ...figura('18_escenario_pesimista.png', 'Cruce por carrera y ciclo en escenario pesimista; el programa nuevo aparece con normalidad junto al resto de la oferta.', { maxAlto: 480 }),

    h2('10.4 Sedes nuevas'),
    p('El mismo archivo de entrada admite sedes que no existen en el histórico. La sede se da por abierta en el primer semestre en que aparece y a partir de ahí despliega su plan ciclo a ciclo, según el apartado 5.8.'),
    p('En la prueba se declaró una sede inexistente, Lima Este, con 160 ingresantes de primer ciclo en 2028-I y, en 2028-II, otros 50 de primer ciclo más una fila de 30 traslados declarados al ciclo 4. El modelo:'),
    ...vinetas([
      'La reconoció como sede nueva y fijó su apertura en 2028-I, con ciclo base 1.',
      'No le asignó ninguna matrícula en 2027-I ni 2027-II, semestres anteriores a su apertura.',
      [txt('Avisó fila por fila: '), cur('«Fila 581: Lima Este no imparte todavía el ciclo 4 en 2028-II (inició en 2028-I, llega hasta el ciclo 2); esos 30 ingresantes se asignan al ciclo 2»'), txt('.')],
      'Proyectó 160 estudiantes en el ciclo 1 en 2028-I —todos ingresantes— y, en 2028-II, 55 en el ciclo 1 y 136 en el ciclo 2, repartidos en 80 ingresantes y 111 regulares: ningún estudiante en un ciclo que la sede no imparte todavía, y ningún reiniciado, porque la sede aún no tiene historia suficiente para producirlos.',
      'Tomó el reparto por turno de la distribución institucional de cada modalidad, al no haber ninguna evidencia propia de esa sede.',
    ]),
    nota('Sobre el turno de una sede nueva.', 'Es la estimación más frágil de todo el modelo. El turno depende del perfil del alumnado de cada sede —Lima Norte y Lima Sur ni siquiera comparten catálogo de turnos— y una sede nueva no aporta ninguna información al respecto. Incorporar la modalidad mitiga el problema, porque una carrera a distancia es nocturna con independencia de la sede, pero no lo resuelve para la parte presencial. Conviene revisar ese reparto en cuanto exista un semestre de matrícula real.'),
    h2('10.5 Un programa nuevo también madura'),
    p([txt('La maduración no es privativa de las sedes. Un programa que arranca tampoco tiene ciclos superiores que ofrecer, y eso importa en cuanto el archivo de entrada deja el ciclo sin declarar: sin la restricción, el reparto estimado del apartado 6.10 le aplicaría la tasa de convalidación de su modalidad —en torno a un 4 %— y colocaría ingresantes en '), neg('ciclos que el programa no imparte'), txt('.')]),
    p('El modelo lo trata igual que a una sede nueva: el programa se da por abierto en el primer semestre en que aparece, con ciclo base el mayor que se declare en ese semestre —1 si no se declara ninguno, que es el caso normal— y despliega un ciclo más en cada semestre siguiente.'),
    tabla([2000, 2100, 2100, 2126],
      ['Semestre', 'Ciclos que imparte', 'Ingresantes declarados', 'Reparto estimado'],
      [
        ['2027-I (apertura)', 'sólo el 1', '200', '200 en el ciclo 1'],
        ['2027-II', '1 y 2', '120', '114 · 6'],
        ['2028-I', '1 a 3', '200', '194 · 4 · 2'],
        ['2028-II', '1 a 4', '120', '114 · 3 · 1 · 2'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.CENTER, AlignmentType.CENTER] }),
    pieTabla('Reparto por ciclo de un programa sin historia que no declara el ciclo, tal como lo resuelve el modelo. Cifras de la prueba automática `fuente/probar_sin_ciclo.js`, que las comprueba en cada reconstrucción.'),
    p([txt('En el semestre de apertura el reparto es '), neg('exacto, no estimado'), txt(': no hay nada que estimar, porque sólo existe un ciclo posible. A partir de ahí la estimación entra en juego sobre los ciclos que ya se imparten, y converge al comportamiento propio del programa en cuanto éste acumula historia.')]),

    nota('Lectura de cautela.', 'Que el modelo proyecte un programa nuevo no significa que acierte. Está aplicando el comportamiento medio de su modalidad a una población de la que no sabe nada, y un programa nuevo puede atraer un perfil de estudiante con retención distinta. La cifra es una hipótesis razonada de partida, no una previsión con la misma solidez que la de un programa consolidado. Conviene revisarla en cuanto existan dos o tres semestres de historia propia.'),
    salto(),
  ];
}

function limitaciones() {
  return [
    h1('11. Limitaciones y mantenimiento'),
    h2('11.1 Limitaciones'),
    ...numerada([
      [neg('La proyección es condicional al archivo de ingresantes. '), txt('El modelo no pronostica la admisión ni su reparto por modalidad. Si el supuesto de ingreso es erróneo, la proyección lo será en la misma medida, y el modelo no tiene forma de advertirlo.')],
      [neg('Supone continuidad del comportamiento. '), txt('Un cambio de plan de estudios, de política de permanencia, de estructura de becas o de oferta de turnos y modalidades rompe el supuesto. La estimación lo recogerá con uno o dos semestres de retraso, no de inmediato.')],
      [neg('La validación se apoya en seis comparaciones, y sólo tres contra semestres cerrados. '), txt('Es la información disponible con ocho semestres de historia. Las cifras del horizonte 3 descansan sobre una única observación, y además contra el semestre incompleto, de modo que deben leerse como indicativas. Lo mismo vale para la magnitud exacta de las mejoras atribuidas a la modalidad y a la continuidad en los apartados 6.5 y 6.6.')],
      [neg('El nivel más desagregado es impreciso. '), txt('Un EPAP del 39 % en el cruce completo refleja que muchas celdas tienen menos de cinco estudiantes. A ese nivel, el intervalo de predicción es tan informativo como el punto.')],
      [neg('El desglose por condición es la parte menos fiable del modelo. '), txt('Su intervalo de predicción cubre el 53 % de los casos frente a un 80 % nominal, y no alcanza el nominal ni triplicando κ. El volumen de reingresos de un semestre depende de decisiones institucionales —campañas de recuperación, amnistías de deuda, flexibilización de requisitos— que no están en los datos, y el de recuperados depende de la exigencia académica de cada semestre. Conviene leer el reparto entre las cinco condiciones como un orden de magnitud —el total al que suman es mucho más fiable— y revisarlo si hay una campaña en marcha.')],
      [neg('El recuperado se estima sobre una población muy pequeña. '), txt('Son 495 casos en seis semestres, un 0,83 % del flujo de rezago 1. El parámetro r del apartado 6.12 sólo tiene evidencia propia apreciable en los niveles de ciclo y de condición de origen; las celdas de carrera heredan prácticamente todo de sus padres. El desglose de recuperados de una celda fina no debe leerse como una predicción con contenido propio, sino como un reparto proporcional dentro de su condición y ciclo.')],
      [neg('El flujo de ingresantes por nueva admisión se proyecta como un nivel constante. '), txt('Unos 68 estudiantes en los primeros semestres del año y 45 en los segundos, porque es la magnitud más estable de las tres candidatas (apartado 6.13). No crece con la institución: si la matrícula se duplicara, su peso relativo caería a la mitad. Con el horizonte habitual el efecto es de décimas de punto, pero conviene revisar el supuesto en cada reestimación.')],
      [neg('La clasificación oficial se reconstruye, no se lee. '), txt('El histórico de matriculados no trae el campo Condición, de modo que el modelo reconstruye la regla desde la base central y la aplica. La reconstrucción coincide con la clasificación oficial en el 99,63 % de las 97 162 matrículas contrastadas; las 364 discrepancias se concentran en reingresos antiguos cuya matrícula previa queda fuera de la ventana cargada. Es un margen pequeño, pero no es cero, y depende de que ambas bases sigan generándose igual.')],
      [neg('La memoria de la condición es de un semestre. '), txt('Quien vuelve de una interrupción llega como reinicio en el semestre del regreso y pasa a regular o a recuperado en el siguiente, aunque empíricamente siga por debajo de un regular durante dos o tres semestres más (apartado 4.3.2). El sesgo que eso introduce en la tasa de los regulares es de 0,27 puntos, medido sobre 1 300 orígenes de 56 040.')],
      [neg('La modalidad a distancia tiene historia corta en los ciclos altos. '), txt('Su matrícula no pasa todavía del ciclo 7, de modo que su continuación en los ciclos 8 a 11 y su ciclo terminal se estiman por contracción hacia el perfil general, no con evidencia propia. Es la parte del modelo que más se beneficiará de cada semestre nuevo.')],
      [neg('La ventana de la base central es de seis semestres, no de ocho. '), txt('En 2023-I el clasificador oficial no ve la matrícula anterior y marca a los 7 855 continuadores como reinicio; en 2026-II la extracción es anterior a la campaña y sólo trae 708 filas. Ambos se excluyen (apartado 3.3), de modo que todo lo relativo a la condición se estima sobre 97 162 matrículas de seis semestres, mientras que la sede, la carrera, la modalidad, el ciclo y el turno se estiman sobre los ocho del histórico. Es otra de las razones por las que λ se sitúa en 1: descartar semestres antiguos dejaría sin datos a las categorías pequeñas.')],
      [neg('El semestre 2026-II sigue admitiendo altas. '), txt('Está al 99 % de su campaña y faltan del orden de doscientas matrículas (apartado 3.4.2). Afecta al punto de partida de la recursión y deja un sesgo de +407 estudiantes en las tres comparaciones que apuntan a ese semestre, frente a −10 en el resto. Por eso todas las selecciones y comparaciones de especificación de este documento se calculan sobre objetivos cerrados (apartado 8.4). Conviene reestimar con el cierre definitivo.')],
      [neg('Los programas nuevos heredan comportamiento ajeno. '), txt('Es la mejor estimación disponible sin historia propia, pero no equivale a una proyección basada en evidencia del propio programa.')],
      [neg('El tope de maduración es una restricción, no una predicción. '), txt('Establece qué ciclos puede ofrecer una sede recién abierta, pero supone que el despliegue avanza un ciclo por semestre sin interrupción. Si la sede abriera dos ciclos a la vez, o retrasara la apertura de uno, habría que reflejarlo en los datos y reestimar.')],
    ]),

    h2('11.2 Cuándo reestimar'),
    p('El modelo lleva incorporados los conteos de transición semestre a semestre, de modo que puede reestimarse dentro del navegador moviendo los parámetros de recencia y contracción. Lo que no puede hacer por sí solo es incorporar semestres nuevos: para eso hay que regenerar el archivo con la base actualizada.'),
    ...vinetas([
      [neg('Cada semestre, '), txt('al cerrar la matrícula: añadir el semestre a la base y regenerar. Se gana un origen de validación y se actualiza el punto de partida.')],
      [neg('Ante un cambio estructural '), txt('—nuevo plan de estudios, nueva sede, nueva modalidad en una carrera, cambio en la política de turnos—: reestimar y comprobar si las constantes de contracción y la λ seleccionada se desplazan.')],
      [neg('Si el error fuera de muestra se degrada '), txt('de forma sostenida por encima del 3 % en el total: es señal de que algo cambió en el comportamiento y conviene revisar la especificación, no sólo reestimar.')],
      [neg('Si la λ seleccionada se va al borde INFERIOR de la rejilla, '), txt('como ocurría sin las dimensiones de modalidad y continuidad: es el síntoma de una variable relevante omitida, y conviene buscarla antes de aceptar la proyección. Un valor alto, en cambio, es buena señal.')],
    ]),

    h2('11.3 Reproducibilidad'),
    p('Todo el procedimiento es determinista. Con la misma base histórica y el mismo archivo de ingresantes, el modelo devuelve exactamente las mismas cifras: no hay simulación, muestreo aleatorio ni semillas.'),
    p([txt('La implementación de referencia se escribió en Python (pandas, numpy, scipy y statsmodels) y el motor de producción en JavaScript dentro del HTML. Ambos se verificaron sobre el mismo conjunto de parámetros y el mismo caso de prueba: sobre seis semestres proyectados, los totales, las desviaciones típicas y los desgloses por modalidad y por continuidad coinciden con una diferencia relativa máxima del orden de 10⁻¹⁶ —el epsilon de la doble precisión— y las constantes de contracción, del orden de 10⁻¹⁵. Lo que queda es el orden de acumulación en coma flotante, no diferencia de lógica.')]),
    nota('Por qué dos implementaciones.', 'La versión en Python permite usar bibliotecas econométricas contrastadas para el GLM y los contrastes estadísticos, y sirve de referencia frente a la cual verificar el motor del navegador. La versión en JavaScript es la que el usuario ejecuta, sin instalar nada. La verificación cruzada entre ambas es la garantía de que lo que se documenta aquí es lo que el modelo calcula.'),
    salto(),
  ];
}

function anexos() {
  return [
    h1('Anexo A. Parámetros estimados'),
    h2('A.1 Continuación por ciclo y rezago'),
    tabla([1150, 1700, 1550, 1550, 1550, 1526],
      ['Ciclo', 'Observaciones', 'L = 1', 'L = 2', 'L = 3', 'L = 4'],
      [
        ['1', '16 749', '60,4 %', '1,9 %', '0,7 %', '0,4 %'],
        ['2', '12 747', '83,0 %', '2,8 %', '1,1 %', '0,4 %'],
        ['3', '9 097', '86,4 %', '3,4 %', '1,2 %', '0,3 %'],
        ['4', '8 538', '89,1 %', '3,2 %', '1,0 %', '0,4 %'],
        ['5', '6 206', '90,5 %', '3,4 %', '1,3 %', '0,6 %'],
        ['6', '5 587', '92,6 %', '3,2 %', '1,1 %', '0,1 %'],
        ['7', '4 354', '91,3 %', '3,2 %', '1,4 %', '0,3 %'],
        ['8', '4 280', '92,2 %', '2,8 %', '1,2 %', '0,3 %'],
        ['9', '3 305', '93,5 %', '2,6 %', '0,6 %', '0,5 %'],
        ['10', '3 481', '48,6 %', '2,0 %', '0,9 %', '0,1 %'],
        ['11', '1 431', '19,4 %', '1,9 %', '0,3 %', '0,5 %'],
      ]),
    pieTabla('Probabilidad de que la siguiente matrícula ocurra L semestres después, por ciclo de origen, sobre el panel de la base central con la ponderación de recencia λ = 1,00 activa. Las observaciones son el recuento sin ponderar del rezago 1. Cada columna se estima sobre su propio conjunto de riesgo —un origen sólo cuenta para el rezago L si el semestre L está dentro de la ventana observada— de modo que las cuatro no suman una partición. La caída de los ciclos 10 y 11 corresponde al egreso. Nótese que el reingreso tras pausa (L ≥ 2) es menos frecuente en el ciclo 1: quien abandona en el primer ciclo rara vez vuelve.'),
    p([txt('Las columnas L ≥ 2 de esta tabla son, por construcción, las que alimentan la condición de '), neg('reinicio'), txt(' del semestre de destino: son los regresos tras una o más pausas. La columna L = 1 se reparte a su vez entre '), neg('regular'), txt(' y '), neg('recuperado'), txt(' con la probabilidad r del apartado 6.12, que es lo único de la clasificación que hay que estimar.')]),

    h2('A.2 Continuación por modalidad y ciclo'),
    p('Tasas de continuación a un semestre (L = 1), agrupadas sobre las condiciones de llegada y las dos paridades, con la ponderación de recencia activa. Son las mismas que el modelo muestra en pantalla.'),
    tabla([1500, 2500, 2500, 2526],
      ['Ciclo', 'Presencial', 'Semi Presencial', 'A distancia'],
      [
        ['1', '71,3 %', '56,2 %', '42,2 %'],
        ['2', '83,3 %', '83,0 %', '78,2 %'],
        ['3', '87,8 %', '86,3 %', '84,7 %'],
        ['4', '88,7 %', '87,8 %', '88,2 %'],
        ['5', '90,4 %', '90,5 %', '91,7 %'],
        ['6', '91,2 %', '92,2 %', '92,5 %'],
        ['7', '90,8 %', '94,1 %', '92,8 %'],
        ['8', '91,1 %', '93,8 %', '—'],
        ['9', '93,1 %', '97,9 %', '—'],
        ['10', '49,3 %', '47,6 %', '—'],
        ['11', '19,3 %', '0,0 %', '—'],
      ]),
    pieTabla('Continuación a un semestre por modalidad y ciclo. La brecha se concentra en los dos primeros ciclos y se cierra a partir del cuarto. Los guiones señalan ciclos sin evidencia propia de esa modalidad: la matrícula a distancia no pasa todavía del ciclo 7. El 0,0 % de la semipresencial en el ciclo 11 no es un hueco sino un dato: los 34 estudiantes de esa casilla egresaron todos. En la proyección esas celdas se resuelven por contracción hacia el perfil del ciclo.'),
    p([txt('Las tres columnas convergen a partir del ciclo 4 y la caída terminal de los ciclos 10 y 11 es común: el egreso no depende de la modalidad. La diferencia de comportamiento está en la '), neg('entrada'), txt(', no en la permanencia ni en la salida.')]),

    h2('A.3 Continuación por continuidad de la matrícula y ciclo'),
    p('Tasas de continuación a un semestre (L = 1) por condición oficial de llegada, sobre el panel de la base central, agrupadas sobre las dos paridades y con la ponderación de recencia activa. Entre paréntesis, las observaciones de cada celda: son la clave para saber de cuáles fiarse. Las casillas con menos de veinte observaciones se muestran con guion.'),
    tabla([780, 1680, 1680, 1470, 1470, 1470],
      ['Ciclo', 'Regular', 'Ingresante', 'Recuperado', 'Reinicio', 'Ingr. n. adm.'],
      [
        ['1', '65,8 %  (430)', '60,3 %  (15 636)', '54,2 %  (177)', '60,3 %  (431)', '80,0 %  (75)'],
        ['2', '84,3 %  (11 826)', '73,2 %  (381)', '62,0 %  (79)', '60,3 %  (426)', '71,4 %  (35)'],
        ['3', '88,5 %  (8 454)', '65,5 %  (165)', '69,8 %  (53)', '53,5 %  (396)', '69,0 %  (29)'],
        ['4', '90,5 %  (8 066)', '68,1 %  (94)', '75,0 %  (44)', '61,2 %  (294)', '77,5 %  (40)'],
        ['5', '91,9 %  (5 870)', '84,0 %  (25)', '75,0 %  (28)', '61,7 %  (253)', '73,3 %  (30)'],
        ['6', '93,7 %  (5 336)', '—  (12)', '69,0 %  (29)', '70,7 %  (198)', '—  (12)'],
        ['7', '92,5 %  (4 082)', '—  (10)', '72,7 %  (22)', '72,4 %  (228)', '—  (12)'],
        ['8', '93,6 %  (4 067)', '—  (3)', '66,7 %  (24)', '66,9 %  (172)', '—  (14)'],
        ['9', '94,1 %  (3 172)', '—  (2)', '—  (19)', '78,9 %  (109)', '—  (3)'],
        ['10', '48,6 %  (3 367)', '—  (0)', '—  (7)', '46,5 %  (101)', '—  (6)'],
        ['11', '19,3 %  (1 370)', '—  (0)', '—  (7)', '18,0 %  (50)', '—  (4)'],
      ], { tam: 16 }),
    pieTabla('Continuación a un semestre por condición oficial de llegada y ciclo. Obsérvese el tamaño de las columnas: el regular tiene miles de observaciones por ciclo y el recuperado, decenas. Esa asimetría es la que obliga a la contracción del apartado 6.12.'),
    p([txt('Tres lecturas conviene destacar. La primera es que el '), neg('reinicio del ciclo 3 (53,5 %) está treinta y cinco puntos por debajo del regular del mismo ciclo (88,5 %)'), txt(': es la mayor diferencia que produce cualquier dimensión del modelo. La segunda es que el recuperado y el reiniciado se parecen mucho más entre sí de lo que sugería la versión anterior de este documento, que los medía con otra definición: en los ciclos 2 a 5 el recuperado está incluso por encima del reiniciado, y en los ciclos 6 a 8 por debajo. Con decenas de observaciones por casilla, esas diferencias no son distinguibles del ruido, y el modelo las trata como tales al contraer ambas hacia el perfil del ciclo. La tercera es que en los ciclos terminales todas las condiciones convergen: el egreso no distingue.')]),
    nota('Cuidado con las celdas pequeñas.', 'El regular del ciclo 1 tiene sólo 430 observaciones porque casi todo el ciclo 1 son ingresantes; el recuperado no pasa de 177 en ningún ciclo y el ingresante por nueva admisión, de 75. La contracción hacia el perfil del ciclo modera los valores más ruidosos en la proyección —es justamente para lo que sirve— pero la tabla se presenta en crudo para que el lector vea sobre qué evidencia descansa cada casilla. Ninguna cifra de esta tabla con menos de un centenar de observaciones debería leerse como una tasa con contenido propio.'),

    h2('A.4 Ciclos del plan por carrera'),
    p('El ciclo terminal se infiere del comportamiento de continuación observado. Las carreras cuyo historial no alcanza aún los ciclos superiores conservan el valor por defecto de diez ciclos.'),
    tabla([4500, 1400, 3126],
      ['Carrera', 'Ciclos', 'Origen del valor'],
      [
        ['DERECHO', '11', 'Inferido: continuación alta en el ciclo 10 (87,8 %).'],
        ['PSICOLOGÍA', '11', 'Inferido: continuación alta en el ciclo 10 (93,6 %).'],
        ['Las 23 carreras restantes', '10', 'Inferido o valor por defecto en las carreras censuradas.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Duración del plan de estudios por carrera.'),

    h2('A.5 Oferta por modalidad'),
    p('De las 150 combinaciones teóricas de sede, carrera y modalidad sólo existen 83. El modelo respeta esa restricción tanto al proyectar continuadores como al repartir ingresantes sin modalidad declarada.'),
    tabla([3400, 1800, 3826],
      ['Restricción de oferta', 'Alcance', 'Consecuencia en la proyección'],
      [
        ['Carreras sólo presenciales', '7 de 25', 'Enfermería, Obstetricia, Farmacia y Bioquímica, Ingeniería Biomédica, Ciencias de la Comunicación y las dos de Tecnología Médica.'],
        ['Carreras en dos modalidades', '6 de 25', 'Reparto entre las dos disponibles.'],
        ['Carreras en las tres modalidades', '12 de 25', 'Reparto completo.'],
        ['Lima Norte', 'sin «A distancia»', 'La sede imparte 17 carreras, en modalidad presencial y semipresencial.'],
        ['Lima Sur', 'las tres modalidades', 'Las 25 carreras.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Estructura de la oferta por modalidad, tal como la detecta el modelo del histórico.'),

    h2('A.6 Continuación global por rezago'),
    tabla([2600, 1600, 4826],
      ['Rezago', 'Probabilidad', 'Interpretación'],
      [
        ['L = 1', '79,10 %', 'Se rematricula en el semestre inmediato siguiente. → Regular con probabilidad 1 − r, Recuperado con probabilidad r.'],
        ['L = 2', '2,75 %', 'Regresa tras interrumpir un semestre. → Reinicio.'],
        ['L = 3', '0,99 %', 'Regresa tras interrumpir dos semestres. → Reinicio.'],
        ['L = 4', '0,36 %', 'Regresa tras interrumpir tres semestres. → Reinicio.'],
        ['No vuelve', '16,80 %', 'Deserción o egreso, según el ciclo.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Continuación global por rezago, sobre el panel de la base central y con la ponderación de recencia activa. Cada q_L se estima sobre su propio conjunto de riesgo, de modo que la fila de cierre es el complemento de la suma y no un residuo estimado aparte. La última columna indica la condición que el rezago asigna al estudiante en el semestre de destino (apartado 5.5); r es la probabilidad del apartado 6.12, del 0,83 % en el agregado.'),
    salto(),

    h1('Anexo B. Glosario'),
    tabla([2600, 6426],
      ['Término', 'Definición'],
      [
        ['Ablación', 'Contraste que ejecuta el procedimiento completo con y sin un componente para medir su aportación. Aquí se aplica a la dimensión de modalidad (apartado 6.5) y a la de continuidad (apartado 6.6).'],
        ['Backtesting de origen móvil', 'Validación que reestima el modelo con datos hasta un corte y proyecta el resto, desplazando el corte. Evita usar información del futuro en la evaluación.'],
        ['Cadena de Markov de cohortes', 'Modelo en el que una población se reparte entre estados y avanza según probabilidades de transición estimadas.'],
        ['Choque de periodo', 'Desviación de la tasa de continuación de un semestre respecto de su nivel esperado, común a todas las cohortes de ese semestre.'],
        ['Contracción (shrinkage)', 'Combinar la estimación de una celda con la de un nivel más agregado, en proporción a la información disponible en cada uno.'],
        ['Descomposición de Oaxaca-Blinder', 'Reparto del cambio de una media entre la parte debida al cambio de composición de los grupos y la debida al cambio dentro de cada grupo (apartado 4.6.1).'],
        ['EPAP (WAPE)', 'Error porcentual absoluto ponderado: suma de errores absolutos dividida por la suma de observados. Pondera cada celda por su tamaño.'],
        ['Empírico-Bayes', 'Enfoque en que los parámetros de la distribución a priori se estiman de los propios datos en lugar de fijarse de antemano.'],
        ['Escala logit', 'Transformación log(p/(1−p)) que lleva una probabilidad a toda la recta real. Un desplazamiento en logit nunca produce probabilidades fuera de [0, 1].'],
        ['GLM binomial', 'Modelo lineal generalizado para variable dependiente binaria; con enlace logit equivale a la regresión logística.'],
        ['Intervalo de predicción', 'Rango en el que se espera que caiga el valor observado. Incluye la incertidumbre sistémica y el azar de realización.'],
        ['Método de los momentos', 'Estimación que iguala momentos teóricos y muestrales. Aquí se usa para obtener la constante de contracción.'],
        ['Continuidad de la matrícula', 'Dimensión del estado que recoge la clasificación oficial de la universidad, tomada del campo Condición de su base central: regular (cerró el semestre anterior en situación activa), recuperado (no lo cerró —abandono, retiro o inhabilitación— y aun así se matricula al siguiente), reinicio (interrumpió uno o más semestres), ingresante e ingresante por nueva admisión. El rezago del flujo determina las categorías de interrupción; el reparto entre regular y recuperado se estima (apartado 6.12).'],
        ['Condición (campo de la base central)', 'Estado académico con que un estudiante cierra un semestre: ACTIVO, TERMINÓ MALLA CURRICULAR, EGRESADO, ABANDONO DE CICLO, RETIRADO o INHABILITADO. Los tres primeros cuentan como cierre sin ruptura; los tres últimos convierten en recuperado a quien se rematricula al semestre siguiente.'],
        ['r', 'Probabilidad de que un flujo de rezago 1 llegue como recuperado. Único parámetro que la clasificación oficial obliga a estimar; se estima por contracción Beta-Binomial sobre la base central (apartado 6.12).'],
        ['Criterio minimax', 'Regla de elección que minimiza la peor pérdida entre varios criterios en competencia. Aquí se usa para seleccionar λ acotando el sobrecoste del nivel de agregación peor servido.'],
        ['Modalidad de estudios', 'Régimen en que se cursa el programa: presencial, semipresencial o a distancia. En este modelo es un atributo conservado del estado que condiciona la continuación, el avance y el turno.'],
        ['Paridad del semestre', 'Si un semestre es el primero (I) o el segundo (II) del año. La continuación y la mezcla de turno difieren sistemáticamente entre ambos.'],
        ['Restricción de oferta', 'Conjunto de combinaciones de sede, carrera y modalidad que la universidad imparte realmente. El modelo no genera matrícula fuera de ellas.'],
        ['Razón de momios', 'Cociente entre los momios de dos grupos, siendo los momios p/(1−p). Una razón de 0,219 significa que los momios del primer grupo son algo menos de la quinta parte de los del segundo. Es la medida natural del efecto en un modelo logit.'],
        ['Rezago', 'Número de semestres entre una matrícula y la siguiente del mismo estudiante. Un rezago mayor que 1 es un reingreso tras pausa, y determina por sí solo la condición de reinicio; el rezago 1 se reparte entre regular y recuperado con la probabilidad r.'],
        ['Semivida', 'Antigüedad a la que el peso de recencia se reduce a la mitad: log(0,5)/log(λ).'],
        ['Tamaño muestral efectivo', 'Observaciones equivalentes de una estimación tras la ponderación de recencia y la contracción. Gobierna el error de parámetro.'],
        ['Variable omitida', 'Regresor relevante ausente de la especificación, cuyo efecto se reparte entre los regresores incluidos y sesga sus coeficientes.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.LEFT] }),
    pieTabla('Glosario de términos empleados en este documento.'),
  ];
}

module.exports = { validacion, manual, programasNuevos, limitaciones, anexos };
