/* Capítulos 8 a 11 y anexos. */
const U = require('./doc_parte1.js');
const {
  Paragraph, TextRun, AlignmentType, BorderStyle,
  AZUL, AMBAR, GRIS, FONDO, ANCHO_TABLA,
  p, neg, txt, cur, mono, h1, h2, h3, formula, nota, vinetas, numerada,
  tabla, figura, pieTabla, salto,
} = U;

function validacion() {
  return [
    h1('8. Validación estadística'),
    h2('8.1 El procedimiento'),
    p('La validación se hizo por backtesting de origen móvil, que es el procedimiento estándar para modelos de proyección temporal y el único que evita contaminar la evaluación con información del futuro.'),
    ...numerada([
      'Se fija un semestre de corte y se descarta todo lo posterior.',
      'Se reestima el modelo completo —tablas de transición, constantes de contracción y ponderación de recencia— usando exclusivamente los datos hasta ese corte.',
      'Se proyectan los semestres siguientes, alimentando el modelo con los ingresantes realmente observados —con su modalidad real— para aislar el error del modelo del error del supuesto de admisión.',
      'La condición de llegada se recalcula dentro de la ventana truncada: en cada corte el modelo sólo puede saber lo que se observa hasta ese semestre, de modo que un estudiante cuya interrupción ocurriera después del corte no cuenta como reiniciado.',
      'Se compara con la matrícula efectivamente registrada, en los diez niveles de agregación.',
      'Se repite desplazando el corte.',
    ]),
    p([txt('Es esencial que la reestimación sea completa en cada corte. Si las constantes de contracción o λ se hubieran fijado con toda la muestra y sólo se reproyectara, el ejercicio filtraría información del futuro y los errores saldrían artificialmente bajos. Aquí se recalcula todo, incluida la selección de λ del apartado 6.7, que se ejecutó '), cur('dentro'), txt(' del bucle de validación, y lo mismo vale para los contrastes de especificación de los apartados 6.5 y 6.6.')]),
    p('Con ocho semestres de historia y la exigencia de al menos cinco para estimar, resultan tres orígenes de reestimación (hasta 2025-I, 2025-II y 2026-I) y seis comparaciones origen-horizonte.'),

    h2('8.2 La métrica'),
    p('Se emplea el error porcentual absoluto ponderado (EPAP, o WAPE en la literatura anglosajona):'),
    ...formula([
      '          Σ | proyectado_i − observado_i |',
      'EPAP =   ─────────────────────────────────',
      '                Σ  observado_i',
    ]),
    p('Se prefiere al error porcentual absoluto medio (EPAM) porque este último otorga el mismo peso a una celda de 800 estudiantes que a una de 3, y basta con unas pocas celdas diminutas para que el promedio pierda todo significado. El EPAP pondera cada celda por su matrícula, que es lo que importa cuando el resultado se usa para dimensionar recursos.'),
    nota('Sobre la comparación entre revisiones.', 'El EPAP depende del nivel de agregación en que se mide, y cada dimensión añadida parte las celdas: la modalidad en hasta tres y la continuidad en hasta cuatro más. Comparar el cruce más fino de esta revisión con el de la anterior no diría nada, porque no son la misma partición. Las comparaciones entre especificaciones de este documento —apartados 1.2, 1.3, 6.5 y 6.6— se hacen todas sobre niveles que existen en ambas.'),

    h2('8.3 Resultados'),
    ...figura('15_validacion.png', 'Tablas de validación dentro del propio modelo: error por nivel de agregación y cobertura empírica del intervalo.', { maxAlto: 470 }),
    tabla([1600, 1650, 1250, 1300, 1500, 1726],
      ['Ajustado hasta', 'Proyectado', 'Horizonte', 'Observado', 'Proyectado', 'Error'],
      [
        ['2025-I', '2025-II', '1', '16 353', '16 422', '+0,42 %'],
        ['2025-I', '2026-I', '2', '21 420', '21 129', '−1,36 %'],
        ['2025-I', '2026-II', '3', '20 330', '20 668', '+1,66 %'],
        ['2025-II', '2026-I', '1', '21 420', '21 099', '−1,50 %'],
        ['2025-II', '2026-II', '2', '20 330', '20 478', '+0,73 %'],
        ['2026-I', '2026-II', '1', '20 330', '20 579', '+1,23 %'],
      ]),
    pieTabla('Detalle del backtesting sobre el total institucional.'),
    p('El error a un semestre vista se mueve entre el 0,42 % y el 1,50 %, con una media del 1,05 %. Para una institución de veinte mil estudiantes, eso supone un error medio del orden de 210 estudiantes sobre el total.'),
    tabla([3600, 2400, 2226],
      ['Revisión del modelo', 'EPAP medio del total', 'Sesgo medio'],
      [
        ['Ciclo, sede, carrera, turno', '2,06 %', '+293'],
        ['+ modalidad de estudios', '1,74 %', '+187'],
        ['+ continuidad de la matrícula', '1,15 %', '+32'],
      ]),
    pieTabla('Evolución del error del total institucional a lo largo de las revisiones del modelo, con la λ elegida por validación cruzada en cada especificación. Las dos últimas filas son los dos brazos de la ablación del apartado 6.6, medidos sobre la base actual; la primera es la medición que reportó aquella revisión, sobre la misma base pero con el estado reducido a cuatro dimensiones.'),

    h2('8.4 El sesgo y la matrícula abierta de 2026-II'),
    p('El sesgo medio del total es de +32 estudiantes, un 0,16 % de la matrícula: prácticamente nulo en el agregado. Conviene aun así descomponerlo, porque esa cifra pequeña es la suma de dos sesgos de signo contrario que no se compensan por casualidad.'),
    p([txt('Las tres comparaciones que apuntan a 2026-II tienen sesgo positivo (+338, +148 y +249); las tres que apuntan a otros semestres suman un sesgo medio de '), neg('−181 estudiantes'), txt(', es decir, algo menos de un punto porcentual por debajo sobre una matrícula de unos veinte mil. Excluir el semestre sospechoso no reduce el sesgo: le cambia el signo.')]),
    tabla([3400, 2700, 2926],
      ['Conjunto de comparaciones', 'Sesgo medio', 'Sobre la matrícula'],
      [
        ['Las seis comparaciones', '+32 estudiantes', '+0,16 %'],
        ['Sólo las que apuntan a 2026-II', '+245 estudiantes', '+1,21 %'],
        ['Excluyendo 2026-II', '−181 estudiantes', '−0,92 %'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.CENTER] }),
    pieTabla('Descomposición del sesgo del backtesting según el semestre proyectado.'),
    p('Esto es coherente con el hallazgo del apartado 3.4.2: la matrícula de 2026-II seguía abierta en la fecha de extracción. El modelo no está sobreestimando; está proyectando una matrícula completa contra un dato aún incompleto. Una vez descontado ese semestre, el sesgo residual es pequeño y de signo contrario, que es lo que cabe esperar de un estimador sin sesgo sistemático evaluado sobre tres observaciones.'),
    nota('Cómo comprobarlo.', 'Cuando se disponga del cierre definitivo de 2026-II, basta con volver a ejecutar la estimación: si la interpretación es correcta, el sesgo de esas tres comparaciones debe reducirse sustancialmente. El procedimiento es reproducible y queda documentado en el Excel de exportación.'),
    p('Es relevante además que los dos contrastes de especificación apunten en la misma dirección. Incorporar la modalidad redujo el sesgo medio de +259 a +153 estudiantes, e incorporar la continuidad lo reduce de +187 a +32 sobre los mismos datos. Lo que parecía sobreestimación sistemática era, en buena parte, aplicar la retención media a poblaciones que retienen mucho menos: los estudiantes a distancia y los que vuelven de una interrupción.'),

    h2('8.5 Qué se puede afirmar y qué no'),
    p('La validación se apoya en tres orígenes y seis comparaciones. Es la información disponible, y conviene ser explícito sobre su alcance.'),
    ...vinetas([
      [neg('Se puede afirmar: '), txt('que el modelo no está sesgado de forma apreciable una vez se descuenta el semestre incompleto; que su error a un semestre vista en el total es del orden del 1,4 %; que la aritmética de la incertidumbre está bien planteada, porque el factor de inflación calibrado sigue siendo 1,0; y que las dos dimensiones de composición mejoran la proyección en todos los niveles comparables, cada una por separado.')],
      [neg('No se puede afirmar: '), txt('que el error vaya a mantenerse exactamente en ese nivel, ni que las mejoras sean exactamente del 17 % y del 21 % en el total. Seis comparaciones no permiten estimar con precisión la distribución del error, y el horizonte 3 se apoya en una sola observación. Tampoco puede afirmarse nada sólido sobre el total de reiniciados y recuperados de un semestre concreto: su intervalo es el único que no alcanza la cobertura nominal.')],
      [neg('Conviene repetir: '), txt('cada semestre nuevo añade un origen de validación. El procedimiento está automatizado y reejecutarlo con datos actualizados no requiere trabajo adicional.')],
    ]),
    salto(),
  ];
}

function manual() {
  return [
    h1('9. Manual de uso'),
    h2('9.1 Puesta en marcha'),
    p([txt('El modelo es un único archivo, '), mono('modelo_proyeccion_matricula.html'), txt('. Se abre con doble clic en cualquier navegador moderno. No necesita instalación, servidor ni conexión a internet: todos los datos y el motor de cálculo viajan dentro del archivo. Puede copiarse, enviarse por correo o guardarse en una carpeta compartida.')]),
    p('Al abrirlo, el modelo ya muestra una proyección calculada con un supuesto de referencia —repetir el último ingreso observado del semestre de la misma paridad, con su composición por modalidad— claramente señalado como marcador de posición. Sirve para explorar la herramienta antes de disponer del archivo de admisión; no es una previsión.'),
    nota('Qué NO hay que declarar.', 'El archivo de entrada contiene únicamente ingresantes. Los continuadores —regulares, reiniciados y recuperados— los genera el modelo, y su desglose en las tablas sale de la recursión. No hay ningún sitio donde declarar cuántos estudiantes se espera recuperar, y eso es deliberado: el modelo proyecta el comportamiento observado, no los objetivos de una campaña.'),
    ...figura('01_cabecera.png', 'Vista inicial del modelo: cinta de acciones, barra de control y pestaña de resumen.', { maxAlto: 400 }),

    h2('9.2 La plantilla de ingresantes'),
    p([txt('El botón '), neg('«Plantilla»'), txt(' descarga un Excel de tres hojas:')]),
    ...vinetas([
      [neg('Instrucciones. '), txt('Descripción de cada columna, tratamiento de los programas nuevos y nomenclatura de semestres.')],
      [neg('Ingresantes. '), txt('La hoja que hay que editar. Viene precargada con el último ingreso observado de cada paridad, desglosado por modalidad, de modo que se parte de una base realista y sólo hay que ajustar las cifras.')],
      [neg('Catálogos. '), txt('Sedes con sus turnos disponibles, sus modalidades y su ciclo máximo ofertable; y carreras con los ciclos de su plan y las modalidades en que se imparten, para escribir los nombres exactamente como los espera el modelo.')],
    ]),
    tabla([1700, 1200, 6126],
      ['Columna', 'Obligatoria', 'Contenido'],
      [
        ['Periodo', 'Sí', 'Semestre académico: 2027-I, 2027-II. También se admite el formato 202701.'],
        ['Sede', 'Sí', 'Debe coincidir con el catálogo para heredar el patrón de turno de esa sede. Una sede que no figure se entiende que abre en el primer semestre en que aparezca, con despliegue progresivo del plan.'],
        ['Carrera', 'Sí', 'Si no figura en el catálogo, se trata como programa nuevo.'],
        ['Modalidad', 'Recomendada', 'Presencial, Semi Presencial o A distancia. Se reconocen sinónimos habituales (virtual, online, blended, híbrida, semipresencial). Si se deja vacía, el modelo la estima por el apartado 6.9 y lo advierte.'],
        ['Ciclo', 'Sí', 'Ciclo al que ingresa: 1 en la admisión ordinaria, mayor que 1 en traslados y convalidaciones.'],
        ['Nuevos', 'Sí', 'Número de ingresantes de esa combinación.'],
        ['CiclosPlan', 'No', 'Ciclos totales del plan. Sólo hace falta para un programa nuevo cuya duración no sea de diez ciclos.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Columnas del archivo de entrada. El lector reconoce además sinónimos habituales de cada encabezado.'),
    nota('El turno no se declara; la modalidad sí conviene declararla.', 'Tal como pide el encargo, el archivo de entrada no lleva columna de turno: el modelo lo estima con el procedimiento del apartado 6.8 y muestra el reparto resultante en la pestaña «Ingresantes», indicando en cada fila el nivel de evidencia empleado. La modalidad es distinta: es un dato que el área de admisión conoce y que el modelo no puede deducir. Si falta, se estima —y el modelo lo advierte fila por fila— pero la proyección pierde precisión.'),
    p([txt('Un archivo preparado con la plantilla anterior, sin columna de modalidad, '), neg('sigue funcionando'), txt(': el modelo lo detecta, avisa de cuántas filas ha tenido que estimar y aplica el reparto del apartado 6.9. No hay que rehacer nada para seguir usándolo.')]),

    h2('9.3 Cargar el archivo'),
    p([txt('El botón '), neg('«Cargar ingresantes»'), txt(' abre el selector de archivos y admite .xlsx y .csv. Tras la carga, el modelo:')]),
    ...numerada([
      'Ajusta automáticamente el horizonte al último semestre presente en el archivo.',
      'Identifica las carreras y sedes que no existen en el histórico y las marca como nuevas.',
      'Avisa de cuántas filas declaran modalidad y cuántas ha tenido que estimar.',
      'Avisa si alguna fila declara un ciclo superior al del plan de la carrera o al que la sede puede ofrecer todavía, y lo ajusta al máximo disponible.',
      'Advierte si el archivo contiene semestres anteriores o iguales al último observado, que no se proyectan.',
      'Recalcula y repinta toda la proyección.',
    ]),
    ...figura('09_ingresantes_estado.png', 'Resumen del archivo cargado y avisos de validación, incluida la detección del programa nuevo y el recuento de modalidades declaradas.', { maxAlto: 260 }),

    h2('9.4 Elegir el horizonte'),
    p([txt('El campo '), neg('«Semestres a proyectar»'), txt(' admite de 1 a 24 semestres. Debajo se muestra el intervalo resultante con la nomenclatura de la universidad, de modo que no hay ambigüedad sobre qué se está proyectando: con 6 semestres desde 2026-II, el intervalo es 2027-I → 2029-II.')]),
    p('La nomenclatura sigue el sistema institucional: el año seguido de I para el primer semestre y II para el segundo. El modelo la aplica en pantalla, en la plantilla y en todas las exportaciones.'),
    nota('Sobre horizontes largos.', 'La validación cubre hasta tres semestres. Proyectar doce es técnicamente posible y la recursión sigue siendo válida, pero a partir del cuarto o quinto semestre la práctica totalidad de la matrícula proviene de ingresantes supuestos por el usuario, de modo que el resultado refleja sobre todo ese supuesto —incluida la composición por modalidad que se haya declarado. El intervalo de predicción se ensancha en consecuencia y debe leerse con atención.'),

    h2('9.5 Leer los resultados'),
    h3('9.5.1 Resumen'),
    p('La pestaña de resumen presenta los indicadores principales, la serie histórica empalmada con la proyección y su banda, la composición entre ingresantes y continuadores, el reparto por sede, la composición por modalidad de estudios, la composición por continuidad de la matrícula y la tabla por semestre y escenario.'),
    p([txt('La tabla de resumen es la que responde directamente al encargo: una fila por semestre, con los '), neg('ingresantes'), txt(' y los '), neg('continuadores abiertos en regulares, reiniciados y recuperados'), txt(', seguidos de los tres escenarios y el intervalo de predicción. Las cuatro primeras columnas suman siempre el total del escenario moderado, porque la condición es parte del estado y no un reparto posterior.')]),
    ...figura('04c_condicion_serie.png', 'Composición de la matrícula por continuidad, observada y proyectada. Los guiones del histórico temprano corresponden a los semestres en que la categoría todavía no es observable (apartado 3.3).', { maxAlto: 300 }),
    ...figura('02_kpis.png', 'Indicadores del resumen. Cada uno lleva su contexto: variación frente al semestre anterior, escenarios alternativos y amplitud del intervalo.', { maxAlto: 260 }),
    ...figura('05_tabla_resumen.png', 'Tabla por semestre y escenario, con la separación entre ingresantes y continuadores y el intervalo de predicción.', { maxAlto: 340 }),

    h3('9.5.2 Detalle'),
    p([txt('La pestaña de detalle permite filtrar por semestre, sede, carrera, modalidad, continuidad y turno, y construir cualquier cruce eligiendo qué dimensión va en filas y cuál en columnas —tanto la modalidad como la continuidad están disponibles en ambos ejes. El selector '), neg('«Escenario en tablas»'), txt(' de la barra superior cambia el escenario mostrado en todas las tablas.')]),
    p('Un cruce útil para la planificación del acompañamiento académico es «Carrera» en filas y «Continuidad» en columnas: muestra dónde se concentran los estudiantes que vuelven de una interrupción, que son los de mayor riesgo de no continuar.'),
    ...figura('07_detalle_cruce.png', 'Cruce de la proyección por carrera y ciclo. Filas y columnas son configurables, y el filtro de modalidad permite aislar cada población.', { maxAlto: 480 }),
    p('Debajo, el detalle por celda lista las combinaciones completas de semestre, sede, carrera, modalidad, continuidad, ciclo y turno, con su margen de precisión. Es la vista que corresponde al nivel más desagregado del encargo.'),
    ...figura('08_detalle_celdas.png', 'Detalle por celda con el margen de precisión de cada una.', { maxAlto: 420 }),

    h3('9.5.3 Modelo y validación'),
    p('La última pestaña no contiene resultados sino el sustento: la ecuación, los parámetros estimados, la caracterización de las tres modalidades y de las cuatro condiciones, la maduración de sede, las tasas de continuación, las matrices de avance y turno, la descomposición de varianza y los resultados de validación. Está pensada para que cualquier cifra de las otras pestañas pueda rastrearse hasta su origen.'),

    h2('9.6 Exportar'),
    p([txt('El botón '), neg('«Exportar proyección»'), txt(' genera un Excel de siete hojas:')]),
    tabla([2400, 6626],
      ['Hoja', 'Contenido'],
      [
        ['Resumen', 'Totales por semestre y escenario, con ingresantes, continuadores abiertos en regulares, reiniciados y recuperados, y el intervalo de predicción. Incluye la cabecera de supuestos: archivo de entrada, horizonte, confianza y choque aplicado.'],
        ['Proyección detallada', 'Una fila por semestre, sede, carrera, modalidad, continuidad, ciclo y turno, con los tres escenarios, la desviación típica independiente y el intervalo de predicción.'],
        ['Agregados', 'Nueve cuadros listos para usar: por sede, carrera, modalidad, ciclo y turno; por modalidad y ciclo; por continuidad; por continuidad y ciclo; y por sede y continuidad, cada uno con los tres escenarios.'],
        ['Ingresantes', 'Los ingresantes utilizados, su modalidad —declarada o estimada— y su reparto estimado por turno, en cantidad y porcentaje, con el nivel de evidencia empleado en cada fila.'],
        ['Parámetros', 'Tasas de continuación por ciclo y rezago, continuación por modalidad y ciclo, tasas por carrera con su valor crudo y contraído, matriz de avance, matriz de turno, maduración de sede y ciclos de plan por carrera.'],
        ['Validación', 'Descomposición de varianza, backtesting por nivel y horizonte, cobertura empírica, detalle del total institucional y rejilla de selección de λ.'],
        ['Metodología', 'Explicación del modelo en doce apartados, para que el archivo se sostenga por sí solo al circular.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.LEFT] }),
    pieTabla('Contenido del archivo Excel de exportación.'),
    p('La exportación incluye todas las celdas de todos los semestres, no sólo las visibles en pantalla, y los totales de cada escenario coinciden exactamente con la suma de sus celdas. La hoja de proyección detallada supera las diecisiete mil filas con un horizonte de cuatro semestres, de modo que conviene usar los filtros de Excel en lugar de recorrerla a mano; los cuadros ya agregados de la hoja «Agregados» cubren los cortes más habituales.'),

    h2('9.7 Parámetros avanzados'),
    p('El botón «Parámetros avanzados» expone tres controles que normalmente no hace falta tocar, pero que permiten reestimar el modelo dentro del navegador y explorar su sensibilidad:'),
    tabla([2600, 1400, 5026],
      ['Control', 'Valor', 'Efecto'],
      [
        ['λ recencia (continuación)', '1,00', 'Ponderación de los semestres antiguos al estimar la continuación, el avance y el reparto por modalidad. Con 1,00, el valor seleccionado, todo el histórico pesa igual; por debajo de 1 los semestres recientes pesan más.'],
        ['λ recencia (turno)', '0,30', 'Lo mismo para el reparto por turno de los ingresantes.'],
        ['Factor de contracción', '1,00', 'Multiplica las constantes k. Por encima de 1 se contrae más hacia los niveles agregados; por debajo, se cree más a cada celda.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Controles avanzados. Los valores por defecto son los seleccionados por validación cruzada.'),
    p('El modelo no trae los parámetros congelados: al mover cualquiera de estos controles vuelve a agregar los conteos de transición semestre a semestre, recalcula las constantes de contracción por el método de los momentos y reproyecta. Incluso el reparto por modalidad de las filas que no la declaran se recalcula, de modo que nada queda fijado fuera del estimador. Es la misma aritmética de la implementación de referencia en Python, verificada punto por punto.'),
    p([txt('El valor por defecto de cada control lo fija la propia estimación, no el archivo HTML: al regenerar el modelo con una base actualizada, la λ que elija la validación cruzada aparece automáticamente en el control. Conviene revisarla al reestimar, porque su '), cur('posición'), txt(' es informativa: si se desplaza hacia el borde inferior de la rejilla, es señal de que ha aparecido una deriva que el modelo no puede ver (apartado 6.7).')]),
    ...figura('17_oscuro.png', 'El modelo también funciona en modo oscuro, conmutable desde la cinta superior.', { maxAlto: 400 }),
    salto(),
  ];
}

function programasNuevos() {
  return [
    h1('10. Programas y sedes nuevas'),
    h2('10.1 El problema'),
    p('Un programa que se abre no tiene historia: no hay cohortes suyas de las que estimar retención, ritmo de avance ni preferencia de turno. Y sin embargo debe poder proyectarse, porque la apertura de programas es justamente uno de los escenarios de planificación más relevantes.'),
    p('Lo mismo vale para una carrera existente que se abre en una modalidad nueva —un programa presencial que empieza a ofrecerse a distancia—, que es un caso cada vez más frecuente a la vista de la deriva documentada en el apartado 3.2.'),

    h2('10.2 La solución: contracción, no reglas especiales'),
    p('El modelo no incorpora ningún tratamiento excepcional. La escalera de contracción resuelve el caso por construcción: al no encontrar evidencia en los niveles finos, la estimación se detiene en el nivel más específico que sí la tenga.'),
    tabla([2600, 3200, 3226],
      ['Parámetro', 'Nivel que se aplica', 'Fundamento'],
      [
        ['Continuación', 'Continuidad × modalidad × ciclo × paridad', 'La estructura por ciclo, continuidad y modalidad es la que más señal contiene y es común a todas las carreras.'],
        ['Avance de ciclo', 'Continuidad × modalidad × ciclo', 'El patrón de aprobación y repetición depende sobre todo del ciclo, de si se vuelve de una pausa y de la modalidad.'],
        ['Transición de turno', 'Sede × modalidad × continuidad × ciclo', 'Depende del catálogo de turnos de la sede y del régimen de la modalidad, que sí se conocen.'],
        ['Reparto de turno de ingresantes', 'Sede × modalidad (o × paridad)', 'La preferencia de turno responde sobre todo a la modalidad y al perfil del alumnado de la sede.'],
        ['Reparto de modalidad, si no se declara', 'Sede × paridad', 'Composición institucional de la sede, restringida a su oferta.'],
        ['Ciclos del plan', 'Declarado o 10 por defecto', 'El usuario puede fijarlo en la columna CiclosPlan de la plantilla.'],
        ['Ciclo máximo ofertable', 'Tope de maduración de la sede', 'Si la sede también es nueva, el programa sólo crece al ritmo al que crece la sede.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.LEFT, AlignmentType.LEFT] }),
    pieTabla('Niveles de la escalera de contracción que se aplican a un programa sin historia.'),
    p([txt('Obsérvese que un programa nuevo hereda el comportamiento de '), neg('su modalidad y de la condición de cada cohorte'), txt(', no el promedio institucional. Una carrera nueva a distancia arranca con una continuación de primer ciclo del orden del 42 %, no del 60 % que promedian las tres modalidades. Y a partir del tercer semestre, cuando empiece a tener reiniciados propios, el modelo les aplicará la tasa de un reiniciado sin que haya que configurar nada.')]),
    p('A medida que el programa acumule semestres, sus propias celdas ganarán observaciones y el estimador les dará peso de forma progresiva y automática, sin intervención ni recalibrado.'),

    h2('10.3 Ejemplo verificado'),
    p('Para comprobar el comportamiento se preparó un archivo de entrada con un programa inexistente en el histórico, INTELIGENCIA ARTIFICIAL, con plan declarado de ocho ciclos y ingresantes en las tres modalidades, en Lima Sur y Lima Norte.'),
    ...vinetas([
      'El modelo lo detectó como programa nuevo y lo señaló en la pestaña de ingresantes.',
      'Aplicó el plan de ocho ciclos declarado, limitando correctamente el avance.',
      'Aplicó a cada fila la continuación y el avance de su modalidad declarada, no el promedio institucional.',
      'En su primer semestre todos sus estudiantes son ingresantes; en el segundo aparecen sus primeros regulares, y en el cuarto sus primeros reiniciados, sin ninguna configuración.',
      'Resolvió el reparto de turno en el nivel «sede·modalidad·paridad», informándolo en la columna correspondiente.',
      'Proyectó su matrícula a lo largo del horizonte con la estructura de continuación por ciclo y modalidad.',
    ]),
    p('El resultado del reparto por turno ilustra bien lo que aporta condicionar en la modalidad. Las tres filas del programa comparten sede, carrera, ciclo y semestre; se diferencian sólo en la modalidad, y el modelo les asigna turnos radicalmente distintos:'),
    tabla([2500, 1450, 1450, 1450, 2176],
      ['Modalidad declarada', '→ Mañana', '→ Noche', '→ Tarde', 'Nivel de evidencia'],
      [
        ['Presencial', '76,2 %', '20,8 %', '3,0 %', 'sede·modalidad·paridad'],
        ['Semi Presencial', '0,0 %', '97,8 %', '2,2 %', 'sede·modalidad·paridad'],
        ['A distancia', '0,0 %', '98,8 %', '1,2 %', 'sede·modalidad·paridad'],
      ]),
    pieTabla('Reparto por turno estimado para el programa nuevo en Lima Sur, primer ciclo, semestre impar. Sin la dimensión de modalidad las tres filas habrían recibido el mismo reparto.'),
    ...figura('18_escenario_pesimista.png', 'Cruce por carrera y ciclo en escenario pesimista; el programa nuevo aparece con normalidad junto al resto de la oferta.', { maxAlto: 480 }),

    h2('10.4 Sedes nuevas'),
    p('El mismo archivo de entrada admite sedes que no existen en el histórico. La sede se da por abierta en el primer semestre en que aparece y a partir de ahí despliega su plan ciclo a ciclo, según el apartado 5.8.'),
    p('En la prueba se declaró una sede inexistente, Lima Este, con 160 ingresantes de primer ciclo en 2028-I y, en 2028-II, otros 50 de primer ciclo más una fila de 30 traslados declarados al ciclo 4. El modelo:'),
    ...vinetas([
      'La reconoció como sede nueva y fijó su apertura en 2028-I, con ciclo base 1.',
      'No le asignó ninguna matrícula en 2027-I ni 2027-II, semestres anteriores a su apertura.',
      [txt('Avisó fila por fila: '), cur('«Fila 581: Lima Este no imparte todavía el ciclo 4 en 2028-II (inició en 2028-I, llega hasta el ciclo 2); esos 30 ingresantes se asignan al ciclo 2»'), txt('.')],
      'Proyectó 160 estudiantes en el ciclo 1 en 2028-I —todos ingresantes— y, en 2028-II, 55 en el ciclo 1 y 136 en el ciclo 2, repartidos en 80 ingresantes y 111 regulares: ningún estudiante en un ciclo que la sede no imparte todavía, y ningún reiniciado, porque la sede aún no tiene historia suficiente para producirlos.',
      'Tomó el reparto por turno de la distribución institucional de cada modalidad, al no haber ninguna evidencia propia de esa sede.',
    ]),
    nota('Sobre el turno de una sede nueva.', 'Es la estimación más frágil de todo el modelo. El turno depende del perfil del alumnado de cada sede —Lima Norte y Lima Sur ni siquiera comparten catálogo de turnos— y una sede nueva no aporta ninguna información al respecto. Incorporar la modalidad mitiga el problema, porque una carrera a distancia es nocturna con independencia de la sede, pero no lo resuelve para la parte presencial. Conviene revisar ese reparto en cuanto exista un semestre de matrícula real.'),
    nota('Lectura de cautela.', 'Que el modelo proyecte un programa nuevo no significa que acierte. Está aplicando el comportamiento medio de su modalidad a una población de la que no sabe nada, y un programa nuevo puede atraer un perfil de estudiante con retención distinta. La cifra es una hipótesis razonada de partida, no una previsión con la misma solidez que la de un programa consolidado. Conviene revisarla en cuanto existan dos o tres semestres de historia propia.'),
    salto(),
  ];
}

function limitaciones() {
  return [
    h1('11. Limitaciones y mantenimiento'),
    h2('11.1 Limitaciones'),
    ...numerada([
      [neg('La proyección es condicional al archivo de ingresantes. '), txt('El modelo no pronostica la admisión ni su reparto por modalidad. Si el supuesto de ingreso es erróneo, la proyección lo será en la misma medida, y el modelo no tiene forma de advertirlo.')],
      [neg('Supone continuidad del comportamiento. '), txt('Un cambio de plan de estudios, de política de permanencia, de estructura de becas o de oferta de turnos y modalidades rompe el supuesto. La estimación lo recogerá con uno o dos semestres de retraso, no de inmediato.')],
      [neg('La validación se apoya en seis comparaciones. '), txt('Es la información disponible con ocho semestres de historia. Las cifras del horizonte 3 descansan sobre una única observación y deben leerse como indicativas. Lo mismo vale para la magnitud exacta de la mejora atribuida a la modalidad en el apartado 6.5.')],
      [neg('El nivel más desagregado es impreciso. '), txt('Un EPAP del 34 % en el cruce completo refleja que muchas celdas tienen menos de cinco estudiantes. A ese nivel, el intervalo de predicción es tan informativo como el punto.')],
      [neg('El desglose por condición es la parte menos fiable del modelo. '), txt('Su intervalo de predicción cubre el 50 % de los casos frente a un 80 % nominal, y no alcanza el nominal ni duplicando κ. El volumen de reingresos de un semestre depende de decisiones institucionales —campañas de recuperación, amnistías de deuda, flexibilización de requisitos— que no están en los datos, y el de recuperados depende de la exigencia académica de cada semestre. Conviene leer el reparto entre las tres condiciones como un orden de magnitud —el total al que suman es mucho más fiable— y revisarlo si hay una campaña en marcha.')],
      [neg('La memoria de la condición es de un semestre. '), txt('Quien vuelve de una interrupción es reiniciado en el semestre del regreso y pasa a regular o a recuperado en el siguiente, aunque empíricamente siga por debajo de un regular durante dos o tres semestres más (apartado 4.3.2). El sesgo que eso introduce en la tasa de los regulares es de un cuarto de punto, medido sobre 1 367 orígenes de 73 063.')],
      [neg('La modalidad a distancia tiene historia corta en los ciclos altos. '), txt('Su matrícula no pasa todavía del ciclo 7, de modo que su continuación en los ciclos 8 a 11 y su ciclo terminal se estiman por contracción hacia el perfil general, no con evidencia propia. Es la parte del modelo que más se beneficiará de cada semestre nuevo.')],
      [neg('Las categorías de continuidad están censuradas al inicio de la ventana. '), txt('Un recuperado necesita un semestre previo para ser observable y un reiniciado, dos, de modo que 2023-I no aporta ninguna observación de esas categorías y 2023-II sólo de recuperados. El estimador lo controla —una matrícula entra en el conjunto de riesgo sólo si su condición es observable— pero la muestra efectiva de esos grupos es menor que la del resto, y ésa es una de las razones por las que λ se sitúa cerca de 1: descartar semestres antiguos los dejaría sin datos.')],
      [neg('El semestre 2026-II estaba incompleto. '), txt('Afecta al punto de partida de la recursión y a las comparaciones de validación que apuntan a ese semestre. Conviene reestimar con el cierre definitivo.')],
      [neg('Los programas nuevos heredan comportamiento ajeno. '), txt('Es la mejor estimación disponible sin historia propia, pero no equivale a una proyección basada en evidencia del propio programa.')],
      [neg('El tope de maduración es una restricción, no una predicción. '), txt('Establece qué ciclos puede ofrecer una sede recién abierta, pero supone que el despliegue avanza un ciclo por semestre sin interrupción. Si la sede abriera dos ciclos a la vez, o retrasara la apertura de uno, habría que reflejarlo en los datos y reestimar.')],
    ]),

    h2('11.2 Cuándo reestimar'),
    p('El modelo lleva incorporados los conteos de transición semestre a semestre, de modo que puede reestimarse dentro del navegador moviendo los parámetros de recencia y contracción. Lo que no puede hacer por sí solo es incorporar semestres nuevos: para eso hay que regenerar el archivo con la base actualizada.'),
    ...vinetas([
      [neg('Cada semestre, '), txt('al cerrar la matrícula: añadir el semestre a la base y regenerar. Se gana un origen de validación y se actualiza el punto de partida.')],
      [neg('Ante un cambio estructural '), txt('—nuevo plan de estudios, nueva sede, nueva modalidad en una carrera, cambio en la política de turnos—: reestimar y comprobar si las constantes de contracción y la λ seleccionada se desplazan.')],
      [neg('Si el error fuera de muestra se degrada '), txt('de forma sostenida por encima del 3 % en el total: es señal de que algo cambió en el comportamiento y conviene revisar la especificación, no sólo reestimar.')],
      [neg('Si la λ seleccionada se va al borde INFERIOR de la rejilla, '), txt('como ocurría sin las dimensiones de modalidad y continuidad: es el síntoma de una variable relevante omitida, y conviene buscarla antes de aceptar la proyección. Un valor alto, en cambio, es buena señal.')],
    ]),

    h2('11.3 Reproducibilidad'),
    p('Todo el procedimiento es determinista. Con la misma base histórica y el mismo archivo de ingresantes, el modelo devuelve exactamente las mismas cifras: no hay simulación, muestreo aleatorio ni semillas.'),
    p([txt('La implementación de referencia se escribió en Python (pandas, numpy, scipy y statsmodels) y el motor de producción en JavaScript dentro del HTML. Ambos se verificaron sobre el mismo conjunto de parámetros y el mismo caso de prueba: sobre seis semestres proyectados, los totales, las desviaciones típicas y los desgloses por modalidad y por continuidad coinciden con una diferencia relativa máxima del orden de 10⁻¹⁶ —el epsilon de la doble precisión— y las constantes de contracción, del orden de 10⁻¹⁵. Lo que queda es el orden de acumulación en coma flotante, no diferencia de lógica.')]),
    nota('Por qué dos implementaciones.', 'La versión en Python permite usar bibliotecas econométricas contrastadas para el GLM y los contrastes estadísticos, y sirve de referencia frente a la cual verificar el motor del navegador. La versión en JavaScript es la que el usuario ejecuta, sin instalar nada. La verificación cruzada entre ambas es la garantía de que lo que se documenta aquí es lo que el modelo calcula.'),
    salto(),
  ];
}

function anexos() {
  return [
    h1('Anexo A. Parámetros estimados'),
    h2('A.1 Continuación por ciclo y rezago'),
    tabla([1150, 1700, 1550, 1550, 1550, 1526],
      ['Ciclo', 'Observaciones', 'L = 1', 'L = 2', 'L = 3', 'L = 4'],
      [
        ['1', '28 870', '61,4 %', '1,9 %', '0,6 %', '0,4 %'],
        ['2', '15 622', '82,3 %', '2,9 %', '1,0 %', '0,4 %'],
        ['3', '13 403', '87,1 %', '3,2 %', '1,0 %', '0,4 %'],
        ['4', '10 613', '88,5 %', '3,0 %', '1,0 %', '0,4 %'],
        ['5', '9 418', '90,4 %', '3,3 %', '0,9 %', '0,5 %'],
        ['6', '7 149', '91,3 %', '3,0 %', '0,9 %', '0,3 %'],
        ['7', '7 132', '91,1 %', '3,2 %', '1,3 %', '0,5 %'],
        ['8', '5 579', '91,3 %', '2,8 %', '1,1 %', '0,4 %'],
        ['9', '5 220', '93,4 %', '2,5 %', '0,6 %', '0,4 %'],
        ['10', '4 708', '49,1 %', '2,0 %', '1,0 %', '0,2 %'],
        ['11', '2 085', '18,8 %', '1,8 %', '0,7 %', '0,5 %'],
      ]),
    pieTabla('Probabilidad de que la siguiente matrícula ocurra L semestres después, por ciclo de origen. Valores con la ponderación de recencia λ = 1,00 activa; las observaciones son el recuento sin ponderar. La caída de los ciclos 10 y 11 corresponde al egreso. Nótese que el reingreso tras pausa (L ≥ 2) es menos frecuente en el ciclo 1: quien abandona en el primer ciclo rara vez vuelve.'),
    p([txt('Las columnas L ≥ 2 de esta tabla son, por construcción, las que alimentan la condición de '), neg('reiniciado'), txt(' del semestre de destino: son los regresos tras una o más pausas. Sumadas dan el 3,9 % de las matrículas de origen. La columna L = 1 se reparte a su vez entre '), neg('regular'), txt(' y '), neg('recuperado'), txt(' según el salto de ciclo, como detalla el apartado 5.5.')]),

    h2('A.2 Continuación por modalidad y ciclo'),
    p('Tasas de continuación a un semestre (L = 1), agrupadas sobre las condiciones de llegada y las dos paridades, con la ponderación de recencia activa. Son las mismas que el modelo muestra en pantalla.'),
    tabla([1500, 2500, 2500, 2526],
      ['Ciclo', 'Presencial', 'Semi Presencial', 'A distancia'],
      [
        ['1', '71,2 %', '56,1 %', '42,1 %'],
        ['2', '83,3 %', '82,9 %', '78,0 %'],
        ['3', '87,8 %', '86,3 %', '84,3 %'],
        ['4', '88,7 %', '87,7 %', '88,1 %'],
        ['5', '90,3 %', '90,2 %', '91,3 %'],
        ['6', '91,1 %', '92,0 %', '92,1 %'],
        ['7', '90,8 %', '93,6 %', '91,1 %'],
        ['8', '91,1 %', '93,1 %', '—'],
        ['9', '93,0 %', '97,9 %', '—'],
        ['10', '49,2 %', '47,6 %', '—'],
        ['11', '19,2 %', '0,0 %', '—'],
      ]),
    pieTabla('Continuación a un semestre por modalidad y ciclo. La brecha se concentra en los dos primeros ciclos y se cierra a partir del cuarto. Los guiones señalan ciclos sin evidencia propia de esa modalidad: la matrícula a distancia no pasa todavía del ciclo 7. El 0,0 % de la semipresencial en el ciclo 11 no es un hueco sino un dato: los 34 estudiantes de esa casilla egresaron todos. En la proyección esas celdas se resuelven por contracción hacia el perfil del ciclo.'),
    p([txt('Las tres columnas convergen a partir del ciclo 4 y la caída terminal de los ciclos 10 y 11 es común: el egreso no depende de la modalidad. La diferencia de comportamiento está en la '), neg('entrada'), txt(', no en la permanencia ni en la salida.')]),

    h2('A.3 Continuación por continuidad de la matrícula y ciclo'),
    p('Tasas de continuación a un semestre (L = 1), agrupadas sobre las dos paridades y con la ponderación de recencia activa. Entre paréntesis, las observaciones ponderadas de cada celda: son la clave para saber de cuáles fiarse.'),
    tabla([1150, 1980, 1980, 1980, 1936],
      ['Ciclo', 'Regular', 'Recuperado', 'Reiniciado', 'Ingresante'],
      [
        ['1', '71,6 %  (563)', '57,0 %  (596)', '56,3 %  (286)', '61,3 %  (27 425)'],
        ['2', '84,3 %  (13 670)', '72,7 %  (952)', '55,0 %  (422)', '72,5 %  (578)'],
        ['3', '89,5 %  (12 056)', '73,3 %  (719)', '52,2 %  (400)', '68,4 %  (228)'],
        ['4', '90,4 %  (9 460)', '80,7 %  (673)', '60,9 %  (350)', '59,2 %  (130)'],
        ['5', '91,8 %  (8 636)', '84,8 %  (442)', '59,4 %  (303)', '70,3 %  (37)'],
        ['6', '92,8 %  (6 597)', '82,1 %  (302)', '62,1 %  (224)', '57,7 %  (26)'],
        ['7', '92,3 %  (6 490)', '84,4 %  (398)', '70,9 %  (223)', '66,7 %  (21)'],
        ['8', '92,6 %  (4 969)', '85,6 %  (418)', '68,3 %  (189)', '—  (3)'],
        ['9', '94,4 %  (4 732)', '86,8 %  (357)', '72,7 %  (128)', '—  (3)'],
        ['10', '50,4 %  (4 103)', '41,0 %  (490)', '38,6 %  (114)', '—  (1)'],
        ['11', '20,3 %  (1 787)', '9,1 %  (242)', '16,4 %  (55)', '—  (1)'],
      ], { tam: 17 }),
    pieTabla('Continuación a un semestre por condición de llegada y ciclo. La brecha entre regular y reiniciado se mantiene a lo largo de todo el plan, a diferencia de la brecha por modalidad, que se cierra en el cuarto ciclo.'),
    p([txt('Tres lecturas conviene destacar. La primera es que el reiniciado del ciclo 3 (52,2 %) está treinta y siete puntos por debajo del regular del mismo ciclo (89,5 %): es la mayor diferencia que produce cualquier dimensión del modelo. La segunda es que el recuperado ocupa sistemáticamente la posición intermedia, y que su brecha '), neg('se cierra'), txt(' —de doce puntos en el ciclo 2 a menos de ocho en el 9— mientras que la del reiniciado se mantiene por encima de los veinte. La tercera es que en los ciclos terminales las tres condiciones convergen: el egreso no distingue.')]),
    nota('Cuidado con las celdas pequeñas.', 'Los reiniciados no pasan de unos pocos centenares de observaciones ponderadas en ningún ciclo, y el ingresante desaparece a partir del ciclo 8 —ahí sólo quedan convalidaciones— de modo que sus casillas se muestran con guion por debajo de veinte observaciones. El recuperado, en cambio, tiene entre trescientas y mil observaciones por ciclo hasta el 9, y su perfil es estable. La contracción hacia el perfil del ciclo modera los valores más ruidosos en la proyección —es justamente para lo que sirve— pero la tabla se presenta en crudo para que el lector vea sobre qué evidencia descansa cada casilla.'),

    h2('A.4 Ciclos del plan por carrera'),
    p('El ciclo terminal se infiere del comportamiento de continuación observado. Las carreras cuyo historial no alcanza aún los ciclos superiores conservan el valor por defecto de diez ciclos.'),
    tabla([4500, 1400, 3126],
      ['Carrera', 'Ciclos', 'Origen del valor'],
      [
        ['DERECHO', '11', 'Inferido: continuación alta en el ciclo 10 (87,8 %).'],
        ['PSICOLOGÍA', '11', 'Inferido: continuación alta en el ciclo 10 (93,6 %).'],
        ['Las 23 carreras restantes', '10', 'Inferido o valor por defecto en las carreras censuradas.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Duración del plan de estudios por carrera.'),

    h2('A.5 Oferta por modalidad'),
    p('De las 150 combinaciones teóricas de sede, carrera y modalidad sólo existen 83. El modelo respeta esa restricción tanto al proyectar continuadores como al repartir ingresantes sin modalidad declarada.'),
    tabla([3400, 1800, 3826],
      ['Restricción de oferta', 'Alcance', 'Consecuencia en la proyección'],
      [
        ['Carreras sólo presenciales', '7 de 25', 'Enfermería, Obstetricia, Farmacia y Bioquímica, Ingeniería Biomédica, Ciencias de la Comunicación y las dos de Tecnología Médica.'],
        ['Carreras en dos modalidades', '6 de 25', 'Reparto entre las dos disponibles.'],
        ['Carreras en las tres modalidades', '12 de 25', 'Reparto completo.'],
        ['Lima Norte', 'sin «A distancia»', 'La sede imparte 17 carreras, en modalidad presencial y semipresencial.'],
        ['Lima Sur', 'las tres modalidades', 'Las 25 carreras.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Estructura de la oferta por modalidad, tal como la detecta el modelo del histórico.'),

    h2('A.6 Continuación global por rezago'),
    tabla([2600, 1600, 4826],
      ['Rezago', 'Probabilidad', 'Interpretación'],
      [
        ['L = 1', '78,19 %', 'Se rematricula en el semestre inmediato siguiente. → Regular si cambia de ciclo, Recuperado si vuelve al mismo.'],
        ['L = 2', '2,68 %', 'Regresa tras interrumpir un semestre. → Reiniciado.'],
        ['L = 3', '0,87 %', 'Regresa tras interrumpir dos semestres. → Reiniciado.'],
        ['L = 4', '0,39 %', 'Regresa tras interrumpir tres semestres. → Reiniciado.'],
        ['No vuelve', '17,86 %', 'Deserción o egreso, según el ciclo.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Continuación global por rezago, con la ponderación de recencia activa. La última columna indica la condición que el rezago asigna al estudiante en el semestre de destino: es la identidad del apartado 5.5.'),
    salto(),

    h1('Anexo B. Glosario'),
    tabla([2600, 6426],
      ['Término', 'Definición'],
      [
        ['Ablación', 'Contraste que ejecuta el procedimiento completo con y sin un componente para medir su aportación. Aquí se aplica a la dimensión de modalidad (apartado 6.5).'],
        ['Backtesting de origen móvil', 'Validación que reestima el modelo con datos hasta un corte y proyecta el resto, desplazando el corte. Evita usar información del futuro en la evaluación.'],
        ['Cadena de Markov de cohortes', 'Modelo en el que una población se reparte entre estados y avanza según probabilidades de transición estimadas.'],
        ['Choque de periodo', 'Desviación de la tasa de continuación de un semestre respecto de su nivel esperado, común a todas las cohortes de ese semestre.'],
        ['Contracción (shrinkage)', 'Combinar la estimación de una celda con la de un nivel más agregado, en proporción a la información disponible en cada uno.'],
        ['Descomposición de Oaxaca-Blinder', 'Reparto del cambio de una media entre la parte debida al cambio de composición de los grupos y la debida al cambio dentro de cada grupo (apartado 4.6.1).'],
        ['EPAP (WAPE)', 'Error porcentual absoluto ponderado: suma de errores absolutos dividida por la suma de observados. Pondera cada celda por su tamaño.'],
        ['Empírico-Bayes', 'Enfoque en que los parámetros de la distribución a priori se estiman de los propios datos en lugar de fijarse de antemano.'],
        ['Escala logit', 'Transformación log(p/(1−p)) que lleva una probabilidad a toda la recta real. Un desplazamiento en logit nunca produce probabilidades fuera de [0, 1].'],
        ['GLM binomial', 'Modelo lineal generalizado para variable dependiente binaria; con enlace logit equivale a la regresión logística.'],
        ['Intervalo de predicción', 'Rango en el que se espera que caiga el valor observado. Incluye la incertidumbre sistémica y el azar de realización.'],
        ['Método de los momentos', 'Estimación que iguala momentos teóricos y muestrales. Aquí se usa para obtener la constante de contracción.'],
        ['Continuidad de la matrícula', 'Dimensión del estado que distingue al continuador regular —se matriculó el semestre anterior y cambió de ciclo— del recuperado —se matriculó el semestre anterior y vuelve al mismo ciclo, porque perdió el que cursaba— y del reiniciado —interrumpió uno o más semestres—. No se estima: la determinan el rezago y el salto de ciclo del flujo.'],
        ['Criterio minimax', 'Regla de elección que minimiza la peor pérdida entre varios criterios en competencia. Aquí se usa para seleccionar λ acotando el sobrecoste del nivel de agregación peor servido.'],
        ['Modalidad de estudios', 'Régimen en que se cursa el programa: presencial, semipresencial o a distancia. En este modelo es un atributo conservado del estado que condiciona la continuación, el avance y el turno.'],
        ['Paridad del semestre', 'Si un semestre es el primero (I) o el segundo (II) del año. La continuación y la mezcla de turno difieren sistemáticamente entre ambos.'],
        ['Restricción de oferta', 'Conjunto de combinaciones de sede, carrera y modalidad que la universidad imparte realmente. El modelo no genera matrícula fuera de ellas.'],
        ['Razón de momios', 'Cociente entre los momios de dos grupos, siendo los momios p/(1−p). Una razón de 0,185 significa que los momios del primer grupo son algo menos de la quinta parte de los del segundo. Es la medida natural del efecto en un modelo logit.'],
        ['Rezago', 'Número de semestres entre una matrícula y la siguiente del mismo estudiante. Un rezago mayor que 1 es un reingreso tras pausa. Junto con el salto de ciclo determina la condición de llegada del estudiante al semestre de destino.'],
        ['Semivida', 'Antigüedad a la que el peso de recencia se reduce a la mitad: log(0,5)/log(λ).'],
        ['Tamaño muestral efectivo', 'Observaciones equivalentes de una estimación tras la ponderación de recencia y la contracción. Gobierna el error de parámetro.'],
        ['Variable omitida', 'Regresor relevante ausente de la especificación, cuyo efecto se reparte entre los regresores incluidos y sesga sus coeficientes.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.LEFT] }),
    pieTabla('Glosario de términos empleados en este documento.'),
  ];
}

module.exports = { validacion, manual, programasNuevos, limitaciones, anexos };
