/* Capítulos 5 a 7: especificación, herramientas econométricas y escenarios. */
const U = require('./doc_parte1.js');
const {
  Paragraph, TextRun, AlignmentType, BorderStyle,
  AZUL, AMBAR, GRIS, FONDO, ANCHO_TABLA,
  p, neg, txt, cur, mono, h1, h2, h3, formula, nota, vinetas, numerada,
  tabla, figura, pieTabla, salto,
} = U;

function especificacion() {
  return [
    h1('5. Especificación del modelo'),
    h2('5.1 La ecuación de recursión'),
    p('El modelo es una cadena de Markov de cohortes con rezagos múltiples. La matrícula de un semestre en un estado dado se obtiene sumando los ingresantes declarados y los flujos que llegan desde los estados de semestres anteriores:'),
    ...formula([
      'M(T, s, c, m, k, u) = N(T, s, c, m, k, u)',
      '                    + Σ       Σ     M(T−L, s, c, m, k′, u′) · φ_L(k′,u′ → k,u)',
      '                     L=1..4  k′,u′',
      '',
      'con  φ_L(k′,u′ → k,u) = q_L(s, c, m, k′, p′) · A(k′→k | c, m, k′) · U(u′→u | s, m, k′)',
    ]),
    tabla([1500, 7526],
      ['Símbolo', 'Significado'],
      [
        ['M', 'Matrícula proyectada.'],
        ['N', 'Ingresantes declarados en el archivo de entrada, repartidos por turno según el apartado 6.7 y, si no se declara, por modalidad según el 6.8.'],
        ['T', 'Semestre académico de destino; p es su paridad (I o II).'],
        ['s, c, m', 'Sede, carrera y modalidad de estudios. Los tres se conservan a lo largo del flujo: no aparecen primados.'],
        ['k, u', 'Ciclo y turno. Las primas indican el estado de origen.'],
        ['L', 'Rezago en semestres entre la matrícula de origen y la de destino.'],
        ['q_L', 'Probabilidad de que la siguiente matrícula del estudiante ocurra exactamente L semestres después.'],
        ['A', 'Distribución del salto de ciclo entre quienes se rematriculan.'],
        ['U', 'Matriz de transición de turno.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.LEFT], mono: [0] }),
    pieTabla('Notación de la ecuación de recursión.'),
    p([txt('Las tres probabilidades condicionan en la modalidad, pero ninguna la '), cur('cambia'), txt(': la modalidad es un índice del estado, como la sede y la carrera. El apartado 5.4 justifica ese tratamiento.')]),
    ...figura('11_ecuacion.png', 'La ecuación y los parámetros del modelo, tal como los expone el propio HTML en su pestaña «Modelo y validación».', { maxAlto: 430 }),

    h2('5.2 Por qué «siguiente matrícula» y no «semestre siguiente»'),
    p([txt('La definición de q_L es deliberada y merece detenerse en ella. No es «¿está matriculado en T−L y también en T?», sino «¿es T la '), cur('siguiente'), txt(' matrícula de quien estaba en T−L?».')]),
    p('La diferencia importa para la corrección aritmética. Con la primera definición, un estudiante matriculado en tres semestres consecutivos sería contado dos veces al proyectar el tercero: una desde el primero con rezago 2 y otra desde el segundo con rezago 1. Con la definición adoptada, cada matrícula de origen genera como mucho una matrícula de destino —su siguiente aparición—, de modo que los sucesos son mutuamente excluyentes y la suma de probabilidades está acotada:'),
    ...formula([
      'q_1(s) + q_2(s) + q_3(s) + q_4(s) + q_no-vuelve(s) = 1',
    ]),
    p('El modelo queda así libre de doble conteo por construcción, no por ajuste posterior.'),

    h2('5.3 Censura por el borde de la ventana observada'),
    p('Un estudiante matriculado en 2026-I sólo puede observarse con rezago 1, porque 2026-II es el último semestre de la base. Incluirlo en el denominador de q₂, q₃ y q₄ sesgaría esas tasas a la baja de forma mecánica.'),
    p('El estimador controla esa censura: una matrícula de origen en el semestre t entra en el conjunto de riesgo del rezago L únicamente si t + L cae dentro de la ventana observada. El resultado es que q₂ se estima con seis semestres de origen, q₃ con cinco y q₄ con cuatro.'),

    h2('5.4 La modalidad de estudios como atributo conservado'),
    p('La modalidad plantea una pregunta de especificación que conviene resolver con los datos y no por analogía: ¿es un estado entre los que el estudiante transita, como el turno, o un atributo que lo acompaña, como la sede?'),
    p('La respuesta está en la matriz de transición observada sobre las 89 196 transiciones de la base:'),
    tabla([2226, 1700, 1700, 1700, 1700],
      ['Modalidad de origen', '→ A distancia', '→ Presencial', '→ Semi Pres.', 'Transiciones'],
      [
        ['A distancia', '99,35 %', '0,26 %', '0,39 %', '9 171'],
        ['Presencial', '0,21 %', '99,63 %', '0,17 %', '67 418'],
        ['Semi Presencial', '0,72 %', '0,76 %', '98,52 %', '12 607'],
      ]),
    pieTabla('Matriz de transición de modalidad entre matrículas consecutivas del mismo estudiante. La diagonal concentra el 99,44 % de los casos.'),
    p([txt('Con una diagonal del 99,44 % la respuesta es inequívoca: la modalidad se comporta como la sede (0 % de cambios) y como la carrera (0,43 %), no como el turno (21,5 % de cambios). El modelo la trata por tanto como '), neg('atributo fijo del estado'), txt(' y no estima matriz de transición para ella.')]),
    p('Esa decisión tiene dos consecuencias favorables. La primera es de parsimonia: se evitan seis parámetros libres por celda que los datos no justifican. La segunda es de contabilidad: al no haber flujo entre modalidades, la matrícula proyectada de cada modalidad se puede leer directamente, sin que dependa de una matriz de traspasos que introduciría error donde no lo hay.'),
    p('Lo que sí hace el modelo es condicionar en la modalidad las tres probabilidades de la recursión:'),
    ...vinetas([
      [neg('Continuación q_L. '), txt('La modalidad es el tercer nivel de la escalera de contracción, entre el ciclo y la carrera (apartado 6.2.3). La brecha de 29 puntos en el primer ciclo es demasiado grande para promediarla.')],
      [neg('Avance de ciclo A. '), txt('El estudiante a distancia avanza un ciclo con mayor frecuencia (90,4 %) y repite menos (5,1 %) que el presencial (84,5 % y 9,6 %).')],
      [neg('Transición de turno U. '), txt('Es la más marcada de las tres: dentro de la misma sede, un estudiante presencial de turno noche pasa a mañana en un 10,1 % de los casos, mientras que uno a distancia lo hace en un 0,1 %. Apartado 5.6.')],
    ]),
    nota('Restricción de oferta.', 'El modelo conoce las 83 combinaciones de sede, carrera y modalidad que realmente existen, de las 150 teóricas. Nunca genera matrícula fuera de ellas: no coloca estudiantes a distancia en Lima Norte, que no ofrece esa modalidad, ni en Enfermería, que sólo se imparte de forma presencial. El archivo de entrada puede ampliar la oferta declarando combinaciones nuevas.'),

    h2('5.5 Avance de ciclo'),
    p('Entre quienes se rematriculan, la distribución del salto de ciclo es marcadamente concentrada pero no degenerada:'),
    tabla([2400, 1300, 1300, 1300, 1300, 1426],
      ['Salto de ciclo', '−1 o menos', '0', '+1', '+2', '+3 o más'],
      [
        ['Probabilidad', '1,7 %', '8,5 %', '85,8 %', '3,1 %', '0,9 %'],
        ['Interpretación', 'Retrocede', 'Repite ciclo', 'Avanza normal', 'Adelanta', 'Convalida'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.CENTER, AlignmentType.CENTER, AlignmentType.CENTER, AlignmentType.CENTER] }),
    pieTabla('Distribución agregada del salto de ciclo entre continuadores.'),
    p('El 8,5 % que repite ciclo es el que hace que una proyección ingenua de «todos avanzan un ciclo» acumule error: al cabo de seis semestres desplaza la distribución de la matrícula por ciclos de forma apreciable.'),
    p('La distribución se estima por modalidad y ciclo, contraída hacia el perfil del ciclo, porque las tres modalidades avanzan a ritmos distintos:'),
    tabla([2226, 1360, 1360, 1360, 1360, 1360],
      ['Modalidad', 'Retrocede', 'Repite', 'Avanza +1', 'Adelanta +2', 'Convalida +3'],
      [
        ['A distancia', '1,4 %', '6,0 %', '89,2 %', '2,7 %', '0,7 %'],
        ['Presencial', '2,1 %', '9,1 %', '84,6 %', '3,1 %', '1,0 %'],
        ['Semi Presencial', '0,8 %', '5,9 %', '88,7 %', '3,9 %', '0,7 %'],
      ]),
    pieTabla('Distribución del salto de ciclo por modalidad tras la contracción, promediada sobre los ciclos 1 a 9. Las cifras del apartado 4.2, que agrupan los conteos observados de todos los ciclos, difieren ligeramente por esa doble razón.'),
    p('El ciclo de destino se acota al ciclo terminal del plan de la carrera. Un estudiante que estuviera en el ciclo 10 de un plan de diez ciclos y «avanzara» no puede aparecer en un ciclo 11 que no existe: permanece en el 10, que es lo que hace el rezagado real que aún arrastra cursos.'),

    h2('5.6 Transición de turno'),
    p('La matriz de transición de turno se estima por sede, modalidad y ciclo, contraída hacia la matriz de la sede. Estimarla por sede es imprescindible porque el catálogo de turnos difiere entre ambas; estimarla además por modalidad lo es porque el comportamiento dentro de una misma sede no se parece.'),
    tabla([2626, 1200, 1200, 1200, 1200, 1600],
      ['Sede · modalidad · turno de origen', '→ Diurno', '→ Mañana', '→ Noche', '→ Tarde', 'Obs. efectivas'],
      [
        ['L. Norte · Presencial · Diurno', '93,2 %', '—', '6,8 %', '—', '503'],
        ['L. Norte · Presencial · Noche', '11,1 %', '—', '88,9 %', '—', '239'],
        ['L. Norte · Semi Pres. · Noche', '—', '—', '100,0 %', '—', '110'],
        ['L. Sur · Presencial · Mañana', '—', '73,9 %', '19,8 %', '6,2 %', '8 643'],
        ['L. Sur · Presencial · Noche', '—', '10,1 %', '86,3 %', '3,6 %', '7 519'],
        ['L. Sur · Presencial · Tarde', '—', '35,2 %', '49,0 %', '15,8 %', '1 117'],
        ['L. Sur · Semi Pres. · Noche', '—', '0,6 %', '91,1 %', '8,3 %', '3 209'],
        ['L. Sur · Semi Pres. · Tarde', '—', '1,7 %', '71,1 %', '27,1 %', '362'],
        ['L. Sur · A distancia · Noche', '—', '0,1 %', '93,7 %', '6,2 %', '3 148'],
        ['L. Sur · A distancia · Tarde', '—', '0,2 %', '87,6 %', '12,1 %', '170'],
      ], { tam: 17 }),
    pieTabla('Matriz de transición de turno por sede, modalidad y turno de origen, ponderada por recencia. Las observaciones son el tamaño muestral efectivo tras la ponderación; se omiten las combinaciones con menos de 50.'),
    p([txt('La comparación que justifica la especificación está en las filas de Lima Sur con turno noche de origen. Un estudiante '), neg('presencial'), txt(' pasa al turno mañana en un 10,1 % de los casos; uno '), neg('semipresencial'), txt(', en un 0,6 %; uno '), neg('a distancia'), txt(', en un 0,1 %. Misma sede, mismo turno de partida, comportamientos que difieren en dos órdenes de magnitud. Una matriz estimada sólo por sede promediaría los tres y devolvería un flujo hacia el turno mañana que no le corresponde a dos de las tres poblaciones.')]),
    p('Dos lecturas más conviene destacar. El turno noche es muy estable en todas las modalidades —entre el 86 % y el 94 % permanece—, mientras que el turno tarde es el más inestable: en la modalidad presencial sólo un 15,8 % permanece y la mayoría migra a mañana o noche. Es coherente con un turno en retirada, como confirma la caída de su participación entre los ingresantes.'),

    h2('5.7 Maduración de sede'),
    p('Una sede que acaba de abrir no puede tener estudiantes en cualquier ciclo: despliega su plan de estudios semestre a semestre. En el semestre de apertura sólo existe el ciclo 1; un semestre después, el 2; y así sucesivamente hasta completar el plan.'),
    p('El modelo impone ese tope como una restricción dura sobre el ciclo de destino, en paralelo al tope por duración del plan de la carrera:'),
    ...formula([
      'ciclo_destino = min( ciclo_origen + Δ ,  ciclos_plan(carrera) ,  tope_sede(s, T) )',
      '',
      'tope_sede(s, T) = max( 0 ,  ciclo_base(s) + semestres_transcurridos(s, T) )',
      '',
      '  ciclo_base(s)  ciclo máximo de la sede en su semestre de apertura',
      '  semestres_transcurridos  distancia entre la apertura y el semestre T',
    ]),
    p('La restricción actúa en dos puntos. Sobre los continuadores, porque la matriz de avance permite saltos de +2 y +3 que llevarían a un estudiante a un ciclo inexistente. Y sobre los ingresantes, porque el archivo de entrada puede declarar traslados a ciclos superiores que la sede todavía no imparte; en ese caso el modelo lo avisa fila por fila y los reasigna al ciclo máximo disponible.'),

    h3('5.7.1 Cómo se detecta la apertura'),
    p('La apertura no se declara a mano: se infiere del propio histórico. Si el ciclo máximo del primer semestre observado de una sede es 1 o 2, la sede arrancó ahí. Si aparece con el plan completo desde su primer registro, es anterior a la ventana de datos y no recibe tope.'),
    tabla([2000, 1700, 1500, 3826],
      ['Sede', 'Primer registro', 'Ciclo máx.', 'Conclusión'],
      [
        ['Lima Norte', '2026-I', '1', 'Abrió en 2026-I: despliegue progresivo.'],
        ['Lima Sur', '2023-I', '11', 'Plan completo desde el inicio de la base: sin tope.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Detección automática de la apertura de sede sobre el histórico.'),
    p('Una sede que aparece por primera vez en el archivo de ingresantes se trata como una apertura en ese semestre, con el mismo mecanismo. No hace falta declararla ni configurar nada.'),
    tabla([1900, 1150, 1150, 1150, 1150, 1150, 1376],
      ['Sede', '2027-I', '2027-II', '2028-I', '2028-II', '2029-I', '2029-II'],
      [
        ['Lima Norte (abrió 2026-I)', '3', '4', '5', '6', '7', '8'],
        ['Lima Sur (consolidada)', 'sin tope', 'sin tope', 'sin tope', 'sin tope', 'sin tope', 'sin tope'],
        ['Sede nueva que abra en 2028-I', 'no opera', 'no opera', '1', '2', '3', '4'],
      ]),
    pieTabla('Ciclo máximo ofertable por sede y semestre. La tercera fila es un ejemplo de sede declarada en el archivo de ingresantes.'),
    ...figura('11b_maduracion.png', 'La restricción de maduración tal como la expone el modelo, con la apertura detectada de cada sede y su ciclo máximo por semestre.', { maxAlto: 330 }),
    nota('Qué ocurre en el tope.', 'Un estudiante que no puede avanzar porque la sede aún no imparte el siguiente ciclo se acumula en el ciclo máximo disponible, igual que el rezagado que arrastra cursos al final de su plan. Es el mismo tratamiento que recibe el tope por duración de la carrera y mantiene la contabilidad cerrada: ningún estudiante se pierde ni se duplica.'),

    h2('5.8 Lo que el modelo no mueve'),
    p('Tres dimensiones se mantienen constantes a lo largo de la proyección porque los datos así lo indican:'),
    ...vinetas([
      [neg('Sede. '), txt('Ningún estudiante del histórico cambia de sede. Se conserva.')],
      [neg('Carrera. '), txt('El 99,57 % de los continuadores mantiene su carrera. El 0,43 % restante se reparte sin patrón discernible y modelarlo añadiría parámetros sin ganancia predictiva.')],
      [neg('Modalidad de estudios. '), txt('El 99,44 % de los continuadores mantiene su modalidad. Se conserva, y en cambio condiciona las tres probabilidades de transición (apartado 5.4).')],
    ]),
    p('El ciclo y el turno sí se mueven, y son los únicos dos índices del estado que llevan matriz de transición estimada. Esa asimetría no es una simplificación de conveniencia: es lo que dicen las 89 196 transiciones observadas.'),
    salto(),
  ];
}

function herramientas() {
  return [
    h1('6. Herramientas econométricas aplicadas'),
    p('Este capítulo detalla los instrumentos estadísticos empleados, por qué se eligieron y cómo se implementan. Es el núcleo del sustento metodológico.'),

    h2('6.1 El problema de fondo: muchas celdas, pocos datos por celda'),
    p('El estado del modelo es (sede, carrera, modalidad, ciclo, turno): 2 × 25 × 3 × 11 × 4 = 6 600 combinaciones teóricas, y cada una necesita sus probabilidades de transición condicionadas además a la paridad del semestre y al rezago. Frente a eso hay ocho semestres de historia.'),
    p('La restricción de oferta reduce el problema —sólo existen 83 combinaciones de sede, carrera y modalidad, no 150— pero no lo elimina: en 2026-II hay 699 celdas completas no vacías y la mediana tiene menos de diez estudiantes.'),
    p('Estimar cada celda por separado con su propia frecuencia produciría tasas inestables: una celda con siete estudiantes de los que continúan cinco daría una tasa del 71,4 % con un error típico de ±17 puntos. Agregarlo todo y usar una tasa única, en el otro extremo, perdería la estructura por ciclo y por modalidad que el capítulo 4 mostró decisiva.'),
    p('La solución empleada es la contracción jerárquica: cada celda combina su propia evidencia con la de un nivel más agregado, en proporción a cuánta información tiene realmente.'),

    h2('6.2 Contracción empírico-Bayes con modelo Beta-Binomial'),
    h3('6.2.1 El estimador'),
    p('Para una tasa de continuación, la estimación de una celda es:'),
    ...formula([
      '            k_celda + k · q_padre',
      'q_celda =  ───────────────────────',
      '            n_celda + k',
      '',
      '   n_celda  observaciones de la celda (ponderadas por recencia)',
      '   k_celda  de ellas, las que continúan',
      '   q_padre  estimación del nivel inmediatamente superior',
      '   k        constante de contracción',
    ]),
    p([txt('La constante '), mono('k'), txt(' es el tamaño muestral equivalente del prior: la celda pondera su propia evidencia con peso n/(n+k) y la del padre con peso k/(n+k). Una celda con muchas observaciones se estima casi sola; una con pocas hereda casi todo del nivel superior. La transición entre ambos regímenes es suave y automática.')]),

    h3('6.2.2 Cómo se obtiene k, y por qué no se elige a mano'),
    p([txt('La constante se estima por el '), neg('método de los momentos del modelo Beta-Binomial'), txt('. Si las tasas verdaderas de las celdas siguen una distribución Beta(α, β), su varianza entre celdas es una función de α+β, y despejando:')]),
    ...formula([
      '        p̄ (1 − p̄)',
      'k  =  ───────────── − 1        con  k = α + β',
      '         σ²_entre',
      '',
      'σ²_entre = σ²_observada − σ²_muestral',
      'σ²_muestral = Σ w_i · p̄(1−p̄)/n_i      (ruido binomial esperado)',
    ]),
    p('La lógica es directa: se mide cuánto varían las tasas entre celdas, se descuenta lo que se explicaría por puro azar muestral, y lo que sobra es heterogeneidad real. Mucha heterogeneidad real implica k pequeña —las celdas son genuinamente distintas y conviene creerles—; poca heterogeneidad implica k grande y contracción fuerte hacia el padre.'),
    p('Es importante que k no sea un parámetro de ajuste elegido por el analista: sale de los propios datos, y su valor es interpretable y auditable.'),

    h3('6.2.3 La escalera de niveles'),
    p('La contracción se aplica en cadena, del nivel más agregado al más fino. Cada nivel sirve de prior al siguiente:'),
    ...formula([
      'global  →  ciclo  →  ciclo × paridad  →  modalidad × ciclo × paridad',
      '        →  carrera × modalidad × ciclo × paridad',
      '        →  sede × carrera × modalidad × ciclo × paridad',
    ]),
    p([txt('La modalidad se inserta '), neg('entre el ciclo y la carrera'), txt(', y esa posición es una decisión con contenido: dice que, para predecir si un estudiante continúa, saber en qué modalidad estudia informa más que saber qué carrera cursa. Las constantes estimadas lo confirman —la k de la modalidad (4,76) es menor que la del ciclo (5,80) y mayor que la de la carrera (4,08)—, y así lo corrobora el contraste de especificación del apartado 6.5.')]),
    tabla([3500, 1400, 4126],
      ['Parámetro', 'k estimada', 'Lectura'],
      [
        ['Continuación · nivel celda (rezago 1)', '4,07', 'Heterogeneidad alta entre sedes: se cree bastante a cada celda.'],
        ['Continuación · nivel carrera (rezago 1)', '4,08', 'Las carreras difieren realmente entre sí dentro de cada modalidad y ciclo.'],
        ['Continuación · nivel modalidad (rezago 1)', '4,76', 'Heterogeneidad alta: las tres modalidades son poblaciones distintas.'],
        ['Continuación · nivel ciclo×paridad', '5,72', 'El efecto de la paridad es real pero moderado.'],
        ['Continuación · nivel ciclo', '5,80', 'El perfil por ciclo es la estructura dominante.'],
        ['Continuación · rezagos 2 a 4', '1 000 a 10 000', 'Apenas se detecta heterogeneidad: el reingreso tras pausa se comporta de forma parecida en todas las celdas y se estima muy agrupado.'],
        ['Avance de ciclo', '5,25', 'El patrón de avance varía apreciablemente entre modalidades y carreras.'],
        ['Transición de turno', '1,00 (mínimo)', 'Heterogeneidad muy alta por sede, modalidad y ciclo: apenas se contrae.'],
        ['Reparto de turno de ingresantes', '1,00 (mínimo)', 'Ídem: una vez condicionado en la modalidad, cada celda tiene su propio patrón.'],
        ['Reparto de modalidad de ingresantes', '1,78', 'Contracción ligera hacia el nivel de sede y carrera.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Constantes de contracción estimadas por el método de los momentos.'),
    nota('Resultado interpretable.', 'Que las constantes de los rezagos 2 a 4 se disparen es un hallazgo, no un fallo: el estimador está diciendo que el reingreso tras una pausa apenas depende de la carrera o la modalidad, y que conviene estimarlo con la muestra muy agrupada. Que la del turno caiga al mínimo dice lo contrario: cada combinación de sede, modalidad y ciclo tiene su propio patrón y hay datos suficientes para estimarlo. Nótese que la del reparto de turno de los ingresantes bajó de 5,42 a 1,00 al incorporar la modalidad: antes la heterogeneidad entre celdas parecía pequeña porque se mezclaban poblaciones distintas; separadas, cada una tiene una señal clara que conviene respetar.'),

    h2('6.3 Contracción Dirichlet-Multinomial para composiciones'),
    p('El avance de ciclo, la transición de turno y el reparto de los ingresantes por turno y por modalidad no son tasas sino composiciones: vectores de probabilidades que suman uno. La extensión natural del Beta-Binomial es el modelo Dirichlet-Multinomial:'),
    ...formula([
      '              c_j + k · π_j(padre)',
      'π_j(celda) = ──────────────────────        para cada categoría j',
      '                 Σ c + k',
    ]),
    p('La constante k se estima con el mismo método de los momentos aplicado a la categoría de mayor masa, que es la que gobierna la variabilidad del conjunto. El resultado se renormaliza para garantizar que la composición suma exactamente uno.'),

    h2('6.4 Modelo lineal generalizado para descomponer la varianza'),
    p('Para separar las fuentes de variación de la tasa de continuación se ajusta un GLM binomial con enlace logit sobre las 109 799 transiciones con semestre de destino observable:'),
    ...formula([
      'logit P(continúa) = μ + α_ciclo + β_modalidad + γ_semestre',
    ]),
    p('La paridad no entra como regresor independiente: está anidada en el semestre y su inclusión produciría un diseño de rango deficiente. Se extrae después proyectando los efectos de semestre estimados sobre la paridad, y el residuo de esa proyección es el choque estocástico.'),
    p([txt('La modalidad entra como '), neg('control'), txt(', y es la novedad de esta especificación. La razón es de libro de texto: si una variable afecta a la probabilidad de continuar y su composición cambia con el tiempo, omitirla hace que su deriva se contabilice en los efectos de periodo. El choque de periodo así medido no sería volatilidad, sino cambio de composición mal atribuido.')]),
    tabla([3600, 1800, 3626],
      ['Estadístico', 'Valor', 'Lectura'],
      [
        ['Observaciones', '109 799', 'Transiciones con destino observable.'],
        ['Devianza residual', '98 447', 'Sobre 109 780 grados de libertad.'],
        ['Pseudo-R² (McFadden)', '0,1453', 'Habitual en modelos de elección individual: el comportamiento de una persona concreta es en gran medida idiosincrásico. Sin modalidad era 0,1345.'],
        ['β Presencial (base: a distancia)', '+0,770', 'Error típico 0,022; z = 35,3; p ≈ 4·10⁻²⁷³.'],
        ['β Semi Presencial', '+0,480', 'Error típico 0,028; z = 17,4; p ≈ 1·10⁻⁶⁷.'],
        ['χ² del bloque de modalidad', '1 235,5', '2 g.l.; p ≈ 5·10⁻²⁶⁹.'],
        ['χ² del bloque de semestre', '65,94', '6 g.l.; p ≈ 2,8·10⁻¹².'],
        ['σ de los efectos de semestre', '0,0709', 'En escala logit, antes de descontar estacionalidad.'],
        ['σ del choque estocástico', '0,0679', 'Tras descontar estacionalidad; 5 g.l.'],
        ['Efecto estacional', '±0,0326', 'Semestre I frente a semestre II, en logit.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Resultados del GLM auxiliar de descomposición de varianza.'),
    p([txt('El pseudo-R² moderado es esperable y no invalida el uso: el modelo auxiliar no pretende predecir si '), cur('un'), txt(' estudiante concreto continuará, sino cuantificar cuánto se mueve la tasa '), cur('media'), txt(' entre semestres una vez controlados el ciclo y la modalidad. Para ese fin, lo relevante es la significación de los bloques, que es contundente en ambos.')]),

    h3('6.4.1 Cuánto cambia la descomposición al controlar la modalidad'),
    p('El efecto del control es grande y va todo en la misma dirección. Ajustando el mismo GLM sobre los mismos datos, con y sin el bloque de modalidad:'),
    tabla([3300, 1900, 1900, 1926],
      ['Componente', 'Sin modalidad', 'Con modalidad', 'Variación'],
      [
        ['σ del choque de periodo', '0,1026', '0,0679', '−33,8 %'],
        ['Efecto estacional (logit)', '±0,0511', '±0,0326', '−36,2 %'],
        ['χ² del bloque de semestre', '152,7', '65,9', '−56,8 %'],
        ['Pseudo-R² de McFadden', '0,1345', '0,1453', '+8,0 %'],
      ]),
    pieTabla('Descomposición de la varianza con y sin el control de modalidad. Ambos ajustes emplean las mismas 109 799 transiciones.'),
    p([txt('La lectura es directa: '), neg('un tercio de lo que se medía como choque de periodo era deriva de composición por modalidad'), txt('. El χ² del bloque de semestre cae a menos de la mitad porque buena parte de lo que capturaba no era un movimiento del entorno, sino el peso creciente de una población con menor retención.')]),
    p('La consecuencia práctica es que los escenarios se estrechan: el desplazamiento sistémico que los gradúa pasa de ±0,151 a ±0,100 en escala logit. No es un ajuste discrecional de la amplitud, sino la traducción de haber convertido incertidumbre en estructura.'),
    p('Descomponiendo la varianza de la tasa agregada entre semestres:'),
    tabla([3600, 2200, 3226],
      ['Componente', 'Varianza', 'Participación'],
      [
        ['Observada entre semestres', '2,690·10⁻⁴', '100,0 %'],
        ['Atribuible al muestreo', '0,111·10⁻⁴', '4,1 %'],
        ['Atribuible al proceso', '2,579·10⁻⁴', '95,9 %'],
      ]),
    pieTabla('Descomposición de la varianza de la tasa agregada de continuación. El componente de proceso incluye tanto la parte predecible —estacionalidad y composición— como el choque genuino; sólo este último alimenta los escenarios.'),
    ...figura('14_incertidumbre.png', 'La descomposición de la incertidumbre, tal como la presenta el modelo.', { maxAlto: 470 }),

    h2('6.5 Contraste de especificación: qué aporta la dimensión modalidad'),
    p('El GLM auxiliar dice que la modalidad es significativa, pero eso no basta: la significación estadística no garantiza ganancia predictiva. La pregunta relevante es si el modelo completo proyecta mejor con esa dimensión que sin ella.'),
    p('Para responderla se ejecutó una ablación: el mismo procedimiento de principio a fin sobre la misma base histórica, con la única diferencia de colapsar la modalidad a una categoría única en la segunda especificación. En ambos casos la ponderación de recencia se selecciona por validación cruzada dentro de la propia especificación, de modo que se comparan dos procedimientos completos y no dos conjuntos de parámetros.'),
    tabla([2400, 1900, 1900, 1500, 1326],
      ['Nivel de agregación', 'Sin modalidad', 'Con modalidad', 'Reducción', 'Celdas'],
      [
        ['Total institucional', '1,992 %', '1,649 %', '17,2 %', '1'],
        ['Sede', '2,304 %', '1,649 %', '28,4 %', '2'],
        ['Carrera', '3,173 %', '2,757 %', '13,1 %', '25'],
        ['Sede × carrera', '3,467 %', '2,904 %', '16,2 %', '42'],
        { __sub: 'Otros resultados del contraste' },
        ['Sesgo medio del total', '+259', '+153', '—', '—'],
        ['λ elegida por validación cruzada', '0,30 (borde)', '0,55 (interior)', '—', '—'],
      ]),
    pieTabla('Ablación de la dimensión modalidad. EPAP medio fuera de muestra en los cuatro niveles de agregación que existen en ambas especificaciones; los niveles más finos no son comparables porque añadir la dimensión parte las celdas. La λ que aparece aquí se elige sobre estos cuatro niveles; el valor de producción, 0,65, se elige sobre la rejilla completa del apartado 6.6.'),
    p('El error baja en los cuatro niveles comparables, entre un 13 % y un 28 %, y el sesgo medio del total se reduce en un 41 %. Pero el resultado más informativo es el de la última fila.'),
    nota('La recencia estaba haciendo de variable omitida.', 'Sin la dimensión de modalidad, la validación cruzada empuja λ hasta 0,30, el borde de la rejilla: el estimador pide olvidar el pasado lo más deprisa posible. Tiene sentido, porque es la única forma que tiene de seguir una composición que cambia sin poder verla. Al incorporar la modalidad, el óptimo se vuelve interior: ya no hace falta tirar información antigua para capturar la deriva, porque la deriva está explícitamente modelada. Un óptimo interior es una señal de especificación sana; un óptimo en el borde de la rejilla es una señal de que falta algo.'),
    p('Conviene ser explícito sobre el alcance de este contraste: se apoya en los mismos tres orígenes y seis comparaciones que el resto de la validación, de modo que la magnitud exacta de la mejora tiene un margen amplio. Lo que sí es robusto es el signo —la mejora aparece en los cuatro niveles y en el sesgo— y el desplazamiento del óptimo de λ, que no depende de cuántas comparaciones haya.'),

    h2('6.6 Ponderación exponencial de recencia'),
    h3('6.6.1 El problema'),
    p('El capítulo 4 documentó dos derivas estructurales: la retención cae en los semestres recientes y la composición por turno de los ingresantes se ha desplazado hacia el turno noche. Ponderar los ocho semestres por igual arrastra información caducada.'),
    p('El estimador aplica por tanto un peso exponencial a cada observación según su antigüedad:'),
    ...formula([
      'w(t) = λ^(t_último − t)          con 0 < λ ≤ 1',
      '',
      'λ = 1    todo el histórico pesa igual',
      'λ < 1    los semestres recientes pesan más; la semivida es log(0,5)/log(λ)',
    ]),

    h3('6.6.2 La elección de λ por validación cruzada'),
    p('El valor de λ no se fijó por criterio. Se recorrió una rejilla de valores y para cada uno se ejecutó el backtesting completo de origen móvil, midiendo el error fuera de muestra en todos los niveles de agregación.'),
    tabla([980, 1230, 1230, 1230, 1230, 1230, 1896],
      ['λ', 'Total', 'Sede×Carr.', '×Modalidad', '×Ciclo', 'Criterio', 'Sesgo'],
      [
        ['1,00', '1,662 %', '3,080 %', '3,660 %', '12,830 %', '101,56', '+225'],
        ['0,85', '1,670 %', '3,023 %', '3,614 %', '12,859 %', '101,19', '+203'],
        ['0,80', '1,666 %', '3,003 %', '3,606 %', '12,878 %', '101,02', '+195'],
        ['0,70', '1,659 %', '2,963 %', '3,593 %', '12,938 %', '100,79', '+176'],
        ['0,65', '1,651 %', '2,934 %', '3,586 %', '12,979 %', '100,56', '+165'],
        ['0,60', '1,650 %', '2,914 %', '3,585 %', '13,025 %', '100,58', '+159'],
        ['0,55', '1,649 %', '2,904 %', '3,585 %', '13,072 %', '100,69', '+153'],
        ['0,50', '1,654 %', '2,899 %', '3,588 %', '13,129 %', '100,99', '+149'],
        ['0,40', '1,663 %', '2,900 %', '3,598 %', '13,263 %', '101,65', '+142'],
        ['0,30', '1,684 %', '2,919 %', '3,624 %', '13,417 %', '102,79', '+139'],
      ]),
    pieTabla('Selección de λ. El criterio es la media de las seis series de EPAP indexadas cada una a su propio mínimo (100 = la mejor λ de ese nivel); se indexa porque el error del cruce más fino es veinte veces mayor que el del total y dominaría cualquier media directa. El mínimo es interior y se alcanza en λ = 0,65.'),
    p([txt('El criterio combinado tiene un '), neg('mínimo interior'), txt(' en λ = 0,65, y la curva es plana en el intervalo [0,55; 0,70]. Que el óptimo no esté en el borde de la rejilla es lo que distingue una elección fundamentada de un ajuste forzado: existe un compromiso real entre usar información reciente —que reduce el error de los agregados— y disponer de muestra suficiente en las celdas finas, cuyo error crece de forma monótona a medida que λ baja.')]),
    ...figura('16_lambda.png', 'Curva de selección de λ dentro del propio modelo, con cada serie indexada a su mínimo para poder compararlas en un solo eje.', { maxAlto: 330 }),
    p('Para el reparto por turno de los ingresantes se repitió el ejercicio por separado, midiendo el error en el nivel que incluye el turno. La curva desciende hasta λ ≈ 0,30 y se aplana después: la ganancia entre 0,30 y 0,05 es de apenas 0,11 puntos porcentuales. Se fijó λ = 0,30, ya que ir más lejos equivaldría a usar un único semestre sin ganancia medible y con riesgo de arrastrar cualquier anomalía puntual.'),
    nota('Qué significa λ = 0,65.', 'La semivida es de 1,6 semestres: el semestre anterior pesa un 65 %, dos semestres atrás un 42 %, cuatro atrás un 18 %. El modelo mira sobre todo los tres o cuatro semestres más recientes. Es una ventana más larga que la de la revisión anterior del modelo, que operaba con λ = 0,50, y el motivo es el del apartado 6.5: parte de la deriva que antes obligaba a olvidar deprisa ahora está explícitamente modelada como composición por modalidad. Al ver la deriva, el modelo puede permitirse recordar más.'),

    h2('6.7 Estimación matemática del reparto de los ingresantes por turno'),
    p('El archivo de entrada declara los ingresantes por semestre, sede, carrera, modalidad y ciclo, pero no por turno. El modelo estima ese reparto con una composición multinomial contraída en cascada:'),
    ...formula([
      'global → sede → sede × modalidad → sede × modalidad × paridad',
      '       → carrera × modalidad → carrera × modalidad × paridad',
      '       → celda completa',
    ]),
    p('El recorrido se detiene en el nivel más fino que disponga de evidencia. Una carrera consolidada llega hasta la celda completa; una carrera nueva, sin historia propia, se queda en el nivel de sede y modalidad y hereda su reparto. No hay regla especial para los programas nuevos: es el mismo mecanismo de contracción resolviendo un caso extremo.'),
    p([txt('La modalidad entra pronto en la cascada —antes que la carrera— porque es, con diferencia, el mejor predictor del turno de un ingresante: las modalidades semipresencial y a distancia son nocturnas en más del 98 % de los casos, mientras que la presencial reparte entre mañana, noche y, en Lima Norte, diurno. El apartado 4.5.1 cuantifica ese efecto de composición.')]),
    p('El modelo informa del nivel alcanzado en cada fila, de modo que siempre puede saberse de dónde procede una estimación concreta.'),
    ...figura('10_ingresantes_turno.png', 'Reparto estimado por turno de los ingresantes. La columna «Nivel usado» indica hasta dónde llegó la evidencia; las filas de INTELIGENCIA ARTIFICIAL corresponden a un programa nuevo de prueba.', { maxAlto: 540 }),

    h2('6.8 Estimación de la modalidad cuando no se declara'),
    p('La plantilla de entrada incluye una columna de modalidad y conviene rellenarla, porque es información que el área de admisión conoce y el modelo no puede deducir. Pero el modelo admite que falte, por dos razones prácticas: para dar continuidad a archivos preparados con la versión anterior de la plantilla, y porque en fases tempranas de planificación la modalidad de una campaña puede no estar decidida.'),
    p('Cuando una fila no declara modalidad, el modelo la reparte con la composición histórica de esa sede y esa carrera, contraída en cascada por el mismo procedimiento Dirichlet-Multinomial del apartado 6.3:'),
    ...formula([
      'global → sede → sede × paridad → sede × carrera',
      '       → sede × carrera × paridad',
      '',
      'restringido a las combinaciones (sede, carrera, modalidad) que existen',
    ]),
    p('La restricción de oferta es la pieza que hace útil el mecanismo. Sin ella, el reparto medio institucional colocaría un 19,6 % de estudiantes a distancia en Lima Norte, que no ofrece esa modalidad, o en Enfermería, que sólo se imparte de forma presencial. Con ella, esas filas se resuelven con un 100 % presencial, que es lo correcto.'),
    ...figura('09b_modalidad_nuevos.png', 'Reparto estimado por modalidad de un archivo de entrada que no la declara. Obsérvese que las filas de Lima Norte y las de Enfermería y Farmacia se resuelven con un 100 % presencial: la restricción de oferta actúa antes que la composición histórica.', { maxAlto: 480 }),
    p('La estimación se recalcula al mover λ, igual que el resto de los parámetros: no es un reparto congelado en el archivo, sino el resultado de aplicar el mismo estimador a los conteos históricos con la ponderación vigente.'),
    nota('Cuándo importa declararla.', 'La diferencia no es cosmética. Un grupo de 300 ingresantes de primer ciclo declarados como presenciales aporta unos 212 continuadores al semestre siguiente; declarados a distancia, unos 125. Sobre una campaña completa, la diferencia entre declarar la modalidad y dejar que el modelo la estime puede ser de varios centenares de estudiantes en el horizonte de proyección. El modelo avisa en pantalla de cuántas filas ha tenido que estimar.'),

    h2('6.9 Propagación de la varianza por el método delta'),
    p('Cada celda proyectada acumula tres fuentes de incertidumbre independiente, que se propagan a lo largo de la recursión:'),
    ...formula([
      'V(destino) = Σ [  x · φ · (1 − φ)                    realización multinomial',
      '                + x² · φ² · ( (1−q)/(q·n_q)',
      '                            + (1−A)/(A·n_A)',
      '                            + (1−U)/(U·n_U) )        error de parámetro',
      '                + φ² · V(origen)              ]      varianza propagada',
    ]),
    ...vinetas([
      [neg('Realización multinomial. '), txt('Aunque las probabilidades fueran exactas, el reparto concreto de x estudiantes entre destinos es aleatorio. Es el término que domina en las celdas pequeñas.')],
      [neg('Error de parámetro. '), txt('Las probabilidades se estiman con muestra finita. Se aplica el método delta al producto de las tres probabilidades, usando el tamaño muestral efectivo tras la contracción.')],
      [neg('Varianza propagada. '), txt('La incertidumbre del stock de origen se arrastra a la de destino, multiplicada por el cuadrado de la probabilidad de transición.')],
    ]),
    p('Estos componentes son independientes entre celdas, de modo que al agregar se suman en cuadratura y se diluyen: por eso el intervalo relativo del total institucional es estrecho y el de una celda individual es ancho. Es el comportamiento correcto y el que la validación confirma.'),
    salto(),
  ];
}

function escenarios() {
  return [
    h1('7. Los tres escenarios'),
    h2('7.1 Qué debe ser un escenario'),
    p('Un escenario de planificación tiene que cumplir dos condiciones que un intervalo de confianza corriente no cumple.'),
    ...numerada([
      [neg('Coherencia. '), txt('Debe describir un estado del mundo posible y completo. Si la retención cae, cae para todas las cohortes a la vez, no de forma independiente en cada celda.')],
      [neg('Aditividad. '), txt('El total del escenario tiene que ser la suma de sus celdas. Si el escenario pesimista del total no coincide con la suma de los escenarios pesimistas por carrera o por modalidad, la cifra no sirve para repartir aulas ni presupuesto.')],
    ]),
    p('Ambas condiciones se satisfacen si —y sólo si— el escenario se construye sobre el componente sistémico de la incertidumbre, aquel que mueve todas las celdas en el mismo sentido.'),

    h2('7.2 Construcción'),
    p('Los tres escenarios aplican un desplazamiento común en escala logit a todas las tasas de continuación:'),
    ...formula([
      'logit q_L(escenario) = logit q_L(central) ± z · σ',
      '',
      'σ = 0,0679   desviación típica del choque de periodo (5 g.l.)',
      'z = 1,476    cuantil t de Student para una confianza del 80 %',
      '',
      'Optimista   +z·σ = +0,100 en logit',
      'Moderado     0',
      'Pesimista   −z·σ = −0,100 en logit',
    ]),
    p('Aplicar el desplazamiento en escala logit y no en la tasa directa tiene dos ventajas: la tasa resultante nunca se sale del intervalo [0, 1], y el efecto es proporcionalmente mayor donde la tasa es intermedia y menor donde ya está cerca de sus extremos, que es como se comportan los choques reales.'),
    p([txt('Ese segundo rasgo cobra sentido añadido con la modalidad en el modelo. La continuación del primer ciclo a distancia (41,6 %) está en la zona de máxima sensibilidad del logit, mientras que la de un ciclo 7 presencial (90,8 %) está cerca del techo. Un choque sistémico de la misma magnitud en logit mueve 2,4 puntos porcentuales a la primera y sólo 0,8 a la segunda. Eso es exactamente lo que se quiere: el escenario pesimista castiga más donde la población es más frágil, sin que haya que programarlo.')]),
    p([txt('Se emplea el cuantil t de Student y no el normal porque σ se estima con sólo 5 grados de libertad: siete semestres de origen menos el parámetro estacional y la media. Con tan pocas observaciones, la distribución normal subestimaría la incertidumbre. Para una confianza del 80 %, z pasa de 1,282 (normal) a 1,476 (t con 5 g.l.), un 15 % más ancho.')]),
    nota('Por qué sólo la continuación.', 'El choque no se aplica a los ingresantes: su número lo fija el archivo de entrada y es un supuesto del usuario, no una estimación del modelo. Un escenario que alterase también el ingreso —o su reparto por modalidad— mezclaría la incertidumbre del comportamiento estudiantil con una decisión institucional, y el usuario no podría saber cuál de las dos está viendo.'),

    h2('7.3 Escenario frente a intervalo de predicción'),
    p('El modelo entrega ambas magnitudes, y conviene no confundirlas. La diferencia es visible en los datos de validación:'),
    tabla([3400, 2700, 2926],
      ['Nivel de agregación', 'Cobertura de la banda de escenarios', 'Cobertura del intervalo de predicción'],
      [
        ['Total institucional', '77,8 %', '88,9 %'],
        ['Modalidad', '66,7 %', '96,3 %'],
        ['Carrera', '33,3 %', '95,3 %'],
        ['Sede × carrera', '36,1 %', '93,4 %'],
        ['Sede × carrera × modalidad', '34,8 %', '96,2 %'],
        ['… × ciclo', '8,8 %', '85,4 %'],
        ['… × turno', '2,9 %', '81,2 %'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.CENTER] }),
    pieTabla('Cobertura empírica media sobre los tres horizontes, para un nivel nominal del 80 %. La banda de escenarios no pretende cubrir el dato observado; el intervalo de predicción sí.'),
    p('La banda de escenarios cubre mucho menos del 80 % en cuanto se desagrega, y eso es correcto: no es un intervalo de predicción. Recoge únicamente el desplazamiento sistémico y deja fuera, por diseño, el azar de realización de cada celda. Leerla como si fuese un intervalo de confianza llevaría a subestimar el riesgo, sobre todo en el detalle fino.'),
    p('El intervalo de predicción suma ambos componentes y sí está calibrado:'),
    ...formula([
      'semiamplitud(A) = z · √( D_A²  +  V_A )',
      '',
      '  D_A  sensibilidad sistémica del agregado A a un choque de un σ.',
      '       Común a todas las celdas → al agregar se suma LINEALMENTE.',
      '  V_A  varianza independiente acumulada (apartado 6.9).',
      '       Al agregar se suma en CUADRATURA → se diluye en los totales',
      '       y domina en las celdas pequeñas.',
    ]),
    p('La distinta álgebra de agregación de los dos términos es la razón por la que el intervalo relativo del total es estrecho y el de una celda con cinco estudiantes es muy ancho, sin que haga falta ningún tratamiento especial para cada nivel.'),

    h2('7.4 Calibración del factor de inflación'),
    p('Queda por comprobar si esa aritmética reproduce la dispersión realmente observada. Para ello se introdujo un factor de inflación κ sobre el componente independiente y se buscó el valor que iguala la cobertura empírica a la nominal.'),
    tabla([880, 1180, 1180, 1180, 1180, 1610, 1816],
      ['κ', 'Total', 'Modalidad', 'Carrera', 'Sede×Carr.', '×Modalidad', '… × turno'],
      [
        ['1,0', '83,3 %', '94,4 %', '94,6 %', '93,7 %', '95,8 %', '79,8 %'],
        ['1,5', '83,3 %', '94,4 %', '98,7 %', '99,6 %', '99,8 %', '89,0 %'],
        ['2,0', '83,3 %', '100,0 %', '100,0 %', '100,0 %', '100,0 %', '93,0 %'],
        ['3,0', '100,0 %', '100,0 %', '100,0 %', '100,0 %', '100,0 %', '96,3 %'],
      ]),
    pieTabla('Cobertura empírica media según el factor de inflación de varianza, para un nivel nominal del 80 %.'),
    p([txt('El valor seleccionado es '), neg('κ = 1,0'), txt(', que deja la cobertura media de los tres niveles desagregados en 86,6 % frente al 80 % nominal. Es decir: la descomposición de varianza del apartado 6.9 reproduce por sí sola la dispersión observada fuera de muestra, sin factor de corrección.')]),
    nota('Por qué esto importa.', 'Un modelo cuyo intervalo hubiera necesitado κ = 3 para cubrir lo observado estaría admitiendo que su aritmética de la incertidumbre está mal planteada y que el intervalo se sostiene sobre un parche. Que κ salga 1,0 es la validación más fuerte que ofrece este trabajo, y es un resultado que se puede volver a comprobar en cada reestimación. Ha salido 1,0 en las tres revisiones del modelo, incluida la incorporación de la modalidad.'),
    p('La cobertura no es uniforme entre niveles: los niveles intermedios quedan por encima del nominal (94 a 96 %) y el cruce más fino ligeramente por debajo (79,8 %). Es el patrón esperable. En la celda más desagregada queda heterogeneidad individual que el supuesto multinomial no captura del todo —las decisiones de turno de personas concretas no son sorteos independientes—, mientras que en los niveles intermedios el componente sistémico resulta algo conservador.'),
    p('Conviene señalar que ese cruce más fino era el punto débil de la revisión anterior, con una cobertura del 68,5 %, casi doce puntos por debajo del nominal. Incorporar la modalidad lo ha llevado al 79,8 %, prácticamente en el objetivo. El intervalo se quedaba corto justamente donde la diferencia entre modalidades era mayor; ahora esa diferencia está en el punto central y no tiene que absorberla el margen.'),
    salto(),
  ];
}

module.exports = { especificacion, herramientas, escenarios };
