/* Capítulos 5 a 7: especificación, herramientas econométricas y escenarios. */
const U = require('./doc_parte1.js');
const {
  Paragraph, TextRun, AlignmentType, BorderStyle,
  AZUL, AMBAR, GRIS, FONDO, ANCHO_TABLA,
  p, neg, txt, cur, mono, h1, h2, h3, formula, nota, vinetas, numerada,
  tabla, figura, pieTabla, salto,
} = U;

function especificacion() {
  return [
    h1('5. Especificación del modelo'),
    h2('5.1 La ecuación de recursión'),
    p('El modelo es una cadena de Markov de cohortes con rezagos múltiples. La matrícula de un semestre en un estado dado se obtiene sumando los ingresantes declarados y los flujos que llegan desde los estados de semestres anteriores:'),
    ...formula([
      'M(T, s, c, m, d, k, u) = N(T, s, c, m, d₀, k, u)',
      '                       + Σ       Σ     M(T−L, s, c, m, d′, k′, u′) · φ_L',
      '                        L=1..4  d′,k′,u′',
      '',
      'con  φ_L = q_L(s,c,m,d′,k′,p′) · A(k′→k | c,m,d′,k′) · U(u′→u | s,m,d′,k′)',
      '',
      'y la condición de destino repartida así:',
      '     d = regular      con probabilidad 1 − r,  si L = 1',
      '         recuperado   con probabilidad r,      si L = 1',
      '         reinicio     si L ≥ 2',
      '     d₀ = ingresante, que sólo ocupan los del archivo de entrada',
      '',
      'más un flujo propio de ingresantes por nueva admisión (apartado 6.13)',
    ]),
    tabla([1500, 7526],
      ['Símbolo', 'Significado'],
      [
        ['M', 'Matrícula proyectada.'],
        ['N', 'Ingresantes declarados en el archivo de entrada, repartidos por turno según el apartado 6.7 y, si no se declara, por modalidad según el 6.8.'],
        ['T', 'Semestre académico de destino; p es su paridad (I o II).'],
        ['s, c, m', 'Sede, carrera y modalidad de estudios. Los tres se conservan a lo largo del flujo: no aparecen primados.'],
        ['d', 'Continuidad de la matrícula, en la clasificación oficial de la universidad: ingresante, regular, recuperado, reinicio e ingresante por nueva admisión. El rezago L fija las categorías de interrupción; el reparto entre regular y recuperado lo da r (apartado 6.12).'],
        ['r', 'Probabilidad de que un flujo de rezago 1 llegue como recuperado, es decir sin haber cerrado el semestre anterior. Depende de la carrera, la modalidad, el ciclo y la condición de origen.'],
        ['k, u', 'Ciclo y turno. Las primas indican el estado de origen.'],
        ['L', 'Rezago en semestres entre la matrícula de origen y la de destino.'],
        ['q_L', 'Probabilidad de que la siguiente matrícula del estudiante ocurra exactamente L semestres después.'],
        ['A', 'Distribución del salto de ciclo entre quienes se rematriculan.'],
        ['U', 'Matriz de transición de turno.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.LEFT], mono: [0] }),
    pieTabla('Notación de la ecuación de recursión.'),
    p([txt('Las tres probabilidades condicionan en la modalidad y en la condición de llegada, pero ninguna las '), cur('cambia'), txt(' por un parámetro estimado: la modalidad se conserva (apartado 5.4) y la condición la determinan el rezago y el salto de ciclo (apartado 5.5). El modelo no gasta ni un grado de libertad en ellas como variables de destino.')]),
    ...figura('11_ecuacion.png', 'La ecuación y los parámetros del modelo, tal como los expone el propio HTML en su pestaña «Modelo y validación».', { maxAlto: 430 }),

    h2('5.2 Por qué «siguiente matrícula» y no «semestre siguiente»'),
    p([txt('La definición de q_L es deliberada y merece detenerse en ella. No es «¿está matriculado en T−L y también en T?», sino «¿es T la '), cur('siguiente'), txt(' matrícula de quien estaba en T−L?».')]),
    p('La diferencia importa para la corrección aritmética. Con la primera definición, un estudiante matriculado en tres semestres consecutivos sería contado dos veces al proyectar el tercero: una desde el primero con rezago 2 y otra desde el segundo con rezago 1. Con la definición adoptada, cada matrícula de origen genera como mucho una matrícula de destino —su siguiente aparición—, de modo que los sucesos son mutuamente excluyentes y la suma de probabilidades está acotada:'),
    ...formula([
      'q_1(s) + q_2(s) + q_3(s) + q_4(s) + q_no-vuelve(s) = 1',
    ]),
    p('El modelo queda así libre de doble conteo por construcción, no por ajuste posterior.'),

    h2('5.3 Censura por el borde de la ventana observada'),
    p('Un estudiante matriculado en 2026-I sólo puede observarse con rezago 1, porque 2026-II es el último semestre de la base. Incluirlo en el denominador de q₂, q₃ y q₄ sesgaría esas tasas a la baja de forma mecánica.'),
    p('El estimador controla esa censura: una matrícula de origen en el semestre t entra en el conjunto de riesgo del rezago L únicamente si t + L cae dentro de la ventana observada. El resultado es que q₂ se estima con seis semestres de origen, q₃ con cinco y q₄ con cuatro.'),

    h2('5.4 La modalidad de estudios como atributo conservado'),
    p('La modalidad plantea una pregunta de especificación que conviene resolver con los datos y no por analogía: ¿es un estado entre los que el estudiante transita, como el turno, o un atributo que lo acompaña, como la sede?'),
    p('La respuesta está en la matriz de transición observada sobre las 89 196 transiciones de la base:'),
    tabla([2226, 1700, 1700, 1700, 1700],
      ['Modalidad de origen', '→ A distancia', '→ Presencial', '→ Semi Pres.', 'Transiciones'],
      [
        ['A distancia', '99,35 %', '0,26 %', '0,39 %', '9 171'],
        ['Presencial', '0,21 %', '99,63 %', '0,17 %', '67 418'],
        ['Semi Presencial', '0,72 %', '0,76 %', '98,52 %', '12 607'],
      ]),
    pieTabla('Matriz de transición de modalidad entre matrículas consecutivas del mismo estudiante. La diagonal concentra el 99,44 % de los casos.'),
    p([txt('Con una diagonal del 99,44 % la respuesta es inequívoca: la modalidad se comporta como la sede (0 % de cambios) y como la carrera (0,43 %), no como el turno (21,5 % de cambios). El modelo la trata por tanto como '), neg('atributo fijo del estado'), txt(' y no estima matriz de transición para ella.')]),
    p('Esa decisión tiene dos consecuencias favorables. La primera es de parsimonia: se evitan seis parámetros libres por celda que los datos no justifican. La segunda es de contabilidad: al no haber flujo entre modalidades, la matrícula proyectada de cada modalidad se puede leer directamente, sin que dependa de una matriz de traspasos que introduciría error donde no lo hay.'),
    p('Lo que sí hace el modelo es condicionar en la modalidad las tres probabilidades de la recursión:'),
    ...vinetas([
      [neg('Continuación q_L. '), txt('La modalidad es el tercer nivel de la escalera de contracción, entre el ciclo y la carrera (apartado 6.2.3). La brecha de 29 puntos en el primer ciclo es demasiado grande para promediarla.')],
      [neg('Avance de ciclo A. '), txt('El estudiante a distancia avanza un ciclo con mayor frecuencia (91,3 %) y repite menos (5,3 %) que el presencial (84,5 % y 9,6 %).')],
      [neg('Transición de turno U. '), txt('Es la más marcada de las tres: dentro de la misma sede, un estudiante presencial de turno noche pasa a mañana en un 10,1 % de los casos, mientras que uno a distancia lo hace en un 0,1 %. Apartado 5.6.')],
    ]),
    nota('Restricción de oferta.', 'El modelo conoce las 83 combinaciones de sede, carrera y modalidad que realmente existen, de las 150 teóricas. Nunca genera matrícula fuera de ellas: no coloca estudiantes a distancia en Lima Norte, que no ofrece esa modalidad, ni en Enfermería, que sólo se imparte de forma presencial. El archivo de entrada puede ampliar la oferta declarando combinaciones nuevas.'),

    h2('5.5 La continuidad de la matrícula en el estado del modelo'),
    p([txt('La condición de llegada plantea una pregunta de especificación distinta de la de la modalidad. No es si se conserva o se transita —transita, y mucho: casi todo el que vuelve pasa a regular al semestre siguiente— sino de dónde sale la etiqueta. Y la respuesta tiene dos mitades, porque '), neg('parte de la clasificación es contable y parte hay que estimarla'), txt('.')]),
    tabla([1700, 2500, 2100, 1400, 1326],
      ['Flujo', 'Cómo se determina', 'Condición de destino', 'Matrículas', 'Peso 26-I'],
      [
        ['(archivo)', 'lo declara el usuario', 'Ingresante', '23 559', '33,8 %'],
        ['L = 1', 'estimado: 1 − r', 'Regular', '69 098', '61,1 %'],
        ['L = 1', 'estimado: r', 'Recuperado', '600', '0,5 %'],
        ['L ≥ 2', 'contable', 'Reinicio', '3 566', '4,3 %'],
        ['(generado)', 'nivel por paridad', 'Ingr. nueva admisión', '339', '0,4 %'],
      ], { al: [AlignmentType.LEFT, AlignmentType.LEFT, AlignmentType.LEFT, AlignmentType.RIGHT, AlignmentType.CENTER] }),
    pieTabla('Origen de cada condición en la recursión. Las matrículas son los recuentos de la base central sobre sus seis semestres utilizables; el peso es sobre la matrícula de 2026-I. Las dos primeras filas suman el flujo de rezago 1 y se reparten con r, que es lo único que hay que estimar.'),
    ...vinetas([
      [neg('El rezago es contable. '), txt('El modelo ya descompone cada flujo por su rezago L, porque necesita los rezagos múltiples del apartado 4.5 para no perder los reingresos. Quien vuelve tras interrumpir uno o más semestres —L ≥ 2— es reiniciado por definición, sin estimar nada.')],
      [neg('El reparto dentro del rezago 1 hay que estimarlo. '), txt('Entre los que se matriculan en el semestre inmediato siguiente conviven regulares y recuperados, y lo que los separa no está en el flujo de matrícula: es si cerraron o no el semestre anterior. El modelo estima r = P(llega como recuperado | rezago 1) sobre la base central, condicionando en la carrera, la modalidad, el ciclo y la condición de origen. El apartado 6.12 desarrolla el estimador.')],
      [neg('El ingresante por nueva admisión se genera. '), txt('No sale del archivo de entrada —no es parte de la campaña de admisión que el usuario declara— ni del stock, porque es gente que vuelve de una ausencia larga por esa vía. El modelo lo inyecta como un flujo propio, con el nivel y la composición del apartado 6.13.')],
    ]),
    nota('Por qué no basta con el salto de ciclo.', 'La versión anterior del modelo definía al recuperado como quien se rematricula sin pausa y vuelve al mismo ciclo. Es una regla contable, cómoda, y da un desglose que suma exactamente el total sin estimar nada. El problema es que no es la regla de la universidad: el 81,8 % de los recuperados oficiales efectivamente repite ciclo, pero la implicación no se invierte —de las 4 978 llegadas sin pausa que repiten ciclo, sólo 405 son recuperadas, un 8,1 %—. La regla del salto de ciclo producía una categoría de unas 6 600 matrículas donde la real tiene 600, y con un comportamiento promediado que no describe a ninguna de las dos poblaciones. Se sustituyó por la estimación de r, que cuesta parámetros pero reproduce la clasificación oficial.'),
    p([txt('El desglose sigue sumando exactamente el total: r reparte el flujo de rezago 1 en dos partes que suman uno, y las demás condiciones son disjuntas por construcción. Lo que se pierde respecto de la regla contable es que ahora '), neg('hay un parámetro que estimar'), txt(', con su propia incertidumbre; lo que se gana es que el desglose es el de la universidad y no el del modelo.')]),
    nota('Un detalle de implementación con consecuencias.', 'El reparto entre regular y recuperado se resuelve DENTRO del bucle de saltos de ciclo de la recursión, no fuera, porque r se condiciona en el ciclo de origen y éste varía dentro del mismo flujo. El tope de la carrera y el de maduración de sede se aplican antes, de modo que un estudiante retenido en el ciclo terminal cuenta como que repite, igual que en los datos observados.'),

    h3('5.5.1 Qué cuesta'),
    p('Las tres probabilidades de la recursión pasan a condicionarse también en la condición de origen, y eso multiplica por cinco el número de celdas del estimador:'),
    ...vinetas([
      [neg('Continuación q_L. '), txt('La condición es el tercer nivel de la escalera de contracción, por delante de la modalidad (apartado 6.2.3). Es donde más pesa: a igualdad de ciclo y modalidad, la razón de momios frente a un regular es de 0,219 para el reiniciado y 0,286 para el recuperado.')],
      [neg('Avance de ciclo A. '), txt('El recuperado repite ciclo el 36,5 % de las veces y el reiniciado el 15,0 %, frente al 8,7 % del regular. Es la diferencia más grande de toda la matriz de avance.')],
      [neg('Transición de turno U. '), txt('El efecto es menor y además la base central no trae el turno en condiciones de usarse, de modo que esta dimensión se estima sobre el histórico con la condición aproximada que sí es derivable de él —ingresante, regular y reinicio—. El apartado 6.12 explica por qué la aproximación es inocua aquí: el 99,2 % de las matrículas consecutivas son regulares, así que colapsar al recuperado dentro del regular cambia la mezcla de turno en menos de una décima.')],
      [neg('El propio r. '), txt('Un parámetro nuevo, con su cascada de contracción de cuatro niveles.')],
    ]),
    p('Los reiniciados son el 3,6 % de la matrícula, los recuperados el 0,63 % y los ingresantes por nueva admisión el 0,35 %, de modo que sus celdas finas tienen muy pocas observaciones —el recuperado, del orden de cien por semestre en toda la universidad—. La contracción jerárquica es la que hace viable la estimación: esas celdas heredan casi todo del nivel de condición × ciclo, que sí tiene muestra suficiente, y sólo se separan de él cuando acumulan evidencia propia.'),
    nota('Por qué la memoria es de un semestre.', 'El estado recuerda cómo llegó el estudiante a este semestre, no su historial completo. Quien vuelve de una interrupción y continúa pasa a regular o a recuperado, y el modelo le aplica desde ese momento la tasa que corresponda. El apartado 4.3.2 mide lo que eso deja fuera: la cicatriz se atenúa pero no desaparece, y el modelo asigna un 85,5 % a una población que empíricamente está en el 74,2 %. Extender la memoria exigiría un contador de antigüedad desde el regreso y multiplicaría otra vez el estado; con 1 300 orígenes afectados sobre 56 040, el sesgo que se evitaría es de 0,27 puntos en la tasa de los regulares. No compensa, y queda documentado como limitación.'),

    h2('5.6 Avance de ciclo'),
    p('Entre quienes se rematriculan, la distribución del salto de ciclo es marcadamente concentrada pero no degenerada:'),
    tabla([2400, 1300, 1300, 1300, 1300, 1426],
      ['Salto de ciclo', '−1 o menos', '0', '+1', '+2', '+3 o más'],
      [
        ['Probabilidad', '1,9 %', '8,3 %', '86,8 %', '2,1 %', '1,0 %'],
        ['Interpretación', 'Retrocede', 'Repite ciclo', 'Avanza normal', 'Adelanta', 'Convalida'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.CENTER, AlignmentType.CENTER, AlignmentType.CENTER, AlignmentType.CENTER] }),
    pieTabla('Distribución agregada del salto de ciclo entre continuadores, sobre el panel de la base central.'),
    p('El 8,3 % que repite ciclo es el que hace que una proyección ingenua de «todos avanzan un ciclo» acumule error: al cabo de seis semestres desplaza la distribución de la matrícula por ciclos de forma apreciable.'),
    p('La distribución se estima por condición, modalidad y ciclo, contraída hacia el perfil del ciclo. La condición es la que más la mueve:'),
    tabla([2226, 1360, 1360, 1360, 1360, 1360],
      ['Condición de llegada', 'Retrocede', 'Repite', 'Avanza +1', 'Adelanta +2', 'Convalida +3'],
      [
        ['Regular', '3,1 %', '13,7 %', '80,5 %', '2,0 %', '0,8 %'],
        ['Recuperado', '3,1 %', '37,3 %', '50,2 %', '7,7 %', '1,7 %'],
        ['Reinicio', '6,3 %', '17,2 %', '68,7 %', '4,2 %', '3,6 %'],
        ['Ingresante', '0,1 %', '6,1 %', '92,2 %', '1,2 %', '0,5 %'],
        ['Ingr. nueva admisión', '1,4 %', '6,0 %', '62,9 %', '11,3 %', '18,4 %'],
      ]),
    pieTabla('Distribución del salto de ciclo por condición de llegada, tras la contracción y ponderada por el stock del último semestre de la base central, tomando para cada condición el stock de esa misma condición. El ingresante avanza de forma casi determinista porque casi todos parten del ciclo 1.'),
    p([txt('El perfil del recuperado es el que más se aparta: repite el 37,3 % de las veces, más del doble que un reiniciado y casi el triple que un regular. Compensa algo por el otro extremo —adelanta dos ciclos el 7,7 % frente al 2,0 % de un regular, porque quien arrastra cursos y por fin los aprueba recupera lo perdido— pero no lo suficiente: su avance medio por semestre continuado es de 0,67 ciclos frente a 0,84 de un regular. El '), neg('ingresante por nueva admisión es el reverso'), txt(': convalida tres o más ciclos el 18,4 % de las veces y adelanta dos el 11,3 %, de modo que avanza 1,39 ciclos de media. La diferencia por modalidad existe pero es menor. El modelo conserva ambas —la cascada del apartado 6.2.3 pasa por condición y luego por modalidad— porque cada una aporta una parte del patrón.')]),
    p('El ciclo de destino se acota al ciclo terminal del plan de la carrera. Un estudiante que estuviera en el ciclo 10 de un plan de diez ciclos y «avanzara» no puede aparecer en un ciclo 11 que no existe: permanece en el 10, que es lo que hace el rezagado real que aún arrastra cursos.'),

    h2('5.7 Transición de turno'),
    p('La matriz de transición de turno se estima por sede, modalidad y ciclo, contraída hacia la matriz de la sede. Estimarla por sede es imprescindible porque el catálogo de turnos difiere entre ambas; estimarla además por modalidad lo es porque el comportamiento dentro de una misma sede no se parece.'),
    tabla([2626, 1200, 1200, 1200, 1200, 1600],
      ['Sede · modalidad · turno de origen', '→ Diurno', '→ Mañana', '→ Noche', '→ Tarde', 'Obs. efectivas'],
      [
        ['L. Norte · Presencial · Diurno', '93,2 %', '—', '6,8 %', '—', '503'],
        ['L. Norte · Presencial · Noche', '11,1 %', '—', '88,9 %', '—', '239'],
        ['L. Norte · Semi Pres. · Noche', '—', '—', '100,0 %', '—', '110'],
        ['L. Sur · Presencial · Mañana', '—', '73,9 %', '19,8 %', '6,2 %', '8 643'],
        ['L. Sur · Presencial · Noche', '—', '10,1 %', '86,3 %', '3,6 %', '7 519'],
        ['L. Sur · Presencial · Tarde', '—', '35,2 %', '49,0 %', '15,8 %', '1 117'],
        ['L. Sur · Semi Pres. · Noche', '—', '0,6 %', '91,1 %', '8,3 %', '3 209'],
        ['L. Sur · Semi Pres. · Tarde', '—', '1,7 %', '71,1 %', '27,1 %', '362'],
        ['L. Sur · A distancia · Noche', '—', '0,1 %', '93,7 %', '6,2 %', '3 148'],
        ['L. Sur · A distancia · Tarde', '—', '0,2 %', '87,6 %', '12,1 %', '170'],
      ], { tam: 17 }),
    pieTabla('Matriz de transición de turno por sede, modalidad y turno de origen, ponderada por recencia. Las observaciones son el tamaño muestral efectivo tras la ponderación; se omiten las combinaciones con menos de 50.'),
    p([txt('La comparación que justifica la especificación está en las filas de Lima Sur con turno noche de origen. Un estudiante '), neg('presencial'), txt(' pasa al turno mañana en un 10,1 % de los casos; uno '), neg('semipresencial'), txt(', en un 0,6 %; uno '), neg('a distancia'), txt(', en un 0,1 %. Misma sede, mismo turno de partida, comportamientos que difieren en dos órdenes de magnitud. Una matriz estimada sólo por sede promediaría los tres y devolvería un flujo hacia el turno mañana que no le corresponde a dos de las tres poblaciones.')]),
    p('Dos lecturas más conviene destacar. El turno noche es muy estable en todas las modalidades —entre el 86 % y el 94 % permanece—, mientras que el turno tarde es el más inestable: en la modalidad presencial sólo un 15,8 % permanece y la mayoría migra a mañana o noche. Es coherente con un turno en retirada, como confirma la caída de su participación entre los ingresantes.'),

    h2('5.8 Maduración de sede'),
    p('Una sede que acaba de abrir no puede tener estudiantes en cualquier ciclo: despliega su plan de estudios semestre a semestre. En el semestre de apertura sólo existe el ciclo 1; un semestre después, el 2; y así sucesivamente hasta completar el plan.'),
    p('El modelo impone ese tope como una restricción dura sobre el ciclo de destino, en paralelo al tope por duración del plan de la carrera:'),
    ...formula([
      'ciclo_destino = min( ciclo_origen + Δ ,  ciclos_plan(carrera) ,  tope_sede(s, T) )',
      '',
      'tope_sede(s, T) = max( 0 ,  ciclo_base(s) + semestres_transcurridos(s, T) )',
      '',
      '  ciclo_base(s)  ciclo máximo de la sede en su semestre de apertura',
      '  semestres_transcurridos  distancia entre la apertura y el semestre T',
    ]),
    p('La restricción actúa en dos puntos. Sobre los continuadores, porque la matriz de avance permite saltos de +2 y +3 que llevarían a un estudiante a un ciclo inexistente. Y sobre los ingresantes, porque el archivo de entrada puede declarar traslados a ciclos superiores que la sede todavía no imparte; en ese caso el modelo lo avisa fila por fila y los reasigna al ciclo máximo disponible.'),

    h3('5.8.1 Cómo se detecta la apertura'),
    p('La apertura no se declara a mano: se infiere del propio histórico. Si el ciclo máximo del primer semestre observado de una sede es 1 o 2, la sede arrancó ahí. Si aparece con el plan completo desde su primer registro, es anterior a la ventana de datos y no recibe tope.'),
    tabla([2000, 1700, 1500, 3826],
      ['Sede', 'Primer registro', 'Ciclo máx.', 'Conclusión'],
      [
        ['Lima Norte', '2026-I', '1', 'Abrió en 2026-I: despliegue progresivo.'],
        ['Lima Sur', '2023-I', '11', 'Plan completo desde el inicio de la base: sin tope.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Detección automática de la apertura de sede sobre el histórico.'),
    p('Una sede que aparece por primera vez en el archivo de ingresantes se trata como una apertura en ese semestre, con el mismo mecanismo. No hace falta declararla ni configurar nada.'),
    tabla([1900, 1150, 1150, 1150, 1150, 1150, 1376],
      ['Sede', '2027-I', '2027-II', '2028-I', '2028-II', '2029-I', '2029-II'],
      [
        ['Lima Norte (abrió 2026-I)', '3', '4', '5', '6', '7', '8'],
        ['Lima Sur (consolidada)', 'sin tope', 'sin tope', 'sin tope', 'sin tope', 'sin tope', 'sin tope'],
        ['Sede nueva que abra en 2028-I', 'no opera', 'no opera', '1', '2', '3', '4'],
      ]),
    pieTabla('Ciclo máximo ofertable por sede y semestre. La tercera fila es un ejemplo de sede declarada en el archivo de ingresantes.'),
    ...figura('11b_maduracion.png', 'La restricción de maduración tal como la expone el modelo, con la apertura detectada de cada sede y su ciclo máximo por semestre.', { maxAlto: 330 }),
    nota('Qué ocurre en el tope.', 'Un estudiante que no puede avanzar porque la sede aún no imparte el siguiente ciclo se acumula en el ciclo máximo disponible, igual que el rezagado que arrastra cursos al final de su plan. Es el mismo tratamiento que recibe el tope por duración de la carrera y mantiene la contabilidad cerrada: ningún estudiante se pierde ni se duplica.'),

    h2('5.9 Lo que el modelo no mueve'),
    p('Tres dimensiones se mantienen constantes a lo largo de la proyección porque los datos así lo indican:'),
    ...vinetas([
      [neg('Sede. '), txt('Ningún estudiante del histórico cambia de sede. Se conserva.')],
      [neg('Carrera. '), txt('El 99,57 % de los continuadores mantiene su carrera. El 0,43 % restante se reparte sin patrón discernible y modelarlo añadiría parámetros sin ganancia predictiva.')],
      [neg('Modalidad de estudios. '), txt('El 99,44 % de los continuadores mantiene su modalidad. Se conserva, y en cambio condiciona las tres probabilidades de transición (apartado 5.4).')],
    ]),
    p('El ciclo y el turno sí se mueven, y son los únicos dos índices del estado que llevan matriz de transición estimada. La continuidad también cambia de un semestre a otro, pero no por una matriz estimada: es una función del rezago y del salto de ciclo del flujo (apartado 5.5). Esa asimetría no es una simplificación de conveniencia: es lo que dicen las 89 196 transiciones observadas.'),
    tabla([2600, 1700, 4726],
      ['Índice del estado', 'Cambia', 'Cómo lo trata el modelo'],
      [
        ['Sede', '0 %', 'Se conserva.'],
        ['Modalidad', '0,56 %', 'Se conserva; condiciona las tres probabilidades.'],
        ['Carrera', '0,43 %', 'Se conserva.'],
        ['Continuidad', 'siempre', 'La fijan el rezago y el salto de ciclo; sin parámetros.'],
        ['Ciclo', '15,1 %', 'Matriz de avance estimada.'],
        ['Turno', '21,5 %', 'Matriz de transición estimada.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Tratamiento de cada índice del estado según su movilidad observada. Sólo dos de los seis necesitan matriz estimada.'),
    salto(),
  ];
}

function herramientas() {
  return [
    h1('6. Herramientas econométricas aplicadas'),
    p('Este capítulo detalla los instrumentos estadísticos empleados, por qué se eligieron y cómo se implementan. Es el núcleo del sustento metodológico.'),

    h2('6.1 El problema de fondo: muchas celdas, pocos datos por celda'),
    p('El estado del modelo es (sede, carrera, modalidad, continuidad, ciclo, turno): 2 × 25 × 3 × 4 × 11 × 4 = 26 400 combinaciones teóricas, y cada una necesita sus probabilidades de transición condicionadas además a la paridad del semestre y al rezago. Frente a eso hay ocho semestres de historia.'),
    p('La restricción de oferta reduce el problema —sólo existen 83 combinaciones de sede, carrera y modalidad, no 150— pero no lo elimina: en 2026-II hay 1 151 celdas completas no vacías y la mediana tiene menos de cinco estudiantes.'),
    p('Conviene ser explícito sobre el peligro: cada dimensión que se añade parte las celdas y las vacía. Que la modalidad y la continuidad mejoren la proyección no es automático, y por eso cada una se contrasta con una ablación completa (apartados 6.5 y 6.6) en lugar de darse por buena porque su coeficiente sea significativo.'),
    p('Estimar cada celda por separado con su propia frecuencia produciría tasas inestables: una celda con siete estudiantes de los que continúan cinco daría una tasa del 71,4 % con un error típico de ±17 puntos. Agregarlo todo y usar una tasa única, en el otro extremo, perdería la estructura por ciclo y por modalidad que el capítulo 4 mostró decisiva.'),
    p('La solución empleada es la contracción jerárquica: cada celda combina su propia evidencia con la de un nivel más agregado, en proporción a cuánta información tiene realmente.'),

    h2('6.2 Contracción empírico-Bayes con modelo Beta-Binomial'),
    h3('6.2.1 El estimador'),
    p('Para una tasa de continuación, la estimación de una celda es:'),
    ...formula([
      '            k_celda + k · q_padre',
      'q_celda =  ───────────────────────',
      '            n_celda + k',
      '',
      '   n_celda  observaciones de la celda (ponderadas por recencia)',
      '   k_celda  de ellas, las que continúan',
      '   q_padre  estimación del nivel inmediatamente superior',
      '   k        constante de contracción',
    ]),
    p([txt('La constante '), mono('k'), txt(' es el tamaño muestral equivalente del prior: la celda pondera su propia evidencia con peso n/(n+k) y la del padre con peso k/(n+k). Una celda con muchas observaciones se estima casi sola; una con pocas hereda casi todo del nivel superior. La transición entre ambos regímenes es suave y automática.')]),

    h3('6.2.2 Cómo se obtiene k, y por qué no se elige a mano'),
    p([txt('La constante se estima por el '), neg('método de los momentos del modelo Beta-Binomial'), txt('. Si las tasas verdaderas de las celdas siguen una distribución Beta(α, β), su varianza entre celdas es una función de α+β, y despejando:')]),
    ...formula([
      '        p̄ (1 − p̄)',
      'k  =  ───────────── − 1        con  k = α + β',
      '         σ²_entre',
      '',
      'σ²_entre = σ²_observada − σ²_muestral',
      'σ²_muestral = Σ w_i · p̄(1−p̄)/n_i      (ruido binomial esperado)',
    ]),
    p('La lógica es directa: se mide cuánto varían las tasas entre celdas, se descuenta lo que se explicaría por puro azar muestral, y lo que sobra es heterogeneidad real. Mucha heterogeneidad real implica k pequeña —las celdas son genuinamente distintas y conviene creerles—; poca heterogeneidad implica k grande y contracción fuerte hacia el padre.'),
    p('Es importante que k no sea un parámetro de ajuste elegido por el analista: sale de los propios datos, y su valor es interpretable y auditable.'),

    h3('6.2.3 La escalera de niveles'),
    p('La contracción se aplica en cadena, del nivel más agregado al más fino. Cada nivel sirve de prior al siguiente:'),
    ...formula([
      'global  →  ciclo  →  ciclo × paridad  →  continuidad × ciclo × paridad',
      '        →  continuidad × modalidad × ciclo × paridad',
      '        →  continuidad × modalidad × carrera × ciclo × paridad',
      '        →  continuidad × modalidad × carrera × sede × ciclo × paridad',
    ]),
    p('Nótese que la condición se usa aquí como índice del estado de ORIGEN: la tasa que se busca es la de un estudiante que llegó a este semestre en una condición dada. La condición de destino no interviene en esta estimación; la fijan después el rezago del flujo y el reparto r del apartado 6.12.'),
    p([txt('El orden de la escalera no es arbitrario: va de lo que más informa a lo que menos. Primero el ciclo, luego la '), neg('continuidad de la matrícula'), txt(', luego la '), neg('modalidad'), txt(', y sólo al final la carrera y la sede. Dicho de otro modo: para predecir si un estudiante continúa, saber si viene de una interrupción informa más que saber en qué modalidad estudia, y ambas cosas informan más que saber qué carrera cursa.')]),
    p('Las constantes estimadas lo confirman. Una k mayor significa que las celdas de ese nivel se parecen más entre sí y conviene contraerlas con fuerza; una k menor, que son genuinamente distintas y conviene creerles. La secuencia 5,40 → 5,31 → 4,79 → 4,22 → 3,26 es monótona, que es exactamente lo que cabe esperar de una escalera bien ordenada.'),
    tabla([3500, 1400, 4126],
      ['Parámetro', 'k estimada', 'Lectura'],
      [
        ['Continuación · nivel celda (rezago 1)', '3,26', 'Heterogeneidad alta entre sedes: se cree bastante a cada celda.'],
        ['Continuación · nivel carrera (rezago 1)', '3,26', 'Las carreras difieren realmente entre sí dentro de cada condición, modalidad y ciclo.'],
        ['Continuación · nivel modalidad (rezago 1)', '4,22', 'Las tres modalidades son poblaciones distintas.'],
        ['Continuación · nivel continuidad (rezago 1)', '4,79', 'Las cinco condiciones también, aunque con algo más de contracción.'],
        ['Continuación · nivel ciclo×paridad', '5,31', 'El efecto de la paridad es real pero moderado.'],
        ['Continuación · nivel ciclo', '5,40', 'El perfil por ciclo es la estructura dominante.'],
        ['Continuación · rezagos 2 a 4', '30 a 10 000', 'Mucha más contracción: el reingreso tras pausa se comporta de forma parecida en todas las celdas y se estima muy agrupado.'],
        ['Reparto regular / recuperado (r)', '27,43', 'Contracción fuerte: 495 casos en seis semestres no dan para creer a las celdas finas (apartado 6.12).'],
        ['Avance de ciclo', '4,34', 'El patrón de avance varía apreciablemente entre condiciones y modalidades.'],
        ['Transición de turno', '1,00 (mínimo)', 'Heterogeneidad muy alta por sede, modalidad, condición y ciclo: apenas se contrae.'],
        ['Reparto de turno de ingresantes', '1,00 (mínimo)', 'Ídem: una vez condicionado en la modalidad, cada celda tiene su propio patrón.'],
        ['Reparto de modalidad de ingresantes', '1,77', 'Contracción ligera hacia el nivel de sede y carrera.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Constantes de contracción estimadas por el método de los momentos.'),
    nota('Resultado interpretable.', 'Que las constantes de los rezagos 2 a 4 sean grandes es un hallazgo, no un fallo: el estimador está diciendo que la probabilidad de volver tras una pausa apenas depende de la carrera, la modalidad o la condición previa, y que conviene estimarla con la muestra muy agrupada. Es coherente con el capítulo 4: lo que distingue al que vuelve no es la probabilidad de volver, sino lo que hace después de haber vuelto. Que la k del turno caiga al mínimo dice lo contrario: cada combinación de sede, modalidad, condición y ciclo tiene su propio patrón y hay datos suficientes para estimarlo.'),

    h2('6.3 Contracción Dirichlet-Multinomial para composiciones'),
    p('El avance de ciclo, la transición de turno y el reparto de los ingresantes por turno y por modalidad no son tasas sino composiciones: vectores de probabilidades que suman uno. La extensión natural del Beta-Binomial es el modelo Dirichlet-Multinomial:'),
    ...formula([
      '              c_j + k · π_j(padre)',
      'π_j(celda) = ──────────────────────        para cada categoría j',
      '                 Σ c + k',
    ]),
    p('La constante k se estima con el mismo método de los momentos aplicado a la categoría de mayor masa, que es la que gobierna la variabilidad del conjunto. El resultado se renormaliza para garantizar que la composición suma exactamente uno.'),

    h2('6.4 Modelo lineal generalizado para descomponer la varianza'),
    p('Para separar las fuentes de variación de la tasa de continuación se ajusta un GLM binomial con enlace logit sobre las 109 799 transiciones del histórico con semestre de destino observable:'),
    ...formula([
      'logit P(continúa) = μ + α_ciclo + β_modalidad + δ_continuidad + γ_semestre',
    ]),
    p('La paridad no entra como regresor independiente: está anidada en el semestre y su inclusión produciría un diseño de rango deficiente. Se extrae después proyectando los efectos de semestre estimados sobre la paridad, y el residuo de esa proyección es el choque estocástico.'),
    p([txt('La modalidad y la continuidad entran como '), neg('controles'), txt('. La razón es de libro de texto: si una variable afecta a la probabilidad de continuar y su composición cambia con el tiempo, omitirla hace que su deriva se contabilice en los efectos de periodo. El choque de periodo así medido no sería volatilidad, sino cambio de composición mal atribuido.')]),
    p('Hay además una razón de coherencia interna. El GLM auxiliar sólo sirve para separar lo predecible de lo impredecible, y «predecible» tiene que significar aquí «predecible por el modelo de puntos». Si el GLM ignorase una dimensión que la proyección sí condiciona, los escenarios recogerían como incertidumbre algo que el modelo ya sabe, y saldrían injustificadamente anchos.'),
    nota('Qué versión de la continuidad entra en este GLM, y por qué.', 'Este modelo auxiliar se ajusta sobre el histórico de matriculados, que cubre ocho semestres —dos más que la base central— y es imprescindible para medir el choque de periodo, porque con seis semestres quedarían tres grados de libertad. El histórico no trae el campo Condición, de modo que la continuidad entra aquí en su versión derivable del flujo: ingresante, regular y reinicio, con el recuperado colapsado dentro del regular. Para lo que este GLM hace —descontar la deriva de composición de los efectos de periodo— la aproximación es inocua, porque el recuperado oficial es el 0,83 % del flujo de rezago 1 y su peso apenas se mueve entre semestres: colapsarlo cambia σ del choque en la cuarta cifra decimal. Los contrastes sobre las cinco condiciones oficiales, que sí necesitan el campo, están en el apartado 6.12.'),
    tabla([3600, 1800, 3626],
      ['Estadístico', 'Valor', 'Lectura'],
      [
        ['Observaciones', '109 799', 'Transiciones con destino observable.'],
        ['Devianza residual', '97 042', 'Sobre 109 778 grados de libertad.'],
        ['Pseudo-R² (McFadden)', '0,1554', 'Habitual en modelos de elección individual: el comportamiento de una persona concreta es en gran medida idiosincrásico. Sin ninguno de los dos controles era 0,1348.'],
        ['β Presencial (base: a distancia)', '+0,769', 'Error típico 0,022; z = 34,9; p ≈ 4·10⁻²⁶⁶. Razón de momios 2,16.'],
        ['β Semi Presencial', '+0,488', 'Error típico 0,028; z = 17,5; p ≈ 7·10⁻⁶⁹. Razón de momios 1,63.'],
        ['δ Reinicio (base: regular)', '−1,554', 'Error típico 0,044; z = −35,5; p ≈ 1·10⁻²⁷⁵. Razón de momios 0,211.'],
        ['δ Ingresante', '−0,536', 'Error típico 0,048; z = −11,2; p ≈ 5·10⁻²⁹. Razón de momios 0,585.'],
        ['χ² del bloque de modalidad', '1 200,7', '2 g.l.; p ≈ 2·10⁻²⁶¹.'],
        ['χ² del bloque de continuidad', '1 143,7', '2 g.l.; p ≈ 4·10⁻²⁴⁹.'],
        ['χ² de la interacción continuidad × ciclo', '250,2', '20 g.l.; p ≈ 1·10⁻⁴¹.'],
        ['χ² del bloque de semestre', '54,62', '6 g.l.; p ≈ 5·10⁻¹⁰.'],
        ['σ de los efectos de semestre', '0,0699', 'En escala logit, antes de descontar estacionalidad.'],
        ['σ del choque estocástico', '0,0459', 'Tras descontar estacionalidad; 5 g.l.'],
        ['Efecto estacional', '±0,0528', 'Semestre I frente a semestre II, en logit.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Resultados del GLM auxiliar de descomposición de varianza.'),
    p([txt('El pseudo-R² moderado es esperable y no invalida el uso: el modelo auxiliar no pretende predecir si '), cur('un'), txt(' estudiante concreto continuará, sino cuantificar cuánto se mueve la tasa '), cur('media'), txt(' entre semestres una vez controlados el ciclo, la modalidad y la continuidad. Para ese fin lo relevante es la significación de los bloques, que es contundente en los tres.')]),
    p('Los dos bloques de composición pesan casi lo mismo —χ² de 1 200,7 con 2 g.l. la modalidad y 1 143,7 con 2 g.l. la continuidad— pero reparten su efecto de forma muy distinta: la razón de momios de un reiniciado frente a un regular es de 0,211, mientras que la mayor diferencia entre modalidades, de presencial a distancia, es de 0,46 (el inverso de 2,16). La interacción de la continuidad con el ciclo también es significativa, y por eso la escalera de contracción condiciona en el ciclo antes que en nada más.'),

    h3('6.4.1 Cuánto cambia la descomposición al controlar la composición'),
    p('El efecto de los controles es grande y va todo en la misma dirección. Ajustando el mismo GLM sobre las mismas 109 799 transiciones, añadiendo un bloque cada vez:'),
    tabla([2900, 1600, 1600, 1600, 1326],
      ['Componente', 'Sólo ciclo', '+ modalidad', '+ continuidad', 'Variación'],
      [
        ['σ del choque de periodo', '0,0937', '0,0589', '0,0459', '−51,0 %'],
        ['Efecto estacional (logit)', '±0,0560', '±0,0375', '±0,0528', '−5,7 %'],
        ['χ² del bloque de semestre', '134,8', '54,4', '54,6', '−59,5 %'],
        ['Pseudo-R² de McFadden', '0,1348', '0,1455', '0,1554', '+15,3 %'],
      ]),
    pieTabla('Descomposición de la varianza según los controles de composición incluidos. La última columna compara la especificación final con la inicial.'),
    p([txt('La lectura es directa: '), neg('casi la mitad de lo que se medía como choque de periodo era deriva de composición'), txt(' —primero el peso creciente de una modalidad con menor retención, después el de una población que vuelve de interrupciones—. El χ² del bloque de semestre cae un 59 % porque buena parte de lo que capturaba no era un movimiento del entorno.')]),
    p('El efecto estacional se comporta de otro modo, y merece una nota. Cae al controlar la modalidad y vuelve a subir al controlar la continuidad, hasta quedar cerca de su valor original. Tiene sentido: los reingresos se concentran en los primeros semestres del año, de modo que parte de lo que parecía estacionalidad era composición, y parte de lo que la composición ocultaba era estacionalidad genuina. Lo que importa para los escenarios es el residuo tras descontar ambas cosas, y ése baja de forma monótona.'),
    p('La consecuencia práctica es que los escenarios se estrechan: el desplazamiento sistémico que los gradúa pasa de ±0,138 a ±0,087 y de ahí a ±0,068 en escala logit. No es un ajuste discrecional de la amplitud, sino la traducción de haber convertido incertidumbre en estructura.'),
    p('Descomponiendo la varianza de la tasa agregada entre semestres:'),
    tabla([3600, 2200, 3226],
      ['Componente', 'Varianza', 'Participación'],
      [
        ['Observada entre semestres', '2,225·10⁻⁴', '100,0 %'],
        ['Atribuible al muestreo', '0,111·10⁻⁴', '5,0 %'],
        ['Atribuible al proceso', '2,114·10⁻⁴', '95,0 %'],
      ]),
    pieTabla('Descomposición de la varianza de la tasa agregada de continuación. El componente de proceso incluye tanto la parte predecible —estacionalidad y composición— como el choque genuino; sólo este último alimenta los escenarios.'),
    ...figura('14_incertidumbre.png', 'La descomposición de la incertidumbre, tal como la presenta el modelo.', { maxAlto: 470 }),

    h2('6.5 Contraste de especificación: la dimensión modalidad'),
    p('El GLM auxiliar dice que la modalidad es significativa, pero eso no basta: la significación estadística no garantiza ganancia predictiva. La pregunta relevante es si el modelo completo proyecta mejor con esa dimensión que sin ella.'),
    p('Para responderla se ejecutó una ablación: el mismo procedimiento de principio a fin sobre la misma base histórica, con la única diferencia de colapsar la modalidad a una categoría única en la segunda especificación. En ambos casos la ponderación de recencia se selecciona por validación cruzada dentro de la propia especificación, de modo que se comparan dos procedimientos completos y no dos conjuntos de parámetros.'),
    tabla([2400, 1900, 1900, 1500, 1326],
      ['Nivel de agregación', 'Sin modalidad', 'Con modalidad', 'Reducción', 'Celdas'],
      [
        ['Total institucional', '1,129 %', '1,035 %', '8,3 %', '1'],
        ['Sede', '1,129 %', '1,035 %', '8,3 %', '2'],
        ['Carrera', '2,348 %', '2,165 %', '7,8 %', '25'],
        ['Sede × carrera', '2,348 %', '2,165 %', '7,8 %', '42'],
        { __sub: 'Otros resultados del contraste' },
        ['Sesgo medio del total', '+57', '−10', '82 %', '—'],
        ['λ elegida por validación cruzada', '0,55', '1,00', '—', '—'],
      ]),
    pieTabla('Ablación de la dimensión modalidad, medida sobre la especificación completa y sobre los semestres objetivo ya cerrados: el brazo «con modalidad» es el modelo de producción y el brazo «sin» es el mismo procedimiento con la modalidad colapsada a una categoría. EPAP medio fuera de muestra en los cuatro niveles de agregación que existen en ambas; los niveles más finos no son comparables porque añadir la dimensión parte las celdas. Las filas de sede y de sede × carrera coinciden con las de total y carrera porque Lima Norte, la única sede nueva, se proyecta sin error.'),
    p('El error baja en los cuatro niveles comparables, entre un 8 % y un 8,3 %, y el sesgo medio del total pasa de +57 a −10 estudiantes: cambia de signo y queda en media décima de punto. Pero el resultado más informativo es el de la última fila.'),
    nota('La recencia estaba haciendo de variable omitida.', 'Sin la dimensión de modalidad, la validación cruzada baja λ de 1,00 a 0,55: el estimador pide olvidar casi la mitad del pasado, porque es la única forma que tiene de seguir una composición que cambia sin poder verla. Al incorporarla, el óptimo sube al borde superior: ya no hace falta tirar información antigua para capturar la deriva, porque la deriva está explícitamente modelada. Es el mismo patrón que aparece en el apartado 6.6 con la continuidad, y el argumento no depende de la magnitud de la mejora en EPAP: depende de dónde cae el óptimo de λ, que es una señal cualitativa y mucho más robusta con pocas comparaciones.'),
    p('Conviene ser explícito sobre el alcance de este contraste: se apoya en las mismas tres comparaciones cerradas que el resto de la validación, de modo que la magnitud exacta de la mejora tiene un margen amplio. Lo que sí es robusto es el signo —la mejora aparece en los cuatro niveles y en el sesgo— y el desplazamiento del óptimo de λ, que no depende de cuántas comparaciones haya.'),
    nota('Medida contra todos los objetivos, la mejora parece mayor.', 'Incluyendo el semestre incompleto, la reducción va del 11 % al 31 % y el sesgo pasa de +290 a +199. No es la cifra que este documento adopta, por lo que explica el apartado 8.4: la especificación sin modalidad proyecta de más, y el objetivo censurado la penaliza el doble. Las dos mediciones coinciden en el signo, que es lo que sostiene la conclusión.'),

    h2('6.6 Contraste de especificación: la continuidad de la matrícula'),
    p('La misma ablación, aplicada ahora a la continuidad sobre la especificación que ya incluye la modalidad. Colapsar la dimensión significa aquí tratar a todos los continuadores como una sola población: sin r, sin tasas propias por condición y sin el flujo de nueva admisión.'),
    tabla([2400, 1900, 1900, 1500, 1326],
      ['Nivel de agregación', 'Sin continuidad', 'Con continuidad', 'Reducción', 'Celdas'],
      [
        ['Total institucional', '1,146 %', '1,035 %', '9,6 %', '1'],
        ['Sede', '1,146 %', '1,035 %', '9,6 %', '2'],
        ['Carrera', '2,259 %', '2,165 %', '4,2 %', '25'],
        ['Sede × carrera', '2,259 %', '2,165 %', '4,2 %', '42'],
        { __sub: 'Otros resultados del contraste' },
        ['Sesgo medio del total', '−73', '−10', '—', '—'],
        ['λ elegida por validación cruzada', '1,00', '1,00', '—', '—'],
      ]),
    pieTabla('Ablación de la dimensión de continuidad, medida sobre los objetivos cerrados. EPAP medio fuera de muestra en los cuatro niveles comunes; en cada especificación λ se elige por validación cruzada sobre esos mismos cuatro niveles. Las dos filas de sede coinciden con las de total y carrera porque la única sede nueva, Lima Norte, se proyecta sin error: en 2026-I toda su matrícula son ingresantes declarados del primer ciclo.'),
    nota('Por qué esta ablación excluye el semestre parcial, y qué pasa si no se excluye.', 'El último semestre del histórico sigue admitiendo altas en la fecha de extracción (apartado 3.4.2), de modo que como OBJETIVO del backtesting está censurado por abajo: cualquier especificación que proyecte de menos parecerá acertar más. Y eso es exactamente lo que ocurre. Midiendo contra todos los objetivos, incluido el incompleto, la especificación sin continuidad sale mejor —1,430 % frente a 1,509 % en el total— porque proyecta 140 estudiantes por encima de lo observado en vez de 199. Excluyendo el objetivo censurado, la comparación se invierte y el sesgo de la especificación completa pasa a ser seis veces menor: −10 frente a −73. Las dos mediciones se informan; la conclusión honesta es que el signo de la comparación depende de si se compara contra un semestre cerrado o contra uno a medio llenar, y sólo el primero es una medición.'),
    p([txt('La mejora es del 9,6 % en el total y del 4,2 % en carrera: '), neg('mucho menor que la que declaraba la versión anterior de este documento'), txt(', que cifraba la reducción entre el 30 % y el 47 %. La diferencia no está en los datos sino en la definición. Aquella versión separaba una categoría de recuperados construida con el salto de ciclo, que recogía unas 6 600 matrículas —el 5,1 % del total— y capturaba de paso el efecto real de repetir ciclo sobre la retención. La categoría oficial es diez veces menor, y por tanto mueve mucho menos el agregado. El valor de la dimensión, así medido, es ahora sobre todo el del '), neg('reinicio'), txt(', que sí pesa un 3,6 % y sí se comporta de forma muy distinta.')]),
    p('Donde la dimensión sigue siendo decisiva es en el sesgo, que es lo que importa para una proyección a varios semestres: sin ella el modelo se queda 73 estudiantes corto por semestre y con ella 10, una séptima parte. Un error de nivel persistente se acumula a lo largo del horizonte; un error de dispersión, no.'),
    nota('Y hay una razón que no es de precisión.', 'Aunque la ganancia en EPAP fuese nula, la dimensión se quedaría. El encargo pide proyectar la matrícula abierta por la clasificación que usa la universidad, y esa clasificación tiene cinco categorías. Un modelo que proyectara sólo el total y repartiera después por cuotas históricas daría números parecidos en el agregado, pero no sería el mismo producto: no respondería a «cuántos recuperados habrá en Psicología a distancia en el ciclo 3», que es una de las preguntas del encargo. La ablación mide el coste de esa exigencia, y el coste resulta ser negativo, es decir que además mejora.'),
    p('Conviene señalar el límite del argumento, igual que en el apartado anterior: tres comparaciones no permiten afirmar que la mejora sea exactamente del 9,6 %. Lo robusto es el signo, que aparece en los cuatro niveles y sobre todo en el sesgo.'),

    h2('6.7 Ponderación exponencial de recencia'),
    h3('6.7.1 El problema'),
    p('El capítulo 4 documentó varias derivas estructurales: la retención cae en los semestres recientes, la composición por modalidad se desplaza hacia la modalidad a distancia y la composición por turno de los ingresantes hacia el turno noche. Ponderar los ocho semestres por igual arrastraría información caducada.'),
    p('Ahora bien, a medida que esas derivas se incorporan al modelo como estructura, dejan de ser un motivo para olvidar. El apartado 6.6 mostró que el λ óptimo sube de 0,30 a 1,00 al identificarlas. La recencia sigue siendo un instrumento del modelo, pero ya no es el que carga con la deriva.'),
    p('El estimador aplica por tanto un peso exponencial a cada observación según su antigüedad:'),
    ...formula([
      'w(t) = λ^(t_último − t)          con 0 < λ ≤ 1',
      '',
      'λ = 1    todo el histórico pesa igual',
      'λ < 1    los semestres recientes pesan más; la semivida es log(0,5)/log(λ)',
    ]),

    h3('6.7.2 La elección de λ por validación cruzada'),
    p('El valor de λ no se fijó por criterio. Se recorrió una rejilla de valores y para cada uno se ejecutó el backtesting completo de origen móvil, midiendo el error fuera de muestra en los ocho niveles de agregación.'),
    tabla([880, 1180, 1180, 1180, 1180, 1180, 1180, 1066],
      ['λ', 'Total', 'Continuidad', 'Sede×Carr.', '×Modalidad', '×Ciclo', 'Peor nivel', 'Sesgo'],
      [
        ['1,00', '1,035 %', '2,292 %', '2,165 %', '2,716 %', '14,133 %', '102,00', '−10'],
        ['0,90', '1,082 %', '2,306 %', '2,165 %', '2,706 %', '14,100 %', '104,51', '−19'],
        ['0,85', '1,093 %', '2,298 %', '2,156 %', '2,701 %', '14,075 %', '105,57', '−22'],
        ['0,80', '1,124 %', '2,310 %', '2,167 %', '2,724 %', '14,051 %', '108,57', '−28'],
        ['0,75', '1,148 %', '2,314 %', '2,157 %', '2,734 %', '14,041 %', '110,84', '−34'],
        ['0,70', '1,154 %', '2,302 %', '2,153 %', '2,736 %', '14,051 %', '111,45', '−37'],
        ['0,65', '1,163 %', '2,308 %', '2,147 %', '2,738 %', '14,072 %', '113,55', '−43'],
        ['0,60', '1,164 %', '2,312 %', '2,140 %', '2,740 %', '14,107 %', '115,63', '−48'],
        ['0,50', '1,141 %', '2,259 %', '2,122 %', '2,739 %', '14,190 %', '116,55', '−39'],
        ['0,30', '1,121 %', '2,278 %', '2,206 %', '2,801 %', '14,455 %', '119,24', '−20'],
      ]),
    pieTabla('Selección de λ, medida sobre los semestres objetivo ya cerrados. Cada serie se indexa a su propio mínimo (100 = la mejor λ de ese nivel) y el criterio es el peor sobrecoste relativo entre los ocho niveles. El mínimo se alcanza en λ = 1,00, el borde superior de la rejilla.'),
    p('Conviene explicar el criterio, porque cambió respecto de una revisión anterior. Antes se usaba la media de las series indexadas; ese criterio resulta sensible a qué nivel tiene el mayor recorrido relativo, y ese nivel no es el mismo en todas las especificaciones. Aquí el total varía un 16 % entre los extremos de la rejilla y el cruce más fino sólo un 3 %, de modo que la media la decidiría el total por sí solo.'),
    p([txt('El criterio '), neg('minimax'), txt(' —minimizar el peor sobrecoste relativo— no tiene ese sesgo: acota lo que pierde el nivel peor servido, sea cual sea. Aplicado aquí elige λ = 1,00, con un sobrecoste máximo del 2,00 % sobre el mejor valor de cualquier nivel; la media indexada elige también 1,00. Los dos criterios coinciden, y conviene decir que el minimax se adoptó antes de conocer este resultado, no para justificarlo.')]),
    p('El reparto de óptimos por nivel explica de dónde sale ese 2,00 %: el total, la modalidad y el cruce sede·carrera·modalidad·condición tienen su mínimo exactamente en 1,00, mientras que los demás niveles lo tienen entre 0,50 y 0,85 y pierden como mucho un 2 % al subir hasta 1,00. Dicho de otro modo, no descontar nada es óptimo justo donde el modelo se usa para decidir, y casi gratuito donde no.'),
    nota('Qué significa un óptimo en cada borde.', 'Un óptimo pegado al borde INFERIOR de la rejilla es un síntoma de misespecificación: el estimador pide olvidar el pasado lo más deprisa posible porque es la única forma que tiene de seguir una deriva que no puede ver. Un óptimo cerca del borde SUPERIOR —λ = 1, sin descuento— es lo contrario: no queda deriva que perseguir y al estimador le conviene toda la muestra que pueda reunir. Es además el modelo más simple de los dos. Esta revisión ha recorrido la rejilla de un extremo al otro, y ése es quizá el mejor resumen de lo que han aportado las dos dimensiones nuevas.'),
    ...figura('16_lambda.png', 'Curva de selección de λ dentro del propio modelo, con cada serie indexada a su mínimo para poder compararlas en un solo eje.', { maxAlto: 330 }),
    p('Para el reparto por turno de los ingresantes se repitió el ejercicio por separado, midiendo el error en el nivel que incluye el turno. La curva desciende hasta λ ≈ 0,30 y se aplana después: la ganancia entre 0,30 y 0,05 es de apenas 0,11 puntos porcentuales. Se fijó λ = 0,30, ya que ir más lejos equivaldría a usar un único semestre sin ganancia medible y con riesgo de arrastrar cualquier anomalía puntual.'),
    nota('Qué significa λ = 1,00.', 'Que no hay descuento: todos los semestres pesan lo mismo. Es el modelo más simple de los que recorre la rejilla —la recencia deja de tener un parámetro que ajustar— y es una ventana mucho más larga que la de las revisiones anteriores (0,50, 0,65 y 0,90). El motivo es el del apartado 6.6: la deriva que antes obligaba a olvidar deprisa está ahora explícitamente modelada como composición por modalidad y por continuidad. Al ver la deriva, el modelo puede permitirse recordar. Y le conviene: las celdas de recuperados y de reinicios son pequeñas —un centenar y novecientos estudiantes por semestre— y descartar semestres antiguos las dejaría sin muestra. Conviene no leer esto como una propiedad permanente: si en el futuro apareciera una deriva nueva que el estado no recoge, el óptimo volvería a bajar, y ésa es precisamente la señal que hay que vigilar al reestimar.'),
    nota('La elección de λ se hace contra objetivos cerrados.', 'El último semestre del histórico seguía admitiendo altas en la fecha de extracción, de modo que como objetivo del backtesting está censurado por abajo. Y λ es justamente la palanca que baja el nivel proyectado: descontar el pasado reduce la matrícula proyectada y eso acerca artificialmente la proyección a un observado incompleto. Medido contra todos los objetivos, el óptimo del total se desplaza a λ = 0,90; medido contra los objetivos ya cerrados vuelve a λ = 1,00, que es el valor de producción. Toda la rejilla de este apartado, y las ablaciones de los apartados 6.5 y 6.6, se calculan sobre objetivos cerrados; las series completas se informan al lado en la salida del programa.'),

    h2('6.8 Estimación matemática del reparto de los ingresantes por turno'),
    p('El archivo de entrada declara los ingresantes por semestre, sede, carrera, modalidad y ciclo, pero no por turno. El modelo estima ese reparto con una composición multinomial contraída en cascada, sobre los ingresantes históricos —que son, por definición, la condición «ingresante» del estado:'),
    ...formula([
      'global → sede → sede × modalidad → sede × modalidad × paridad',
      '       → carrera × modalidad → carrera × modalidad × paridad',
      '       → celda completa',
    ]),
    p('El recorrido se detiene en el nivel más fino que disponga de evidencia. Una carrera consolidada llega hasta la celda completa; una carrera nueva, sin historia propia, se queda en el nivel de sede y modalidad y hereda su reparto. No hay regla especial para los programas nuevos: es el mismo mecanismo de contracción resolviendo un caso extremo.'),
    p([txt('La modalidad entra pronto en la cascada —antes que la carrera— porque es, con diferencia, el mejor predictor del turno de un ingresante: las modalidades semipresencial y a distancia son nocturnas en más del 98 % de los casos, mientras que la presencial reparte entre mañana, noche y, en Lima Norte, diurno. El apartado 4.6.1 cuantifica ese efecto de composición.')]),
    p('El modelo informa del nivel alcanzado en cada fila, de modo que siempre puede saberse de dónde procede una estimación concreta.'),
    ...figura('10_ingresantes_turno.png', 'Reparto estimado por turno de los ingresantes. La columna «Nivel usado» indica hasta dónde llegó la evidencia; las filas de INTELIGENCIA ARTIFICIAL corresponden a un programa nuevo de prueba.', { maxAlto: 540 }),

    h2('6.9 Estimación de la modalidad cuando no se declara'),
    p('La plantilla de entrada incluye una columna de modalidad y conviene rellenarla, porque es información que el área de admisión conoce y el modelo no puede deducir. Pero el modelo admite que falte, por dos razones prácticas: para dar continuidad a archivos preparados con la versión anterior de la plantilla, y porque en fases tempranas de planificación la modalidad de una campaña puede no estar decidida.'),
    p('Cuando una fila no declara modalidad, el modelo la reparte con la composición histórica de esa sede y esa carrera, contraída en cascada por el mismo procedimiento Dirichlet-Multinomial del apartado 6.3:'),
    ...formula([
      'global → sede → sede × paridad → sede × carrera',
      '       → sede × carrera × paridad',
      '',
      'restringido a las combinaciones (sede, carrera, modalidad) que existen',
    ]),
    p('La restricción de oferta es la pieza que hace útil el mecanismo. Sin ella, el reparto medio institucional colocaría un 19,7 % de estudiantes a distancia en Lima Norte, que no ofrece esa modalidad, o en Enfermería, que sólo se imparte de forma presencial. Con ella, esas filas se resuelven con un 100 % presencial, que es lo correcto.'),
    ...figura('09b_modalidad_nuevos.png', 'Reparto estimado por modalidad de un archivo de entrada que no la declara. Obsérvese que las filas de Lima Norte y las de Enfermería y Farmacia se resuelven con un 100 % presencial: la restricción de oferta actúa antes que la composición histórica.', { maxAlto: 480 }),
    p('La estimación se recalcula al mover λ, igual que el resto de los parámetros: no es un reparto congelado en el archivo, sino el resultado de aplicar el mismo estimador a los conteos históricos con la ponderación vigente.'),
    nota('Cuándo importa declararla.', 'La diferencia no es cosmética. Un grupo de 300 ingresantes de primer ciclo declarados como presenciales aporta unos 212 continuadores al semestre siguiente; declarados a distancia, unos 125. Sobre una campaña completa, la diferencia entre declarar la modalidad y dejar que el modelo la estime puede ser de varios centenares de estudiantes en el horizonte de proyección. El modelo avisa en pantalla de cuántas filas ha tenido que estimar.'),

    h2('6.10 Estimación del ciclo de ingreso cuando no se declara'),
    p([txt('La columna de ciclo admite el mismo tratamiento que la de modalidad, y por un motivo más de fondo: la planificación de la admisión suele fijarse por carrera y modalidad, no por ciclo. Pero el ciclo de ingreso '), neg('no es un detalle administrativo'), txt('. El 96,2 % de los ingresantes entra en el primero; los 1 205 restantes del histórico son convalidaciones de estudios previos, y colocarlos mal desplaza la matrícula proyectada a lo largo de todo el plan.')]),
    p('Que son convalidaciones reales, y no ruido de registro, lo confirma la edad: la media sube de 26,2 años en el ciclo 1 a 29,9 en el 2, 31,9 en el 3 y 34,0 en el 4.'),
    p('El reparto se estima en dos partes, porque los datos se comportan de forma distinta en cada una y necesitan contracciones distintas:'),
    tabla([1500, 2600, 2500, 2326],
      ['Componente', 'Qué mide', 'Cuánto varía', 'Contracción'],
      [
        ['Nivel', 'P(entra por encima del ciclo 1)', 'Del 0,2 % de Obstetricia al 19,7 % de Contabilidad; χ² = 1 643 con 17 g.l. Por modalidad, 2,4 % presencial frente a 5,3 % y 5,7 %; χ² = 207 con 2 g.l.', 'Beta-Binomial'],
        ['Forma', 'P(ciclo | entra por encima del 1)', 'Casi universal: 56,8 % al ciclo 2, 21,3 % al 3, 12,7 % al 4 y 9,2 % al 5 o más, con una desviación entre semestres de 5,8 pp en la cuota del ciclo 2.', 'Dirichlet-Multinomial'],
      ]),
    pieTabla('Las dos partes del reparto por ciclo de ingreso. La separación no es estética: el nivel necesita estimarse carrera a carrera y la forma se puede poner casi en común.'),
    ...formula([
      'NIVEL   global → paridad → modalidad × paridad → carrera × paridad',
      '                → carrera × modalidad × paridad',
      '                → sede × carrera × modalidad × paridad',
      '',
      'FORMA   global → modalidad → carrera → carrera × modalidad',
    ]),
    p([txt('La paridad del semestre entra en el nivel y no por capricho. La cuota de ingreso alto es del 2,5 % al 2,7 % en los primeros semestres y del 4,9 % al 5,9 % en los segundos, y la tentación es leerlo como que en agosto entran más convalidados. Es al revés: lo que cambia es '), neg('el denominador'), txt('. El recuento de convalidados es bastante estable —129 a 172 de media por paridad, con un coeficiente de variación del 33,9 %— mientras que la campaña de ciclo 1 se duplica entre paridades, con un 47,4 %. Como el modelo recibe un total y tiene que partirlo, necesita la cuota condicionada a la paridad, que es la que refleja ese efecto.')]),
    p('Sobre el resultado actúan después tres restricciones: el ciclo terminal del plan de la carrera, el tope de maduración de una sede recién abierta y el de un programa recién abierto. Lo que cae por encima del tope se acumula en el propio tope, igual que hace la matriz de avance con un estudiante retenido en el ciclo terminal. El reparto entero usa el método del resto mayor, de modo que la suma por fila coincide exactamente con el total declarado.'),
    nota('Un programa nuevo sólo puede ofrecer el ciclo 1.', 'La tercera restricción merece detalle porque es la que más se nota. Un programa que no figura en el histórico no tiene ciclos superiores que ofrecer: en el semestre en que arranca sólo existe el ciclo 1, de modo que todos sus ingresantes van ahí; en el siguiente existen el 1 y el 2, y así sucesivamente, conforme avanza su primera cohorte. Es la misma maduración que la de una sede nueva y responde al mismo hecho físico: no se puede convalidar hacia un ciclo que todavía no se imparte. Sin esta restricción, el reparto estimado heredaría la tasa de convalidación de su modalidad —en torno a un 4 %— y colocaría estudiantes en ciclos inexistentes. El ciclo base es el mayor declarado en el semestre de apertura, por si el programa se lanza convalidando desde otro afín; si no se declara ninguno, es el 1.'),
    nota('Qué NO puede hacer esta estimación.', 'Describe el comportamiento medio del histórico, no una política. Una convocatoria extraordinaria de traslados, un convenio nuevo con institutos o un endurecimiento de los requisitos de convalidación son decisiones institucionales que no están en los datos y que el modelo no puede anticipar. Cuando el área de admisión conozca el ciclo de ingreso, conviene declararlo; la estimación es el punto de partida razonable cuando no se conoce, no un sustituto de lo que ya se sabe.'),

    h2('6.11 Propagación de la varianza por el método delta'),
    p('Cada celda proyectada acumula tres fuentes de incertidumbre independiente, que se propagan a lo largo de la recursión:'),
    ...formula([
      'V(destino) = Σ [  x · φ · (1 − φ)                    realización multinomial',
      '                + x² · φ² · ( (1−q)/(q·n_q)',
      '                            + (1−A)/(A·n_A)',
      '                            + (1−U)/(U·n_U) )        error de parámetro',
      '                + φ² · V(origen)              ]      varianza propagada',
    ]),
    ...vinetas([
      [neg('Realización multinomial. '), txt('Aunque las probabilidades fueran exactas, el reparto concreto de x estudiantes entre destinos es aleatorio. Es el término que domina en las celdas pequeñas.')],
      [neg('Error de parámetro. '), txt('Las probabilidades se estiman con muestra finita. Se aplica el método delta al producto de las tres probabilidades, usando el tamaño muestral efectivo tras la contracción.')],
      [neg('Varianza propagada. '), txt('La incertidumbre del stock de origen se arrastra a la de destino, multiplicada por el cuadrado de la probabilidad de transición.')],
    ]),
    p('Estos componentes son independientes entre celdas, de modo que al agregar se suman en cuadratura y se diluyen: por eso el intervalo relativo del total institucional es estrecho y el de una celda individual es ancho. Es el comportamiento correcto y el que la validación confirma.'),
    nota('Una propiedad que la nueva dimensión pone a prueba.', 'Al partir cada celda en cinco condiciones, las celdas finas se quedan con muy pocos estudiantes y el término de realización multinomial pasa a dominar todavía más. Si la aritmética de la varianza estuviera mal planteada, ahí se vería: el intervalo del cruce más fino se quedaría corto. Ocurre lo contrario —su cobertura sube del 77,4 % al 90,0 %— y el factor de inflación sigue saliendo κ = 1,0. Es la comprobación más exigente a la que se ha sometido esta parte del modelo.'),
    salto(),
  ];
}

function escenarios() {
  return [
    h2('6.12 Estimación del reparto entre regular y recuperado'),
    p([txt('Es el único parámetro que la clasificación oficial obliga a estimar y que las versiones anteriores del modelo no tenían. El resto de la partición es contable —el rezago decide quién es reiniciado— pero dentro del flujo que se rematricula sin pausa conviven dos poblaciones que el flujo no distingue, y hay que separarlas con una probabilidad:')]),
    ...formula([
      'r(carrera, modalidad, condición de origen, ciclo) = P(llega como recuperado | rezago 1)',
    ]),
    p([txt('El recuperado es quien '), neg('no cerró el semestre anterior'), txt(' —abandono de ciclo, retiro o inhabilitación— y aun así se matricula en el inmediato siguiente. El dato que lo define, el campo '), cur('Condición'), txt(', sólo está en la base central, de modo que r se estima sobre su panel: 59 935 flujos de rezago 1 en seis semestres, de los que 495 llegan como recuperados. La tasa global es del '), neg('0,83 %'), txt('.')]),
    p('La estimación es una contracción Beta-Binomial en cascada, con la misma mecánica del apartado 6.2 y cuatro niveles:'),
    tabla([2600, 1200, 5226],
      ['Nivel', 'Celdas', 'Por qué está en la cascada'],
      [
        ['Global', '1', 'El punto de partida: 0,83 %.'],
        ['Ciclo', '11', 'La tasa dobla en el ciclo 1 (1,47 %) respecto del resto del plan (0,6 %–0,8 %). Es el mismo patrón que toda la fragilidad del modelo.'],
        ['Condición × ciclo', '53', 'La reincidencia: quien llega como recuperado vuelve a serlo el 21,2 % de las veces, frente al 0,6 % de un regular, el 1,7 % de un reiniciado y el 1,1 % de un ingresante. Es el salto más grande de la cascada.'],
        ['Modalidad × condición × ciclo', '115', 'Presencial 0,89 %, a distancia 0,80 %, semipresencial 0,51 %.'],
        ['Carrera × modalidad × condición × ciclo', '853', 'El nivel más fino, casi siempre sin evidencia propia suficiente.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Escalera de contracción de r. El parámetro de contracción, estimado por el método de los momentos sobre el nivel de condición × ciclo, es k = 27,4: una celda necesita del orden de 27 observaciones para pesar tanto como su nivel padre.'),
    p([txt('El orden de la cascada no es arbitrario: reproduce el de la continuación —ciclo primero, condición después, modalidad al final— y el nivel que más información aporta es el de la '), neg('condición de origen'), txt('. Que la reincidencia sea de veinticinco a uno es lo que obliga a que la condición forme parte del estado y no sea una etiqueta calculada al final: sin ella, el modelo repartiría el flujo de rezago 1 con la misma tasa del 0,83 % saliese de donde saliese, y perdería el único mecanismo que hace persistente a esta población.')]),
    nota('Por qué una probabilidad y no el salto de ciclo.', 'La alternativa contable —«es recuperado quien vuelve al mismo ciclo»— no cuesta parámetros y da un desglose exacto. Se descartó porque no reproduce la clasificación de la universidad: de las 4 978 llegadas sin pausa que repiten ciclo sólo 405 son recuperadas, un 8,1 %, de modo que aquella regla multiplicaba la categoría por diez y le atribuía el comportamiento promedio de una población que en su inmensa mayoría es regular. La relación inversa sí se cumple —el 81,8 % de los recuperados repite ciclo— pero eso no autoriza a invertir la implicación. El coste de hacerlo bien es un parámetro con su propia incertidumbre; el beneficio es que las cinco cifras del desglose son las que la universidad reconoce.'),
    nota('El límite de este estimador.', 'Con 495 casos en seis semestres, r se estima sobre una población pequeña y muy contraída: sólo los niveles de ciclo y de condición × ciclo tienen evidencia propia apreciable, y las celdas de carrera heredan prácticamente todo de sus padres. En la práctica eso significa que el modelo reparte los recuperados de forma casi proporcional dentro de cada combinación de condición y ciclo, y que no conviene leer el desglose de recuperados de una celda fina como una predicción con contenido propio. El apartado 8.3 lo confirma: el nivel de condición es el único de la validación que queda por debajo de su cobertura nominal.'),

    h2('6.13 Proyección de los ingresantes por nueva admisión'),
    p([txt('La quinta condición es un caso aparte porque no sale de ninguna de las dos fuentes habituales del modelo. No está en el archivo de entrada —el usuario declara la campaña de admisión, y estos estudiantes no forman parte de ella— y tampoco sale del stock, porque son personas que llevan uno o más semestres fuera y vuelven por la vía de una nueva admisión. El modelo tiene que '), neg('generarlos'), txt('.')]),
    p('Son 339 en los seis semestres utilizables, todos en Lima Sur, con una regularidad notable: 68 de media en los primeros semestres del año y 45 en los segundos. La pregunta de especificación es qué magnitud proyectar, y hay tres candidatas.'),
    tabla([3000, 1900, 1900, 2226],
      ['Magnitud proyectada', 'Media', 'Coef. de variación', 'Lectura'],
      [
        ['Nivel por paridad', '68 y 45', '15 % y 13 %', 'La más estable de las tres.'],
        ['Cuota sobre la matrícula', '0,35 %', '16 %', 'Añade la volatilidad del denominador.'],
        ['Cuota sobre continuadores', '0,47 %', '23 %', 'La peor: el denominador es el que más se mueve.'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.CENTER, AlignmentType.LEFT] }),
    pieTabla('Las tres formas de proyectar el flujo de nueva admisión, medidas sobre los seis semestres de la base central. Se proyecta la primera.'),
    p([txt('El modelo proyecta por tanto el '), neg('nivel'), txt(', separado por paridad del semestre, y lo reparte por sede, carrera, modalidad y ciclo con la composición histórica de esa misma paridad —89 combinaciones en los primeros semestres y 63 en los segundos—. El turno se asigna con el mismo estimador que el de los ingresantes (apartado 6.8), porque la base central no trae el turno en condiciones de usarse.')]),
    p('El reparto por ciclo es el que cabe esperar de una población que vuelve con créditos: un 30 % entra en el ciclo 1 y el resto se distribuye por todo el plan, con un repunte en el cuarto. Y su avance posterior es el más rápido de las cinco condiciones —convalida tres o más ciclos el 19,6 % de las veces— por la misma razón.'),
    nota('La contrapartida de proyectar un nivel.', 'Un nivel constante no crece con la institución: si la matrícula se duplicara, el modelo seguiría inyectando 68 y 45 reingresos por semestre, y su peso relativo caería a la mitad. Con el horizonte habitual de seis semestres el efecto es pequeño —son cuatro décimas de punto de la matrícula— y la estabilidad observada compensa; pero es un supuesto que conviene revisar en cada reestimación, y el apartado 11.1 lo recoge como limitación.'),

    h1('7. Los tres escenarios'),
    h2('7.1 Qué debe ser un escenario'),
    p('Un escenario de planificación tiene que cumplir dos condiciones que un intervalo de confianza corriente no cumple.'),
    ...numerada([
      [neg('Coherencia. '), txt('Debe describir un estado del mundo posible y completo. Si la retención cae, cae para todas las cohortes a la vez, no de forma independiente en cada celda.')],
      [neg('Aditividad. '), txt('El total del escenario tiene que ser la suma de sus celdas. Si el escenario pesimista del total no coincide con la suma de los escenarios pesimistas por carrera o por modalidad, la cifra no sirve para repartir aulas ni presupuesto.')],
    ]),
    p('Ambas condiciones se satisfacen si —y sólo si— el escenario se construye sobre el componente sistémico de la incertidumbre, aquel que mueve todas las celdas en el mismo sentido.'),

    h2('7.2 Construcción'),
    p('Los tres escenarios aplican un desplazamiento común en escala logit a todas las tasas de continuación:'),
    ...formula([
      'logit q_L(escenario) = logit q_L(central) ± z · σ',
      '',
      'σ = 0,0459   desviación típica del choque de periodo (5 g.l.)',
      'z = 1,476    cuantil t de Student para una confianza del 80 %',
      '',
      'Optimista   +z·σ = +0,068 en logit',
      'Moderado     0',
      'Pesimista   −z·σ = −0,068 en logit',
    ]),
    p('Aplicar el desplazamiento en escala logit y no en la tasa directa tiene dos ventajas: la tasa resultante nunca se sale del intervalo [0, 1], y el efecto es proporcionalmente mayor donde la tasa es intermedia y menor donde ya está cerca de sus extremos, que es como se comportan los choques reales.'),
    p([txt('Ese segundo rasgo cobra sentido añadido con las dos dimensiones de composición en el modelo. La continuación de un reiniciado en el tercer ciclo (53,5 %) está en la zona de máxima sensibilidad del logit, mientras que la de un regular en el mismo ciclo (88,5 %) está cerca del techo. Un choque sistémico de la misma magnitud en logit mueve 1,7 puntos porcentuales a la primera y sólo 0,7 a la segunda. Eso es exactamente lo que se quiere: el escenario pesimista castiga más donde la población es más frágil, sin que haya que programarlo.')]),
    p([txt('Se emplea el cuantil t de Student y no el normal porque σ se estima con sólo 5 grados de libertad: siete semestres de origen menos el parámetro estacional y la media. Con tan pocas observaciones, la distribución normal subestimaría la incertidumbre. Para una confianza del 80 %, z pasa de 1,282 (normal) a 1,476 (t con 5 g.l.), un 15 % más ancho.')]),
    nota('Por qué sólo la continuación.', 'El choque no se aplica a los ingresantes: su número lo fija el archivo de entrada y es un supuesto del usuario, no una estimación del modelo. Un escenario que alterase también el ingreso —o su reparto por modalidad— mezclaría la incertidumbre del comportamiento estudiantil con una decisión institucional, y el usuario no podría saber cuál de las dos está viendo.'),

    h2('7.3 Escenario frente a intervalo de predicción'),
    p('El modelo entrega ambas magnitudes, y conviene no confundirlas. La diferencia es visible en los datos de validación:'),
    tabla([3400, 2700, 2926],
      ['Nivel de agregación', 'Cobertura de la banda de escenarios', 'Cobertura del intervalo de predicción'],
      [
        ['Total institucional', '33,3 %', '83,3 %'],
        ['Sede', '58,3 %', '83,3 %'],
        ['Modalidad', '44,4 %', '94,4 %'],
        ['Continuidad', '43,3 %', '53,3 %'],
        ['Carrera', '24,9 %', '93,8 %'],
        ['Sede × carrera', '32,4 %', '94,2 %'],
        ['Sede × carrera × modalidad', '27,6 %', '94,4 %'],
        ['… × continuidad', '30,6 %', '85,4 %'],
        ['… × ciclo', '10,1 %', '89,7 %'],
        ['… × turno', '2,5 %', '90,0 %'],
      ], { al: [AlignmentType.LEFT, AlignmentType.CENTER, AlignmentType.CENTER] }),
    pieTabla('Cobertura empírica media sobre los tres horizontes, para un nivel nominal del 80 %. La banda de escenarios no pretende cubrir el dato observado; el intervalo de predicción sí.'),
    p('La banda de escenarios cubre menos del 80 % en todos los niveles, y eso es correcto: no es un intervalo de predicción. Recoge únicamente el desplazamiento sistémico y deja fuera, por diseño, el azar de realización de cada celda. Leerla como si fuese un intervalo de confianza llevaría a subestimar el riesgo.'),
    p('Nótese además que la banda se ha estrechado en esta revisión —σ pasó de 0,068 a 0,045— aunque su cobertura ha subido, porque el punto central ha mejorado más de lo que la banda se ha estrechado. Ese estrechamiento no es un deterioro: es la contrapartida de haber convertido en estructura una parte de lo que antes era choque. La banda describe hoy un desplazamiento sistémico más pequeño porque el modelo ya no necesita que ese desplazamiento explique la deriva de composición.'),
    p('El intervalo de predicción suma ambos componentes y sí está calibrado:'),
    ...formula([
      'semiamplitud(A) = z · √( D_A²  +  V_A )',
      '',
      '  D_A  sensibilidad sistémica del agregado A a un choque de un σ.',
      '       Común a todas las celdas → al agregar se suma LINEALMENTE.',
      '  V_A  varianza independiente acumulada (apartado 6.11).',
      '       Al agregar se suma en CUADRATURA → se diluye en los totales',
      '       y domina en las celdas pequeñas.',
    ]),
    p('La distinta álgebra de agregación de los dos términos es la razón por la que el intervalo relativo del total es estrecho y el de una celda con cinco estudiantes es muy ancho, sin que haga falta ningún tratamiento especial para cada nivel.'),

    h2('7.4 Calibración del factor de inflación'),
    p('Queda por comprobar si esa aritmética reproduce la dispersión realmente observada. Para ello se introdujo un factor de inflación κ sobre el componente independiente y se buscó el valor que iguala la cobertura empírica a la nominal.'),
    tabla([880, 1180, 1180, 1180, 1250, 1680, 1676],
      ['κ', 'Total', 'Continuidad', 'Carrera', 'Sede×Carr.', '… × continuidad', '… × turno'],
      [
        ['1,0', '83,3 %', '53,3 %', '93,8 %', '94,2 %', '85,4 %', '90,0 %'],
        ['1,5', '83,3 %', '53,3 %', '98,0 %', '98,4 %', '93,8 %', '93,9 %'],
        ['2,0', '100,0 %', '53,3 %', '100,0 %', '100,0 %', '96,5 %', '95,9 %'],
        ['3,0', '100,0 %', '53,3 %', '100,0 %', '100,0 %', '97,9 %', '97,6 %'],
      ]),
    pieTabla('Cobertura empírica media según el factor de inflación de varianza, para un nivel nominal del 80 %.'),
    p([txt('El valor seleccionado es '), neg('κ = 1,0'), txt(', que deja la cobertura media de los tres niveles desagregados en 88,3 % frente al 80 % nominal. Es decir: la descomposición de varianza del apartado 6.11 reproduce por sí sola la dispersión observada fuera de muestra, sin factor de corrección.')]),
    nota('Por qué esto importa.', 'Un modelo cuyo intervalo hubiera necesitado κ = 3 para cubrir lo observado estaría admitiendo que su aritmética de la incertidumbre está mal planteada y que el intervalo se sostiene sobre un parche. Que κ salga 1,0 es la validación más fuerte que ofrece este trabajo, y es un resultado que se puede volver a comprobar en cada reestimación. Ha salido 1,0 en las cinco revisiones del modelo.'),
    p('La cobertura no es uniforme entre niveles: los intermedios quedan por encima del nominal (94 %) y los desagregados también (85 a 90 %). Es el patrón esperable, y ha mejorado mucho: el cruce más fino era el punto débil de las revisiones anteriores —68,5 % en la primera y 79,8 % con la modalidad— y está ahora en el 90,0 %. El intervalo se quedaba corto justamente donde se mezclaban poblaciones con comportamientos muy distintos; ahora esa diferencia está en el punto central y no tiene que absorberla el margen.'),
    p([txt('La excepción es el nivel de '), neg('continuidad'), txt(', que se queda en el 53,3 % y no se mueve ni con κ = 3: hace falta llegar a κ = 6 para que alcance el nominal. Son cinco celdas y quince comparaciones, de modo que el dato es ruidoso, pero apunta a un límite real del modelo. El reparto entre condiciones depende de cosas que no están en los datos: el volumen de reingresos, que responde a decisiones institucionales —campañas de recuperación, amnistías de deuda, flexibilizaciones de matrícula—, y el de recuperados y de reingresos por nueva admisión, que son poblaciones de apenas un centenar de estudiantes donde una variación de veinte personas es un 20 %. Nada de eso es un choque sistémico de la continuación, que es lo único que el margen modela. Conviene leer el '), cur('reparto'), txt(' entre condiciones como un orden de magnitud; el '), cur('total'), txt(' al que suman está, en cambio, bien cubierto. El apartado 11.1 lo recoge como limitación.')]),
    salto(),
  ];
}

module.exports = { especificacion, herramientas, escenarios };
